(function () {
    'use strict';

    // Supervisor color palette for row highlighting
    var SUPERVISOR_COLORS = {
        'Scott':           { bg: '#e3f2fd', dark: '#0d2137' },
        'Miranda':         { bg: '#fce4ec', dark: '#2a1015' },
        'Kathy':           { bg: '#f3e5f5', dark: '#1f0f24' },
        'Angie':           { bg: '#fff3e0', dark: '#2a1d08' },
        'Sarah':           { bg: '#e8f5e9', dark: '#0d2010' },
        'Schnelle':        { bg: '#e0f7fa', dark: '#0a1f22' },
        'Nicole':          { bg: '#fff9c4', dark: '#2a2508' },
        'Angela Allison':  { bg: '#f1f8e9', dark: '#1a2410' }
    };

    function _getSupervisorColor(empName) {
        try {
            var sups = JSON.parse(localStorage.getItem('devCoachingTool_employeeSupervisors') || '{}');
            var sup = sups[empName];
            if (sup && SUPERVISOR_COLORS[sup]) {
                var isDark = document.documentElement.getAttribute('data-theme') === 'dark';
                return isDark ? SUPERVISOR_COLORS[sup].dark : SUPERVISOR_COLORS[sup].bg;
            }
        } catch (_e) {}
        return null;
    }

    function _getSupervisorLightColor(empName) {
        try {
            var sups = JSON.parse(localStorage.getItem('devCoachingTool_employeeSupervisors') || '{}');
            var sup = sups[empName];
            if (sup && SUPERVISOR_COLORS[sup]) return SUPERVISOR_COLORS[sup].bg;
        } catch (_e) {}
        return '#ccc';
    }

    function _escapeHtml(str) {
        var mod = window.DevCoachModules?.sharedUtils;
        if (mod?.escapeHtml) return mod.escapeHtml(str);
        return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
    }
    function _formatMetricDisplay(key, value) {
        return typeof window.formatMetricDisplay === 'function' ? window.formatMetricDisplay(key, value) : String(value);
    }
    function _getTeamMembersForWeek(weekKey) {
        return typeof window.getTeamMembersForWeek === 'function' ? window.getTeamMembersForWeek(weekKey) : [];
    }
    function _getLatestWeeklyKey() {
        return typeof window.getLatestWeeklyKey === 'function' ? window.getLatestWeeklyKey() : null;
    }
    function _getWeeklyData() {
        return typeof weeklyData !== 'undefined' ? weeklyData : {};
    }
    function _getYtdData() {
        return typeof ytdData !== 'undefined' ? ytdData : {};
    }

    // ── Period selector ──
    var _selectedRankingPeriodKey = null;

    function _getAvailableRankingPeriods() {
        var periods = [];
        var wData = _getWeeklyData();
        var yData = _getYtdData();

        Object.keys(wData).forEach(function(key) {
            var data = wData[key];
            var meta = data?.metadata || {};
            var count = (data?.employees || []).length;
            if (count < 2) return;
            var pType = meta.periodType || 'week';
            var endStr = meta.endDate || (key.includes('|') ? key.split('|')[1] : '');
            var label = meta.label || _fmtPeriodLabel(key, pType);
            periods.push({ key: key, label: label, type: pType, source: 'weekly', count: count, endDate: endStr });
        });

        Object.keys(yData).forEach(function(key) {
            var data = yData[key];
            var meta = data?.metadata || {};
            if (meta.autoGeneratedYtd) return;
            var count = (data?.employees || []).length;
            if (count < 2) return;
            var pType = meta.periodType || 'ytd';
            var endStr = meta.endDate || (key.includes('|') ? key.split('|')[1] : '');
            var label = meta.label || _fmtPeriodLabel(key, pType);
            periods.push({ key: key, label: label, type: pType, source: 'ytd', count: count, endDate: endStr });
        });

        periods.sort(function(a, b) {
            var aDate = a.endDate || a.key.split('|')[0] || '';
            var bDate = b.endDate || b.key.split('|')[0] || '';
            return bDate.localeCompare(aDate);
        });
        return periods;
    }

    function _fmtPeriodLabel(key, type) {
        var parts = key.split('|');
        var endDate = parts[1] || parts[0] || '';
        var prefix = type === 'ytd' ? 'YTD' : type === 'month' ? 'Monthly' : type === 'quarter' ? 'Quarterly' : type === 'daily' ? 'Daily' : 'Weekly';
        return prefix + ' ending ' + endDate;
    }

    function _renderRankingPeriodSelector(selectedValue) {
        var periods = _getAvailableRankingPeriods();
        var typeOrder = ['ytd', 'quarter', 'month', 'week', 'daily'];
        var typeLabels = { ytd: 'YTD', quarter: 'Quarterly', month: 'Monthly', week: 'Weekly', daily: 'Daily' };
        var grouped = {};
        periods.forEach(function(p) {
            var t = p.type || 'week';
            if (!grouped[t]) grouped[t] = [];
            grouped[t].push(p);
        });

        var html = '<div style="margin-bottom: 16px; display: flex; align-items: center; gap: 12px; flex-wrap: wrap;">';
        html += '<label style="font-weight: 600; color: #555; font-size: 0.9em;">Period:</label>';
        html += '<select id="rankingPeriodSelect" style="padding: 6px 10px; border: 1px solid #ccc; border-radius: 6px; font-size: 0.9em; min-width: 260px;">';
        html += '<option value="">Auto (Best Available)</option>';

        typeOrder.forEach(function(t) {
            if (!grouped[t] || grouped[t].length === 0) return;
            html += '<optgroup label="' + (typeLabels[t] || t) + '">';
            grouped[t].forEach(function(p) {
                var val = p.key;
                var sel = (val === selectedValue) ? ' selected' : '';
                html += '<option value="' + _escapeHtml(val) + '"' + sel + '>' + _escapeHtml(p.label) + ' (' + p.count + ' employees)</option>';
            });
            html += '</optgroup>';
        });

        html += '</select></div>';
        return html;
    }

    function _onRankingPeriodChange() {
        var select = document.getElementById('rankingPeriodSelect');
        if (!select) return;
        _selectedRankingPeriodKey = select.value || null;
        renderCenterRanking();
    }

    /**
     * Score an employee using the On/Off track 5-metric system.
     * Returns { ratingAverage, trackLabel, scores, values, reliability } or null.
     */
    function scoreEmployee(emp, year) {
        var onOff = window.DevCoachModules?.onOffTracker;
        if (!onOff?.calculateYearEndOnOffMirror) return null;

        var result = onOff.calculateYearEndOnOffMirror(emp, year);
        if (!result) return null;

        // For center ranking, include employees even if they're missing some
        // metrics. Calculate a partial rating average from available scores.
        var scores = result.scores || {};
        var ratingAverage = result.ratingAverage;
        var trackLabel = result.trackLabel || 'N/A';
        var trackStatusValue = result.trackStatusValue || 'unknown';

        if (!result.isComplete) {
            var validScores = Object.values(scores).filter(function (s) { return s !== null; });
            if (validScores.length === 0) return null;
            var sum = validScores.reduce(function (a, b) { return a + b; }, 0);
            ratingAverage = sum / validScores.length;
            if (ratingAverage <= 1.79) {
                trackLabel = 'Off Track'; trackStatusValue = 'off-track';
            } else if (ratingAverage <= 2.79) {
                trackLabel = 'On Track/Successful'; trackStatusValue = 'on-track-successful';
            } else {
                trackLabel = 'On Track/Exceptional'; trackStatusValue = 'on-track-exceptional';
            }
        }

        return {
            ratingAverage: ratingAverage,
            trackLabel: trackLabel,
            trackStatusValue: trackStatusValue,
            scores: scores,
            values: result.values || {},
            reliability: parseFloat(emp.reliability) || 0,
            surveyTotal: parseInt(emp.surveyTotal, 10) || 0
        };
    }

    /**
     * Build rankings from the best available data source for a year.
     * Uses getLatestYearPeriodForEmployee logic via YTD data, or falls
     * back to the latest weekly upload with the most employees.
     */
    function buildCenterRankings() {
        var currentYear = new Date().getFullYear();
        var wData = _getWeeklyData();
        var yData = _getYtdData();

        // Find the single most recent upload with 30+ employees.
        // Priority: newest real YTD > newest non-YTD upload.
        // No merging. One period. That's it.
        var bestYtd = null;
        var bestYtdTime = 0;
        var bestYtdKey = '';
        var bestYtdSource = '';

        Object.entries(yData).forEach(function (entry) {
            var meta = entry[1]?.metadata || {};
            if (meta.autoGeneratedYtd) return;
            var endStr = meta.endDate || (entry[0].includes('|') ? entry[0].split('|')[1] : '');
            var endYear = parseInt(String(endStr).split('-')[0], 10);
            if (endYear !== currentYear) return;
            var count = (entry[1].employees || []).length;
            if (count < 30) return;
            var uploadedAt = meta.uploadedAt ? new Date(meta.uploadedAt).getTime() : 0;
            if (uploadedAt > bestYtdTime) {
                bestYtd = entry[1];
                bestYtdTime = uploadedAt;
                bestYtdKey = entry[0];
                bestYtdSource = meta.label || 'YTD upload';
            }
        });

        // Fall back to newest weekly/custom upload with 30+ employees
        var bestWeekly = null;
        var bestWeeklyTime = 0;
        var bestWeeklyKey = '';
        var bestWeeklySource = '';

        Object.entries(wData).forEach(function (entry) {
            var meta = entry[1]?.metadata || {};
            var endStr = meta.endDate || (entry[0].includes('|') ? entry[0].split('|')[1] : '');
            var endYear = parseInt(String(endStr).split('-')[0], 10);
            if (endYear !== currentYear) return;
            var count = (entry[1].employees || []).length;
            if (count < 30) return;
            var uploadedAt = meta.uploadedAt ? new Date(meta.uploadedAt).getTime() : 0;
            if (uploadedAt > bestWeeklyTime) {
                bestWeekly = entry[1];
                bestWeeklyTime = uploadedAt;
                bestWeeklyKey = entry[0];
                bestWeeklySource = meta.label || entry[0];
            }
        });

        // Use the most recently uploaded source. Real YTD wins ties.
        var bestPeriod, bestKey, bestSource;
        if (bestYtd && (!bestWeekly || bestYtdTime >= bestWeeklyTime)) {
            bestPeriod = bestYtd;
            bestKey = bestYtdKey;
            bestSource = bestYtdSource;
        } else if (bestWeekly) {
            bestPeriod = bestWeekly;
            bestKey = bestWeeklyKey;
            bestSource = bestWeeklySource;
        } else {
            return null;
        }

        // Use this period's employees directly. No merging. No overlaying.
        var baseEmployees = {};
        (bestPeriod.employees || []).forEach(function (emp) {
            if (emp && emp.name) baseEmployees[emp.name] = emp;
        });

        var mergedEmployees = Object.values(baseEmployees);

        var rankings = _scoreAndRank(mergedEmployees, currentYear);

        // Identify team members — check weekly keys first, fall back to YTD/any key
        var latestKey = _getLatestWeeklyKey();
        if (!latestKey) {
            var teamFilter = window.DevCoachModules?.teamFilter;
            if (teamFilter?.getTeamSelectionContext) {
                latestKey = teamFilter.getTeamSelectionContext().weekKey || '';
            }
        }
        var teamMembers = latestKey ? _getTeamMembersForWeek(latestKey) : [];
        var teamSet = new Set(teamMembers);

        return {
            rankings: rankings,
            totalEmployees: rankings.length,
            source: bestSource,
            periodKey: bestKey,
            teamMembers: teamSet
        };
    }

    /**
     * Shared scoring + ranking logic. Takes an array of employee objects,
     * scores each one, assigns per-metric ranks and composite rank.
     * Returns the sorted rankings array.
     */
    function _scoreAndRank(employees, year) {
        var rankings = [];
        employees.forEach(function (emp) {
            if (!emp || !emp.name) return;
            var score = scoreEmployee(emp, year);
            if (!score) return;

            rankings.push({
                name: emp.name,
                ratingAverage: score.ratingAverage,
                trackLabel: score.trackLabel,
                trackStatusValue: score.trackStatusValue,
                scores: score.scores,
                values: score.values,
                reliability: score.reliability,
                surveyTotal: score.surveyTotal
            });
        });

        // Rank by each individual metric (lower rank = better)
        var metricRankKeys = [
            { key: 'aht', field: 'values.aht', reverse: true },
            { key: 'adherence', field: 'values.adherence', reverse: false },
            { key: 'sentiment', field: 'values.sentiment', reverse: false },
            { key: 'associateOverall', field: 'values.associateOverall', reverse: false },
            { key: 'reliability', field: 'reliability', reverse: true }
        ];

        metricRankKeys.forEach(function (mk) {
            var sorted = rankings.slice().sort(function (a, b) {
                var aVal = mk.field.includes('.') ? a.values[mk.field.split('.')[1]] : a[mk.field];
                var bVal = mk.field.includes('.') ? b.values[mk.field.split('.')[1]] : b[mk.field];
                // Treat null/undefined/NaN as worst possible rank
                var aNull = aVal === null || aVal === undefined || (typeof aVal === 'number' && isNaN(aVal));
                var bNull = bVal === null || bVal === undefined || (typeof bVal === 'number' && isNaN(bVal));
                if (aNull && bNull) return 0;
                if (aNull) return 1;  // a goes to bottom
                if (bNull) return -1; // b goes to bottom
                return mk.reverse ? (aVal - bVal) : (bVal - aVal);
            });
            sorted.forEach(function (emp, idx) {
                if (!emp.metricRanks) emp.metricRanks = {};
                emp.metricRanks[mk.key] = idx + 1;
            });
        });

        // Composite rank = average of only present metric ranks (lower = better).
        // Missing metrics are excluded from the average so employees aren't
        // artificially boosted or penalized for missing data.
        rankings.forEach(function (r) {
            var ranks = r.metricRanks || {};
            var presentRanks = [];
            ['aht', 'adherence', 'sentiment', 'associateOverall'].forEach(function (k) {
                if (ranks[k] && ranks[k] > 0) presentRanks.push(ranks[k]);
            });
            r.compositeScore = presentRanks.length > 0
                ? presentRanks.reduce(function (a, b) { return a + b; }, 0) / presentRanks.length
                : Infinity;
        });

        // Sort by composite score (lower = better)
        rankings.sort(function (a, b) {
            return a.compositeScore - b.compositeScore;
        });

        rankings.forEach(function (r, i) { r.rank = i + 1; });
        return rankings;
    }

    /**
     * Build rankings for a specific period key (weekly or YTD).
     * Unlike buildCenterRankings which merges all periods,
     * this ranks only the employees present in the given period.
     */
    function buildRankingsForPeriod(periodKey) {
        if (!periodKey) return null;
        var wData = _getWeeklyData();
        var yData = _getYtdData();
        var period = wData[periodKey] || yData[periodKey];
        if (!period || !period.employees?.length) return null;

        var meta = period.metadata || {};
        var endStr = meta.endDate || (periodKey.includes('|') ? periodKey.split('|')[1] : '');
        var endYear = parseInt(String(endStr).split('-')[0], 10) || new Date().getFullYear();

        var rankings = _scoreAndRank(period.employees, endYear);
        if (!rankings.length) return null;

        // Identify team members for this period
        var teamMembers = _getTeamMembersForWeek(periodKey);
        var teamSet = new Set(teamMembers);

        return {
            rankings: rankings,
            totalEmployees: rankings.length,
            source: meta.label || periodKey,
            periodKey: periodKey,
            teamMembers: teamSet
        };
    }

    /**
     * Render the center ranking view
     */
    function renderCenterRanking() {
        var container = document.getElementById('centerRankingContent');
        if (!container) return;

        var currentSelectValue = _selectedRankingPeriodKey || '';

        var data;
        if (_selectedRankingPeriodKey) {
            data = buildRankingsForPeriod(_selectedRankingPeriodKey);
        } else {
            data = buildCenterRankings();
        }

        if (!data || data.rankings.length === 0) {
            container.innerHTML = _renderRankingPeriodSelector(currentSelectValue) +
                '<p style="color: #94a3b8; text-align: center; padding: 40px;">No ranking data available. Upload a full center data set (30+ employees) to see rankings.</p>';
            var sel = document.getElementById('rankingPeriodSelect');
            if (sel) sel.addEventListener('change', _onRankingPeriodChange);
            return;
        }

        var html = '';

        // Period selector
        html += _renderRankingPeriodSelector(currentSelectValue);

        // Header
        html += '<div style="margin-bottom: 20px; padding: 15px; background: #e3f2fd; border-radius: 8px; border-left: 4px solid #1565c0;">';
        html += '<strong>Center Rankings</strong> &mdash; ' + data.totalEmployees + ' employees scored';
        html += '<br><span style="color: #666; font-size: 0.85em;">Source: ' + _escapeHtml(data.source) + ' | Ranked by On/Off Track score (reliability as tiebreaker)</span>';
        html += '</div>';

        // Team summary
        var teamRanks = data.rankings.filter(function (r) { return data.teamMembers.has(r.name); });
        if (teamRanks.length > 0) {
            html += '<div style="margin-bottom: 20px; padding: 15px; background: #fff; border-radius: 8px; border: 1px solid #ddd; box-shadow: 0 1px 3px rgba(0,0,0,0.08);">';
            html += '<h4 style="margin-top: 0; color: #1a1a2e;">Your Team</h4>';
            html += '<div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 10px;">';

            teamRanks.forEach(function (r) {
                var statusColor = r.trackStatusValue === 'on-track-exceptional' ? '#2e7d32' :
                    r.trackStatusValue === 'on-track-successful' ? '#f57f17' : '#c62828';
                var statusBg = r.trackStatusValue === 'on-track-exceptional' ? '#e8f5e9' :
                    r.trackStatusValue === 'on-track-successful' ? '#fff8e1' : '#fbe9e7';
                var percentile = Math.round((1 - (r.rank - 1) / data.totalEmployees) * 100);

                html += '<div style="padding: 12px 16px; background: ' + statusBg + '; border-radius: 8px; border-left: 4px solid ' + statusColor + ';">';
                html += '<div class="ranking-card-name" data-employee="' + _escapeHtml(r.name) + '" style="font-weight: bold; font-size: 1.05em; cursor: pointer; text-decoration: underline;">' + _escapeHtml(r.name) + '</div>';
                html += '<div style="margin-top: 4px;">';
                html += '<span style="font-size: 1.3em; font-weight: bold; color: ' + statusColor + ';">#' + r.rank + '</span>';
                html += ' <span style="color: #666; font-size: 0.85em;">of ' + data.totalEmployees + ' (top ' + percentile + '%)</span>';
                html += '</div>';
                html += '<div style="margin-top: 4px; font-size: 0.85em; color: #555;">' + _escapeHtml(r.trackLabel) + ' &mdash; Avg rank: ' + r.compositeScore.toFixed(1) + '</div>';
                html += '<div style="font-size: 0.8em; color: #888;">Reliability: ' + _formatMetricDisplay('reliability', r.reliability) + ' (#' + (r.metricRanks?.reliability || '?') + ')</div>';
                html += '</div>';
            });

            html += '</div></div>';
        }

        // Store data for re-sorting
        _lastRankingData = data;
        _currentSort = { key: 'composite', dir: 'asc' };

        // Full ranking table
        html += '<div id="centerRankingTableWrapper" style="padding: 20px; background: #fff; border-radius: 8px; border: 1px solid #ddd; box-shadow: 0 1px 3px rgba(0,0,0,0.08);">';
        html += '<h4 style="margin-top: 0; color: #1a1a2e;">Full Center Rankings</h4>';
        html += '<p style="margin: 0 0 12px 0; color: #666; font-size: 0.85em;">Click any column header to sort. Each metric shows value and rank (#).</p>';
        html += '</div>';

        container.innerHTML = html;
        renderRankingTable('composite', 'asc');

        // Bind period selector
        var sel = document.getElementById('rankingPeriodSelect');
        if (sel) sel.addEventListener('change', _onRankingPeriodChange);

        // Bind team card name clicks to scroll to that employee's row
        container.querySelectorAll('.ranking-card-name').forEach(function (el) {
            el.addEventListener('click', function () {
                var name = el.dataset.employee;
                var row = document.querySelector('#centerRankingTableWrapper tr[data-employee="' + CSS.escape(name) + '"]');
                if (row) {
                    row.scrollIntoView({ behavior: 'smooth', block: 'center' });
                    row.style.transition = 'background 0.3s';
                    row.style.background = '#bbdefb';
                    setTimeout(function () { row.style.background = ''; }, 2000);
                }
            });
        });
    }

    var _lastRankingData = null;
    var _currentSort = { key: 'composite', dir: 'asc' };

    var SORT_COLUMNS = [
        { key: 'composite', label: 'Avg Rank', getValue: function(r) { return r.compositeScore; }, reverse: false },
        { key: 'score', label: 'Score', getValue: function(r) { return r.ratingAverage; }, reverse: true },
        { key: 'aht', label: 'AHT', getValue: function(r) { return r.values.aht; }, reverse: false },
        { key: 'adherence', label: 'Adherence', getValue: function(r) { return r.values.adherence; }, reverse: true },
        { key: 'sentiment', label: 'Sentiment', getValue: function(r) { return r.values.sentiment; }, reverse: true },
        { key: 'associateOverall', label: 'Assoc Overall', getValue: function(r) { return r.values.associateOverall; }, reverse: true },
        { key: 'reliability', label: 'Reliability', getValue: function(r) { return r.reliability; }, reverse: false }
    ];

    function renderRankingTable(sortKey, sortDir) {
        var wrapper = document.getElementById('centerRankingTableWrapper');
        if (!wrapper || !_lastRankingData) return;
        var data = _lastRankingData;

        // Sort rankings
        var col = SORT_COLUMNS.find(function(c) { return c.key === sortKey; });
        var sorted = data.rankings.slice().sort(function(a, b) {
            var aVal = col ? col.getValue(a) : a.compositeScore;
            var bVal = col ? col.getValue(b) : b.compositeScore;
            aVal = aVal !== null && aVal !== undefined ? aVal : (sortDir === 'asc' ? Infinity : -Infinity);
            bVal = bVal !== null && bVal !== undefined ? bVal : (sortDir === 'asc' ? Infinity : -Infinity);
            return sortDir === 'asc' ? (aVal - bVal) : (bVal - aVal);
        });

        var thStyle = 'padding: 6px 3px; text-align: center; border-bottom: 2px solid #ddd; cursor: pointer; user-select: none; font-size: 0.85em;';
        var arrow = function(key) {
            if (key !== sortKey) return ' <span style="opacity: 0.3;">&#8597;</span>';
            return sortDir === 'asc' ? ' <span style="color: #1565c0;">&#9650;</span>' : ' <span style="color: #1565c0;">&#9660;</span>';
        };

        var html = '<div>';
        html += '<table style="width: 100%; border-collapse: collapse; font-size: 0.82em; table-layout: auto;">';
        html += '<thead><tr style="background: #f5f5f5;">';
        html += '<th style="' + thStyle + ' width: 30px;">#</th>';
        html += '<th style="' + thStyle + ' text-align: left;">Name</th>';
        html += '<th class="rank-sort-header" data-sort="composite" style="' + thStyle + '">Avg' + arrow('composite') + '</th>';
        html += '<th class="rank-sort-header" data-sort="score" style="' + thStyle + '">Score' + arrow('score') + '</th>';
        html += '<th style="' + thStyle + '">Status</th>';
        html += '<th class="rank-sort-header" data-sort="aht" style="' + thStyle + '">AHT' + arrow('aht') + '</th>';
        html += '<th class="rank-sort-header" data-sort="adherence" style="' + thStyle + '">Adh' + arrow('adherence') + '</th>';
        html += '<th class="rank-sort-header" data-sort="sentiment" style="' + thStyle + '">Sent' + arrow('sentiment') + '</th>';
        html += '<th class="rank-sort-header" data-sort="associateOverall" style="' + thStyle + '">Assoc' + arrow('associateOverall') + '</th>';
        html += '<th class="rank-sort-header" data-sort="reliability" style="' + thStyle + '">Rel' + arrow('reliability') + '</th>';
        html += '</tr></thead><tbody>';

        sorted.forEach(function (r, idx) {
            var isTeam = data.teamMembers.has(r.name);
            var supColor = _getSupervisorColor(r.name);
            var isDark = document.documentElement.getAttribute('data-theme') === 'dark';
            var defaultBg = isDark ? (r.rank % 2 === 0 ? '#1a1f2e' : 'transparent') : (r.rank % 2 === 0 ? '#fafafa' : '#fff');
            var rowBg = supColor || (isTeam ? (isDark ? '#0d2a1a' : '#e8f5e9') : defaultBg);
            var fontWeight = (isTeam || supColor) ? 'bold' : 'normal';

            var statusColor = r.trackStatusValue === 'on-track-exceptional' ? '#2e7d32' :
                r.trackStatusValue === 'on-track-successful' ? '#f57f17' : '#c62828';

            var scoreColor = function (s) {
                if (s === 3) return '#2e7d32';
                if (s === 2) return '#f57f17';
                return '#c62828';
            };

            var teamBorder = isTeam ? 'outline: 2px solid #2e7d32; outline-offset: -2px; ' : '';
            html += '<tr class="ranking-row" data-employee="' + _escapeHtml(r.name) + '" style="' + teamBorder + 'background: ' + rowBg + '; border-bottom: 1px solid #eee; font-weight: ' + fontWeight + ';">';

            // Row number
            html += '<td style="padding: 4px 3px; text-align: center; font-weight: bold;">' + (idx + 1) + '</td>';

            // Name (highlight team members, show supervisor color dot for rivals)
            html += '<td class="ranking-name-cell" style="padding: 4px 3px; white-space: nowrap;">';
            if (isTeam) {
                html += '<span style="color: #1565c0;">&#9733; </span>';
            } else if (supColor) {
                var _dotColor = _getSupervisorLightColor(r.name);
                html += '<span style="display:inline-block;width:8px;height:8px;border-radius:50%;background:' + _dotColor + ';margin-right:4px;vertical-align:middle;"></span>';
            }
            html += _escapeHtml(r.name) + '</td>';

            // Composite average rank
            html += '<td style="padding: 4px 3px; text-align: center; font-weight: bold;">' + r.compositeScore.toFixed(1) + '</td>';

            // 1-3 Score (rating average)
            html += '<td style="padding: 4px 3px; text-align: center; font-weight: bold; color: ' + statusColor + ';">' + r.ratingAverage.toFixed(2) + '</td>';

            // Status badge
            html += '<td style="padding: 4px 3px; text-align: center;"><span style="display: inline-block; padding: 1px 5px; border-radius: 8px; font-size: 0.72em; font-weight: bold; color: white; background: ' + statusColor + ';">';
            if (r.trackStatusValue === 'on-track-exceptional') html += 'Exceptional';
            else if (r.trackStatusValue === 'on-track-successful') html += 'Successful';
            else html += 'Off Track';
            html += '</span></td>';

            // Individual scores with values
            var metricPairs = [
                { score: r.scores.aht, value: r.values.aht, key: 'aht', rankKey: 'aht' },
                { score: r.scores.adherence, value: r.values.adherence, key: 'scheduleAdherence', rankKey: 'adherence' },
                { score: r.scores.sentiment, value: r.values.sentiment, key: 'overallSentiment', rankKey: 'sentiment' },
                { score: r.scores.associateOverall, value: r.values.associateOverall, key: 'cxRepOverall', rankKey: 'associateOverall' },
                { score: null, value: r.reliability, key: 'reliability', rankKey: 'reliability' }
            ];

            metricPairs.forEach(function (mp) {
                var display = mp.value !== null && mp.value !== undefined ? _formatMetricDisplay(mp.key, mp.value) : '--';
                var color = mp.score !== null ? scoreColor(mp.score) : '#333';
                var metricRank = r.metricRanks?.[mp.rankKey] || '?';
                var rankColor = metricRank <= 10 ? '#2e7d32' : metricRank <= Math.round(data.totalEmployees * 0.5) ? '#666' : '#c62828';
                var scoreBadge = mp.score !== null
                    ? '<span style="display: inline-block; width: 18px; height: 18px; line-height: 18px; border-radius: 50%; font-size: 0.7em; font-weight: bold; color: white; background: ' + scoreColor(mp.score) + '; text-align: center; margin-right: 3px;">' + mp.score + '</span>'
                    : '';
                // Show survey count next to Assoc Overall
                var surveyBadge = '';
                if (mp.rankKey === 'associateOverall' && r.surveyTotal > 0) {
                    surveyBadge = ' <span style="font-size: 0.68em; color: #888;">(' + r.surveyTotal + ')</span>';
                }
                html += '<td style="padding: 4px 3px; text-align: center; color: ' + color + '; white-space: nowrap;">' +
                    scoreBadge + display + surveyBadge + ' <span style="font-size: 0.72em; color: ' + rankColor + ';">#' + metricRank + '</span></td>';
            });

            html += '</tr>';
        });

        html += '</tbody></table>';
        html += '</div>';

        // Keep the header content, replace just the table area
        var existingHeader = wrapper.querySelector('h4');
        var existingDesc = wrapper.querySelector('p');
        wrapper.innerHTML = '';
        if (existingHeader) wrapper.appendChild(existingHeader);
        if (existingDesc) wrapper.appendChild(existingDesc);
        var tableDiv = document.createElement('div');
        tableDiv.innerHTML = html;
        wrapper.appendChild(tableDiv.firstChild);

        // Bind sort headers
        wrapper.querySelectorAll('.rank-sort-header').forEach(function(th) {
            th.addEventListener('click', function() {
                var newKey = th.dataset.sort;
                var col = SORT_COLUMNS.find(function(c) { return c.key === newKey; });
                var defaultDir = col && col.reverse ? 'desc' : 'asc';
                var newDir;
                if (_currentSort.key === newKey) {
                    newDir = _currentSort.dir === 'asc' ? 'desc' : 'asc';
                } else {
                    newDir = defaultDir;
                }
                _currentSort = { key: newKey, dir: newDir };
                renderRankingTable(newKey, newDir);
            });
        });
    }

    /* ── Module export ── */
    window.DevCoachModules = window.DevCoachModules || {};
    window.DevCoachModules.centerRanking = {
        renderCenterRanking: renderCenterRanking,
        buildCenterRankings: buildCenterRankings,
        buildRankingsForPeriod: buildRankingsForPeriod
    };

    window.renderCenterRanking = renderCenterRanking;
})();
