(function () {
    'use strict';

    function _escapeHtml(str) {
        var mod = window.DevCoachModules?.sharedUtils;
        if (mod?.escapeHtml) return mod.escapeHtml(str);
        return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }
    function _formatMetricDisplay(key, value) {
        return typeof window.formatMetricDisplay === 'function' ? window.formatMetricDisplay(key, value) : String(value);
    }
    function _getTeamMembersForWeek(weekKey) {
        return typeof window.getTeamMembersForWeek === 'function' ? window.getTeamMembersForWeek(weekKey) : [];
    }
    function _getLatestWeeklyKey() {
        return typeof window.getLatestWeeklyKey === 'function' ? window.getLatestWeeklyKey() : null;
    }
    function _getWeeklyData() {
        return typeof weeklyData !== 'undefined' ? weeklyData : {};
    }
    function _getYtdData() {
        return typeof ytdData !== 'undefined' ? ytdData : {};
    }

    /**
     * Score an employee using the On/Off track 5-metric system.
     * Returns { ratingAverage, trackLabel, scores, values, reliability } or null.
     */
    function scoreEmployee(emp, year) {
        var onOff = window.DevCoachModules?.onOffTracker;
        if (!onOff?.calculateYearEndOnOffMirror) return null;

        var result = onOff.calculateYearEndOnOffMirror(emp, year);
        if (!result || !result.isComplete) return null;

        return {
            ratingAverage: result.ratingAverage,
            trackLabel: result.trackLabel,
            trackStatusValue: result.trackStatusValue,
            scores: result.scores,
            values: result.values,
            reliability: parseFloat(emp.reliability) || 0,
            surveyTotal: parseInt(emp.surveyTotal, 10) || 0
        };
    }

    /**
     * Build rankings from the best available data source for a year.
     * Uses getLatestYearPeriodForEmployee logic via YTD data, or falls
     * back to the latest weekly upload with the most employees.
     */
    function buildCenterRankings() {
        var currentYear = new Date().getFullYear();
        var wData = _getWeeklyData();
        var yData = _getYtdData();

        // Find the best data source for rankings.
        // Prefer the newest real (non-auto-generated) YTD upload first,
        // then fall back to the period with the most employees.
        var bestPeriod = null;
        var bestCount = 0;
        var bestSource = '';
        var bestKey = '';
        var foundRealYtd = false;
        var bestRealYtdDate = 0;

        // Check YTD data first — prefer the newest real YTD upload
        Object.entries(yData).forEach(function (entry) {
            var key = entry[0];
            var period = entry[1];
            var meta = period?.metadata || {};
            var endStr = meta.endDate || (key.includes('|') ? key.split('|')[1] : '');
            var endYear = parseInt(String(endStr).split('-')[0], 10);
            if (endYear !== currentYear) return;
            var count = (period.employees || []).length;
            var isRealYtd = !meta.autoGeneratedYtd && meta.periodType === 'ytd';
            var endDate = endStr ? new Date(endStr) : null;
            var endTime = endDate && !isNaN(endDate) ? endDate.getTime() : 0;

            if (isRealYtd) {
                // Among real YTDs, always prefer the newest by end date
                if (!foundRealYtd || endTime > bestRealYtdDate) {
                    foundRealYtd = true;
                    bestRealYtdDate = endTime;
                    bestPeriod = period;
                    bestCount = count;
                    bestSource = meta.label || 'YTD upload';
                    bestKey = key;
                }
                return;
            }

            // Only consider non-real-YTD if we haven't found a real one
            if (!foundRealYtd && count > bestCount) {
                bestPeriod = period;
                bestCount = count;
                bestSource = meta.label || 'YTD upload';
                bestKey = key;
            }
        });

        // Only check weekly data if no real YTD was found
        if (!foundRealYtd) {
            Object.entries(wData).forEach(function (entry) {
                var key = entry[0];
                var period = entry[1];
                var meta = period?.metadata || {};
                var endStr = meta.endDate || (key.includes('|') ? key.split('|')[1] : '');
                var endYear = parseInt(String(endStr).split('-')[0], 10);
                if (endYear !== currentYear) return;
                var count = (period.employees || []).length;
                if (count > bestCount) {
                    bestPeriod = period;
                    bestCount = count;
                    bestSource = meta.label || key;
                    bestKey = key;
                }
            });
        }

        if (!bestPeriod || bestCount === 0) return null;

        // Score every employee
        var rankings = [];
        (bestPeriod.employees || []).forEach(function (emp) {
            if (!emp || !emp.name) return;
            var score = scoreEmployee(emp, currentYear);
            if (!score) return;

            rankings.push({
                name: emp.name,
                ratingAverage: score.ratingAverage,
                trackLabel: score.trackLabel,
                trackStatusValue: score.trackStatusValue,
                scores: score.scores,
                values: score.values,
                reliability: score.reliability,
                surveyTotal: score.surveyTotal
            });
        });

        // Rank by each individual metric (lower rank = better)
        var metricRankKeys = [
            { key: 'aht', field: 'values.aht', reverse: true },         // lower AHT = better
            { key: 'adherence', field: 'values.adherence', reverse: false }, // higher = better
            { key: 'sentiment', field: 'values.sentiment', reverse: false }, // higher = better
            { key: 'associateOverall', field: 'values.associateOverall', reverse: false }, // higher = better
            { key: 'reliability', field: 'reliability', reverse: true }  // lower hours = better
        ];

        metricRankKeys.forEach(function (mk) {
            // Sort a copy to determine ranks for this metric
            var sorted = rankings.slice().sort(function (a, b) {
                var aVal = mk.field.includes('.') ? a.values[mk.field.split('.')[1]] : a[mk.field];
                var bVal = mk.field.includes('.') ? b.values[mk.field.split('.')[1]] : b[mk.field];
                aVal = aVal !== null && aVal !== undefined ? aVal : (mk.reverse ? Infinity : -Infinity);
                bVal = bVal !== null && bVal !== undefined ? bVal : (mk.reverse ? Infinity : -Infinity);
                return mk.reverse ? (aVal - bVal) : (bVal - aVal);
            });

            // Assign metric rank to each employee
            sorted.forEach(function (emp, idx) {
                if (!emp.metricRanks) emp.metricRanks = {};
                emp.metricRanks[mk.key] = idx + 1;
            });
        });

        // Composite rank = average of all 5 metric ranks (lower = better)
        rankings.forEach(function (r) {
            var ranks = r.metricRanks || {};
            var sum = (ranks.aht || 0) + (ranks.adherence || 0) + (ranks.sentiment || 0) +
                (ranks.associateOverall || 0) + (ranks.reliability || 0);
            r.compositeScore = sum / 5;
        });

        // Sort by composite score (lower = better), reliability rank as tiebreaker
        rankings.sort(function (a, b) {
            if (a.compositeScore !== b.compositeScore) return a.compositeScore - b.compositeScore;
            return (a.metricRanks?.reliability || 0) - (b.metricRanks?.reliability || 0);
        });

        // Assign overall rank
        rankings.forEach(function (r, i) { r.rank = i + 1; });

        // Identify team members — check weekly keys first, fall back to YTD/any key
        var latestKey = _getLatestWeeklyKey();
        if (!latestKey) {
            // Try team filter module's resolution which checks ytdData too
            var teamFilter = window.DevCoachModules?.teamFilter;
            if (teamFilter?.getTeamSelectionContext) {
                latestKey = teamFilter.getTeamSelectionContext().weekKey || '';
            }
        }
        var teamMembers = latestKey ? _getTeamMembersForWeek(latestKey) : [];
        var teamSet = new Set(teamMembers);

        return {
            rankings: rankings,
            totalEmployees: rankings.length,
            source: bestSource,
            periodKey: bestKey,
            teamMembers: teamSet
        };
    }

    /**
     * Render the center ranking view
     */
    function renderCenterRanking() {
        var container = document.getElementById('centerRankingContent');
        if (!container) return;

        var data = buildCenterRankings();
        if (!data || data.rankings.length === 0) {
            container.innerHTML = '<p style="color: #94a3b8; text-align: center; padding: 40px;">No ranking data available. Upload a full center data set (30+ employees) to see rankings.</p>';
            return;
        }

        var html = '';

        // Header
        html += '<div style="margin-bottom: 20px; padding: 15px; background: #e3f2fd; border-radius: 8px; border-left: 4px solid #1565c0;">';
        html += '<strong>Center Rankings</strong> &mdash; ' + data.totalEmployees + ' employees scored';
        html += '<br><span style="color: #666; font-size: 0.85em;">Source: ' + _escapeHtml(data.source) + ' | Ranked by On/Off Track score (reliability as tiebreaker)</span>';
        html += '</div>';

        // Team summary
        var teamRanks = data.rankings.filter(function (r) { return data.teamMembers.has(r.name); });
        if (teamRanks.length > 0) {
            html += '<div style="margin-bottom: 20px; padding: 15px; background: #fff; border-radius: 8px; border: 1px solid #ddd; box-shadow: 0 1px 3px rgba(0,0,0,0.08);">';
            html += '<h4 style="margin-top: 0; color: #1a1a2e;">Your Team</h4>';
            html += '<div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 10px;">';

            teamRanks.forEach(function (r) {
                var statusColor = r.trackStatusValue === 'on-track-exceptional' ? '#2e7d32' :
                    r.trackStatusValue === 'on-track-successful' ? '#f57f17' : '#c62828';
                var statusBg = r.trackStatusValue === 'on-track-exceptional' ? '#e8f5e9' :
                    r.trackStatusValue === 'on-track-successful' ? '#fff8e1' : '#fbe9e7';
                var percentile = Math.round((1 - (r.rank - 1) / data.totalEmployees) * 100);

                html += '<div style="padding: 12px 16px; background: ' + statusBg + '; border-radius: 8px; border-left: 4px solid ' + statusColor + ';">';
                html += '<div class="ranking-card-name" data-employee="' + _escapeHtml(r.name) + '" style="font-weight: bold; font-size: 1.05em; cursor: pointer; text-decoration: underline; text-decoration-color: rgba(0,0,0,0.2);">' + _escapeHtml(r.name) + '</div>';
                html += '<div style="margin-top: 4px;">';
                html += '<span style="font-size: 1.3em; font-weight: bold; color: ' + statusColor + ';">#' + r.rank + '</span>';
                html += ' <span style="color: #666; font-size: 0.85em;">of ' + data.totalEmployees + ' (top ' + percentile + '%)</span>';
                html += '</div>';
                html += '<div style="margin-top: 4px; font-size: 0.85em; color: #555;">' + _escapeHtml(r.trackLabel) + ' &mdash; Avg rank: ' + r.compositeScore.toFixed(1) + '</div>';
                html += '<div style="font-size: 0.8em; color: #888;">Reliability: ' + _formatMetricDisplay('reliability', r.reliability) + ' (#' + (r.metricRanks?.reliability || '?') + ')</div>';
                html += '</div>';
            });

            html += '</div></div>';
        }

        // Store data for re-sorting
        _lastRankingData = data;
        _currentSort = { key: 'composite', dir: 'asc' };

        // Full ranking table
        html += '<div id="centerRankingTableWrapper" style="padding: 20px; background: #fff; border-radius: 8px; border: 1px solid #ddd; box-shadow: 0 1px 3px rgba(0,0,0,0.08);">';
        html += '<h4 style="margin-top: 0; color: #1a1a2e;">Full Center Rankings</h4>';
        html += '<p style="margin: 0 0 12px 0; color: #666; font-size: 0.85em;">Click any column header to sort. Each metric shows value and rank (#).</p>';
        html += '</div>';

        container.innerHTML = html;
        renderRankingTable('composite', 'asc');

        // Bind team card name clicks to scroll to that employee's row
        container.querySelectorAll('.ranking-card-name').forEach(function (el) {
            el.addEventListener('click', function () {
                var name = el.dataset.employee;
                var row = document.querySelector('#centerRankingTableWrapper tr[data-employee="' + CSS.escape(name) + '"]');
                if (row) {
                    row.scrollIntoView({ behavior: 'smooth', block: 'center' });
                    row.style.transition = 'background 0.3s';
                    row.style.background = '#bbdefb';
                    setTimeout(function () { row.style.background = ''; }, 2000);
                }
            });
        });
    }

    var _lastRankingData = null;
    var _currentSort = { key: 'composite', dir: 'asc' };

    var SORT_COLUMNS = [
        { key: 'composite', label: 'Avg Rank', getValue: function(r) { return r.compositeScore; }, reverse: false },
        { key: 'score', label: 'Score', getValue: function(r) { return r.ratingAverage; }, reverse: true },
        { key: 'aht', label: 'AHT', getValue: function(r) { return r.values.aht; }, reverse: false },
        { key: 'adherence', label: 'Adherence', getValue: function(r) { return r.values.adherence; }, reverse: true },
        { key: 'sentiment', label: 'Sentiment', getValue: function(r) { return r.values.sentiment; }, reverse: true },
        { key: 'associateOverall', label: 'Assoc Overall', getValue: function(r) { return r.values.associateOverall; }, reverse: true },
        { key: 'reliability', label: 'Reliability', getValue: function(r) { return r.reliability; }, reverse: false }
    ];

    function renderRankingTable(sortKey, sortDir) {
        var wrapper = document.getElementById('centerRankingTableWrapper');
        if (!wrapper || !_lastRankingData) return;
        var data = _lastRankingData;

        // Sort rankings
        var col = SORT_COLUMNS.find(function(c) { return c.key === sortKey; });
        var sorted = data.rankings.slice().sort(function(a, b) {
            var aVal = col ? col.getValue(a) : a.compositeScore;
            var bVal = col ? col.getValue(b) : b.compositeScore;
            aVal = aVal !== null && aVal !== undefined ? aVal : (sortDir === 'asc' ? Infinity : -Infinity);
            bVal = bVal !== null && bVal !== undefined ? bVal : (sortDir === 'asc' ? Infinity : -Infinity);
            return sortDir === 'asc' ? (aVal - bVal) : (bVal - aVal);
        });

        var thStyle = 'padding: 6px 3px; text-align: center; border-bottom: 2px solid #ddd; cursor: pointer; user-select: none; font-size: 0.85em;';
        var arrow = function(key) {
            if (key !== sortKey) return ' <span style="opacity: 0.3;">&#8597;</span>';
            return sortDir === 'asc' ? ' <span style="color: #1565c0;">&#9650;</span>' : ' <span style="color: #1565c0;">&#9660;</span>';
        };

        var html = '<div>';
        html += '<table style="width: 100%; border-collapse: collapse; font-size: 0.82em; table-layout: auto;">';
        html += '<thead><tr style="background: #f5f5f5;">';
        html += '<th style="' + thStyle + ' width: 30px;">#</th>';
        html += '<th style="' + thStyle + ' text-align: left;">Name</th>';
        html += '<th class="rank-sort-header" data-sort="composite" style="' + thStyle + '">Avg' + arrow('composite') + '</th>';
        html += '<th class="rank-sort-header" data-sort="score" style="' + thStyle + '">Score' + arrow('score') + '</th>';
        html += '<th style="' + thStyle + '">Status</th>';
        html += '<th class="rank-sort-header" data-sort="aht" style="' + thStyle + '">AHT' + arrow('aht') + '</th>';
        html += '<th class="rank-sort-header" data-sort="adherence" style="' + thStyle + '">Adh' + arrow('adherence') + '</th>';
        html += '<th class="rank-sort-header" data-sort="sentiment" style="' + thStyle + '">Sent' + arrow('sentiment') + '</th>';
        html += '<th class="rank-sort-header" data-sort="associateOverall" style="' + thStyle + '">Assoc' + arrow('associateOverall') + '</th>';
        html += '<th class="rank-sort-header" data-sort="reliability" style="' + thStyle + '">Rel' + arrow('reliability') + '</th>';
        html += '</tr></thead><tbody>';

        sorted.forEach(function (r, idx) {
            var isTeam = data.teamMembers.has(r.name);
            var rowBg = isTeam ? '#e8eaf6' : (r.rank % 2 === 0 ? '#fafafa' : '#fff');
            var fontWeight = isTeam ? 'bold' : 'normal';

            var statusColor = r.trackStatusValue === 'on-track-exceptional' ? '#2e7d32' :
                r.trackStatusValue === 'on-track-successful' ? '#f57f17' : '#c62828';

            var scoreColor = function (s) {
                if (s === 3) return '#2e7d32';
                if (s === 2) return '#f57f17';
                return '#c62828';
            };

            html += '<tr data-employee="' + _escapeHtml(r.name) + '" style="background: ' + rowBg + '; border-bottom: 1px solid #eee; font-weight: ' + fontWeight + ';">';

            // Row number
            html += '<td style="padding: 4px 3px; text-align: center; font-weight: bold;">' + (idx + 1) + '</td>';

            // Name (highlight team members)
            html += '<td style="padding: 4px 3px; white-space: nowrap;">';
            if (isTeam) html += '<span style="color: #1565c0;">&#9733; </span>';
            html += _escapeHtml(r.name) + '</td>';

            // Composite average rank
            html += '<td style="padding: 4px 3px; text-align: center; font-weight: bold;">' + r.compositeScore.toFixed(1) + '</td>';

            // 1-3 Score (rating average)
            html += '<td style="padding: 4px 3px; text-align: center; font-weight: bold; color: ' + statusColor + ';">' + r.ratingAverage.toFixed(2) + '</td>';

            // Status badge
            html += '<td style="padding: 4px 3px; text-align: center;"><span style="display: inline-block; padding: 1px 5px; border-radius: 8px; font-size: 0.72em; font-weight: bold; color: white; background: ' + statusColor + ';">';
            if (r.trackStatusValue === 'on-track-exceptional') html += 'Exceptional';
            else if (r.trackStatusValue === 'on-track-successful') html += 'Successful';
            else html += 'Off Track';
            html += '</span></td>';

            // Individual scores with values
            var metricPairs = [
                { score: r.scores.aht, value: r.values.aht, key: 'aht', rankKey: 'aht' },
                { score: r.scores.adherence, value: r.values.adherence, key: 'scheduleAdherence', rankKey: 'adherence' },
                { score: r.scores.sentiment, value: r.values.sentiment, key: 'overallSentiment', rankKey: 'sentiment' },
                { score: r.scores.associateOverall, value: r.values.associateOverall, key: 'cxRepOverall', rankKey: 'associateOverall' },
                { score: null, value: r.reliability, key: 'reliability', rankKey: 'reliability' }
            ];

            metricPairs.forEach(function (mp) {
                var display = mp.value !== null && mp.value !== undefined ? _formatMetricDisplay(mp.key, mp.value) : '--';
                var color = mp.score !== null ? scoreColor(mp.score) : '#333';
                var metricRank = r.metricRanks?.[mp.rankKey] || '?';
                var rankColor = metricRank <= 10 ? '#2e7d32' : metricRank <= Math.round(data.totalEmployees * 0.5) ? '#666' : '#c62828';
                var scoreBadge = mp.score !== null
                    ? '<span style="display: inline-block; width: 18px; height: 18px; line-height: 18px; border-radius: 50%; font-size: 0.7em; font-weight: bold; color: white; background: ' + scoreColor(mp.score) + '; text-align: center; margin-right: 3px;">' + mp.score + '</span>'
                    : '';
                // Show survey count next to Assoc Overall
                var surveyBadge = '';
                if (mp.rankKey === 'associateOverall' && r.surveyTotal > 0) {
                    surveyBadge = ' <span style="font-size: 0.68em; color: #888;">(' + r.surveyTotal + ')</span>';
                }
                html += '<td style="padding: 4px 3px; text-align: center; color: ' + color + '; white-space: nowrap;">' +
                    scoreBadge + display + surveyBadge + ' <span style="font-size: 0.72em; color: ' + rankColor + ';">#' + metricRank + '</span></td>';
            });

            html += '</tr>';
        });

        html += '</tbody></table>';
        html += '</div>';

        // Keep the header content, replace just the table area
        var existingHeader = wrapper.querySelector('h4');
        var existingDesc = wrapper.querySelector('p');
        wrapper.innerHTML = '';
        if (existingHeader) wrapper.appendChild(existingHeader);
        if (existingDesc) wrapper.appendChild(existingDesc);
        var tableDiv = document.createElement('div');
        tableDiv.innerHTML = html;
        wrapper.appendChild(tableDiv.firstChild);

        // Bind sort headers
        wrapper.querySelectorAll('.rank-sort-header').forEach(function(th) {
            th.addEventListener('click', function() {
                var newKey = th.dataset.sort;
                var col = SORT_COLUMNS.find(function(c) { return c.key === newKey; });
                var defaultDir = col && col.reverse ? 'desc' : 'asc';
                var newDir;
                if (_currentSort.key === newKey) {
                    newDir = _currentSort.dir === 'asc' ? 'desc' : 'asc';
                } else {
                    newDir = defaultDir;
                }
                _currentSort = { key: newKey, dir: newDir };
                renderRankingTable(newKey, newDir);
            });
        });
    }

    /* ── Module export ── */
    window.DevCoachModules = window.DevCoachModules || {};
    window.DevCoachModules.centerRanking = {
        renderCenterRanking: renderCenterRanking,
        buildCenterRankings: buildCenterRankings
    };

    window.renderCenterRanking = renderCenterRanking;
})();
