(function () {
    'use strict';

    var STORAGE_PREFIX = (window.DevCoachConstants && window.DevCoachConstants.STORAGE_PREFIX) || 'devCoachingTool_';

    // Supervisor color palette for row highlighting
    // bg = light-mode row tint, dark = dark-mode row tint, dot = vivid accent for
    // the name-cell indicator (needs to read clearly on BOTH row backgrounds).
    var SUPERVISOR_COLORS = {
        'Scott':           { bg: '#e3f2fd', dark: '#0d2137', dot: '#1e88e5' },
        'Miranda':         { bg: '#fce4ec', dark: '#2a1015', dot: '#ec407a' },
        'Kathy':           { bg: '#f3e5f5', dark: '#1f0f24', dot: '#ab47bc' },
        'Angie':           { bg: '#fff3e0', dark: '#2a1d08', dot: '#fb8c00' },
        'Sarah':           { bg: '#e8f5e9', dark: '#0d2010', dot: '#43a047' },
        'Schnelle':        { bg: '#e0f7fa', dark: '#0a1f22', dot: '#00acc1' },
        'Nicole':          { bg: '#fff9c4', dark: '#2a2508', dot: '#fdd835' },
        'Angela Allison':  { bg: '#f1f8e9', dark: '#1a2410', dot: '#7cb342' }
    };

    function _getSupervisorColor(empName) {
        try {
            var sups = JSON.parse(localStorage.getItem(STORAGE_PREFIX + 'employeeSupervisors') || '{}');
            var sup = sups[empName];
            if (sup && SUPERVISOR_COLORS[sup]) {
                var isDark = document.documentElement.getAttribute('data-theme') === 'dark';
                return isDark ? SUPERVISOR_COLORS[sup].dark : SUPERVISOR_COLORS[sup].bg;
            }
        } catch (_e) { /* localStorage parse failure — fall through to default */ }
        return null;
    }

    function _getSupervisorDotColor(empName) {
        try {
            var sups = JSON.parse(localStorage.getItem(STORAGE_PREFIX + 'employeeSupervisors') || '{}');
            var sup = sups[empName];
            if (sup && SUPERVISOR_COLORS[sup]) return SUPERVISOR_COLORS[sup].dot;
        } catch (_e) { /* localStorage parse failure — fall through to default */ }
        return '#90a4ae';
    }

    function _escapeHtml(str) {
        var mod = window.DevCoachModules?.sharedUtils;
        if (mod?.escapeHtml) return mod.escapeHtml(str);
        return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
    }
    function _formatMetricDisplay(key, value) {
        return typeof window.formatMetricDisplay === 'function' ? window.formatMetricDisplay(key, value) : String(value);
    }
    function _getTeamMembersForWeek(weekKey) {
        return typeof window.getTeamMembersForWeek === 'function' ? window.getTeamMembersForWeek(weekKey) : [];
    }
    function _getLatestWeeklyKey() {
        return typeof window.getLatestWeeklyKey === 'function' ? window.getLatestWeeklyKey() : null;
    }
    function _getWeeklyData() {
        return typeof weeklyData !== 'undefined' ? weeklyData : {};
    }
    function _getYtdData() {
        return typeof ytdData !== 'undefined' ? ytdData : {};
    }

    // ── Period selector ──
    var _selectedRankingPeriodKey = null;
    var _rankingPeriodInitialized = false;

    function _getAvailableRankingPeriods() {
        var periods = [];
        var wData = _getWeeklyData();
        var yData = _getYtdData();

        Object.keys(wData).forEach(function(key) {
            var data = wData[key];
            var meta = data?.metadata || {};
            var count = (data?.employees || []).length;
            if (count < 2) return;
            var pType = meta.periodType || 'week';
            var endStr = meta.endDate || (key.includes('|') ? key.split('|')[1] : '');
            var label = meta.label || _fmtPeriodLabel(key, pType);
            periods.push({ key: key, label: label, type: pType, source: 'weekly', count: count, endDate: endStr });
        });

        Object.keys(yData).forEach(function(key) {
            var data = yData[key];
            var meta = data?.metadata || {};
            if (meta.autoGeneratedYtd) return;
            var count = (data?.employees || []).length;
            if (count < 2) return;
            var pType = meta.periodType || 'ytd';
            var endStr = meta.endDate || (key.includes('|') ? key.split('|')[1] : '');
            var label = meta.label || _fmtPeriodLabel(key, pType);
            periods.push({ key: key, label: label, type: pType, source: 'ytd', count: count, endDate: endStr });
        });

        periods.sort(function(a, b) {
            var aDate = a.endDate || a.key.split('|')[1] || '';
            var bDate = b.endDate || b.key.split('|')[1] || '';
            return bDate.localeCompare(aDate);
        });
        return periods;
    }

    function _fmtPeriodLabel(key, type) {
        var parts = key.split('|');
        var endDate = parts[1] || parts[0] || '';
        var prefix;
        if (type === 'ytd') prefix = 'YTD';
        else if (type === 'month') prefix = 'Monthly';
        else if (type === 'quarter') prefix = 'Quarterly';
        else if (type === 'daily') prefix = 'Daily';
        else if (type === 'week-in-progress') prefix = 'Week in progress';
        else prefix = 'Weekly';
        return prefix + ' ending ' + endDate;
    }

    function _renderRankingPeriodSelector(selectedValue) {
        var periods = _getAvailableRankingPeriods();
        var typeOrder = ['ytd', 'quarter', 'month', 'week', 'week-in-progress', 'daily'];
        var typeLabels = { ytd: 'YTD', quarter: 'Quarterly', month: 'Monthly', week: 'Weekly', 'week-in-progress': 'Week to Date', daily: 'Daily' };
        var grouped = {};
        periods.forEach(function(p) {
            var t = p.type || 'week';
            if (!grouped[t]) grouped[t] = [];
            grouped[t].push(p);
        });

        var html = '<div style="margin-bottom: 16px; display: flex; align-items: center; gap: 12px; flex-wrap: wrap;">';
        html += '<label style="font-weight: 600; color: #555; font-size: 0.9em;">Period:</label>';
        html += '<select id="rankingPeriodSelect" style="padding: 6px 10px; border: 1px solid #ccc; border-radius: 6px; font-size: 0.9em; min-width: 260px;">';
        html += '<option value="">Auto (Best Available)</option>';

        typeOrder.forEach(function(t) {
            if (!grouped[t] || grouped[t].length === 0) return;
            html += '<optgroup label="' + (typeLabels[t] || t) + '">';
            grouped[t].forEach(function(p) {
                var val = p.key;
                var sel = (val === selectedValue) ? ' selected' : '';
                html += '<option value="' + _escapeHtml(val) + '"' + sel + '>' + _escapeHtml(p.label) + ' (' + p.count + ' employees)</option>';
            });
            html += '</optgroup>';
        });

        html += '</select></div>';
        return html;
    }

    function _onRankingPeriodChange() {
        var select = document.getElementById('rankingPeriodSelect');
        if (!select) return;
        _selectedRankingPeriodKey = select.value || null;
        renderCenterRanking();
    }

    /**
     * Score an employee using the 5-KPI system (3/2/1 per KPI).
     * Returns { scores, values, kpisMet, scoreSum, kpiScore, trackLabel, trackStatusValue, ... } or null.
     */
    function scoreEmployee(emp, year) {
        var onOff = window.DevCoachModules?.onOffTracker;
        if (!onOff?.calculateYearEndOnOffMirror) return null;

        var result = onOff.calculateYearEndOnOffMirror(emp, year);
        if (!result) return null;

        var scores = result.scores || {};
        var SCORE_KEYS = ['aht', 'adherence', 'sentiment', 'associateOverall', 'reliability'];

        // Require at least one valid score
        var validScores = SCORE_KEYS.map(function (k) { return scores[k]; }).filter(function (s) { return s !== null && s !== undefined; });
        if (validScores.length === 0) return null;
        var measuredCount = validScores.length;

        // KPIs Met: count of KPIs scoring 2 (Meets) or 3 (Exceeds)
        var kpisMet = 0;
        SCORE_KEYS.forEach(function (k) {
            if (scores[k] !== null && scores[k] !== undefined && scores[k] >= 2) kpisMet++;
        });

        // Score Sum: total of MEASURED KPI scores only. Blank KPIs are not
        // back-filled — a missing slot must neither pad nor drag the total.
        var scoreSum = validScores.reduce(function (a, b) { return a + b; }, 0);

        // KPI Score = average score across the KPIs the agent actually has
        // data for (1.0-3.0 scale).
        var kpiScore = scoreSum / measuredCount;

        // Track band from the per-KPI average, so the cutoffs scale to however
        // many KPIs were measured. 2.8 = old 14/15 Exceptional, 1.8 = old 9/15
        // Successful. An agent with 3 blank KPIs is judged on the 2 real ones.
        var trackLabel, trackStatusValue;
        if (kpiScore >= 2.8) {
            trackLabel = 'Exceptional'; trackStatusValue = 'on-track-exceptional';
        } else if (kpiScore >= 1.8) {
            trackLabel = 'Successful'; trackStatusValue = 'on-track-successful';
        } else {
            trackLabel = 'Off Track'; trackStatusValue = 'off-track';
        }

        // Reliability: keep a genuinely missing value as null, not 0 — 0 is a
        // legitimate perfect score, so coercing blanks to 0 would crown them.
        var reliabilityVal = parseFloat(emp.reliability);
        if (isNaN(reliabilityVal)) reliabilityVal = null;

        return {
            kpisMet: kpisMet,
            scoreSum: scoreSum,
            measuredCount: measuredCount,
            kpiScore: kpiScore,
            ratingAverage: kpiScore,
            trackLabel: trackLabel,
            trackStatusValue: trackStatusValue,
            scores: scores,
            values: result.values || {},
            reliability: reliabilityVal,
            surveyTotal: parseInt(emp.surveyTotal, 10) || 0,
            totalCalls: parseInt(emp.totalCalls, 10) || 0
        };
    }

    /**
     * Build rankings from the best available data source for a year.
     * Uses getLatestYearPeriodForEmployee logic via YTD data, or falls
     * back to the latest weekly upload with the most employees.
     */
    function buildCenterRankings() {
        var currentYear = new Date().getFullYear();
        var wData = _getWeeklyData();
        var yData = _getYtdData();

        // Find the single most recent upload with 30+ employees.
        // Priority: newest real YTD > newest non-YTD upload.
        // No merging. One period. That's it.
        var bestYtd = null;
        var bestYtdTime = 0;
        var bestYtdKey = '';
        var bestYtdSource = '';

        Object.entries(yData).forEach(function (entry) {
            var meta = entry[1]?.metadata || {};
            if (meta.autoGeneratedYtd) return;
            var endStr = meta.endDate || (entry[0].includes('|') ? entry[0].split('|')[1] : '');
            var endYear = parseInt(String(endStr).split('-')[0], 10);
            if (endYear !== currentYear) return;
            var count = (entry[1].employees || []).length;
            if (count < 30) return;
            var uploadedAt = meta.uploadedAt ? new Date(meta.uploadedAt).getTime() : 0;
            if (uploadedAt > bestYtdTime) {
                bestYtd = entry[1];
                bestYtdTime = uploadedAt;
                bestYtdKey = entry[0];
                bestYtdSource = meta.label || 'YTD upload';
            }
        });

        // Fall back to newest weekly/custom upload with 30+ employees
        var bestWeekly = null;
        var bestWeeklyTime = 0;
        var bestWeeklyKey = '';
        var bestWeeklySource = '';

        Object.entries(wData).forEach(function (entry) {
            var meta = entry[1]?.metadata || {};
            var endStr = meta.endDate || (entry[0].includes('|') ? entry[0].split('|')[1] : '');
            var endYear = parseInt(String(endStr).split('-')[0], 10);
            if (endYear !== currentYear) return;
            var count = (entry[1].employees || []).length;
            if (count < 30) return;
            var uploadedAt = meta.uploadedAt ? new Date(meta.uploadedAt).getTime() : 0;
            if (uploadedAt > bestWeeklyTime) {
                bestWeekly = entry[1];
                bestWeeklyTime = uploadedAt;
                bestWeeklyKey = entry[0];
                bestWeeklySource = meta.label || entry[0];
            }
        });

        // Use the most recently uploaded source. Real YTD wins ties.
        var bestPeriod, bestKey, bestSource;
        if (bestYtd && (!bestWeekly || bestYtdTime >= bestWeeklyTime)) {
            bestPeriod = bestYtd;
            bestKey = bestYtdKey;
            bestSource = bestYtdSource;
        } else if (bestWeekly) {
            bestPeriod = bestWeekly;
            bestKey = bestWeeklyKey;
            bestSource = bestWeeklySource;
        } else {
            return null;
        }

        // Use this period's employees directly. No merging. No overlaying.
        var baseEmployees = {};
        (bestPeriod.employees || []).forEach(function (emp) {
            if (emp && emp.name) baseEmployees[emp.name] = emp;
        });

        var mergedEmployees = Object.values(baseEmployees);

        var rankings = _scoreAndRank(mergedEmployees, currentYear);

        // Identify team members — check weekly keys first, fall back to YTD/any key
        var latestKey = _getLatestWeeklyKey();
        if (!latestKey) {
            var teamFilter = window.DevCoachModules?.teamFilter;
            if (teamFilter?.getTeamSelectionContext) {
                latestKey = teamFilter.getTeamSelectionContext().weekKey || '';
            }
        }
        var teamMembers = latestKey ? _getTeamMembersForWeek(latestKey) : [];
        var teamSet = new Set(teamMembers);

        return {
            rankings: rankings,
            totalEmployees: rankings.length,
            source: bestSource,
            periodKey: bestKey,
            teamMembers: teamSet
        };
    }

    /**
     * Shared scoring + ranking logic. Takes an array of employee objects,
     * scores each one, assigns per-metric ranks, then sorts by 4-level
     * priority: KPIs Met → Score Sum → KPI Rank Total → Tiebreaker.
     * Returns the sorted rankings array.
     */
    function _scoreAndRank(employees, year) {
        var METRIC_KEYS = ['aht', 'adherence', 'sentiment', 'associateOverall', 'reliability'];

        // Dedupe by name (last row wins) so a doubled upload row can't be
        // scored twice and skew every other employee's metric ranks.
        var _byName = {};
        (employees || []).forEach(function (emp) {
            if (emp && emp.name) _byName[emp.name] = emp;
        });

        var rankings = [];
        Object.values(_byName).forEach(function (emp) {
            var score = scoreEmployee(emp, year);
            if (!score) return;

            rankings.push({
                name: emp.name,
                kpisMet: score.kpisMet,
                scoreSum: score.scoreSum,
                measuredCount: score.measuredCount,
                kpiScore: score.kpiScore,
                ratingAverage: score.ratingAverage,
                trackLabel: score.trackLabel,
                trackStatusValue: score.trackStatusValue,
                scores: score.scores,
                values: score.values,
                reliability: score.reliability,
                surveyTotal: score.surveyTotal,
                totalCalls: score.totalCalls
            });
        });

        // ── Step 5: Individual KPI Ranks ──
        var metricRankKeys = [
            { key: 'aht', field: 'values.aht', reverse: true },       // lower is better
            { key: 'adherence', field: 'values.adherence', reverse: false },  // higher is better
            { key: 'sentiment', field: 'values.sentiment', reverse: false },
            { key: 'associateOverall', field: 'values.associateOverall', reverse: false },
            { key: 'reliability', field: 'reliability', reverse: true }  // lower is better
        ];

        var _isNullVal = function (v) {
            return v === null || v === undefined || (typeof v === 'number' && isNaN(v));
        };

        metricRankKeys.forEach(function (mk) {
            var getVal = function (e) {
                return mk.field.includes('.') ? e.values[mk.field.split('.')[1]] : e[mk.field];
            };
            var sorted = rankings.slice().sort(function (a, b) {
                var aVal = getVal(a), bVal = getVal(b);
                var aNull = _isNullVal(aVal), bNull = _isNullVal(bVal);
                if (aNull && bNull) return 0;
                if (aNull) return 1;   // missing values sink to the end
                if (bNull) return -1;
                return mk.reverse ? (aVal - bVal) : (bVal - aVal);
            });
            var lastRank = 0, lastVal;
            sorted.forEach(function (emp, idx) {
                if (!emp.metricRanks) emp.metricRanks = {};
                var val = getVal(emp);
                // No data for this metric — leave the rank null. It displays as
                // '?' and the KPI Rank Total step below substitutes the worst
                // rank, so a blank metric can never out-rank a measured one.
                if (_isNullVal(val)) {
                    emp.metricRanks[mk.key] = null;
                    return;
                }
                // Standard 1-2-2-4 ranking, with an epsilon tie test so decimal
                // values that display identically aren't split into two ranks.
                if (idx === 0 || _isNullVal(lastVal) || Math.abs(val - lastVal) >= 1e-9) {
                    emp.metricRanks[mk.key] = idx + 1;
                } else {
                    emp.metricRanks[mk.key] = lastRank;
                }
                lastRank = emp.metricRanks[mk.key];
                lastVal = val;
            });
        });

        // ── KPI Rank Total = sum of all 5 individual ranks (lower = better) ──
        var worstRank = rankings.length + 1;
        rankings.forEach(function (r) {
            var ranks = r.metricRanks || {};
            var total = 0;
            METRIC_KEYS.forEach(function (k) {
                total += (ranks[k] && ranks[k] > 0) ? ranks[k] : worstRank;
            });
            r.kpiRankTotal = total;
        });

        // ── Step 6: Tiebreaker (min-max normalized average) ──
        var metricMinMax = {};
        METRIC_KEYS.forEach(function (mk) {
            var vals = rankings.map(function (r) {
                var v = mk === 'reliability' ? r.reliability : r.values[mk];
                return (v !== null && v !== undefined && !isNaN(v)) ? v : null;
            }).filter(function (v) { return v !== null; });
            metricMinMax[mk] = {
                min: vals.length ? Math.min.apply(null, vals) : 0,
                max: vals.length ? Math.max.apply(null, vals) : 0
            };
        });

        rankings.forEach(function (r) {
            var normalized = [];
            var _norm = function (val, key, invert) {
                if (val === null || val === undefined || isNaN(val)) return;
                var mm = metricMinMax[key];
                var range = mm.max - mm.min;
                if (range === 0) { normalized.push(0.5); return; }
                normalized.push(invert ? (mm.max - val) / range : (val - mm.min) / range);
            };
            _norm(r.values.adherence, 'adherence', false);
            _norm(r.reliability, 'reliability', true);
            _norm(r.values.aht, 'aht', true);
            _norm(r.values.associateOverall, 'associateOverall', false);
            _norm(r.values.sentiment, 'sentiment', false);

            r.tiebreaker = normalized.length > 0
                ? normalized.reduce(function (a, b) { return a + b; }, 0) / normalized.length
                : 0;
        });

        // ── Step 7: Final Rank — 4-level priority sort ──
        rankings.sort(function (a, b) {
            // Priority 1: KPIs Met (most first — descending)
            if (a.kpisMet !== b.kpisMet) return b.kpisMet - a.kpisMet;
            // Priority 2: Score Sum (highest first — descending)
            if (a.scoreSum !== b.scoreSum) return b.scoreSum - a.scoreSum;
            // Priority 3: KPI Rank Total (lowest first — ascending)
            if (a.kpiRankTotal !== b.kpiRankTotal) return a.kpiRankTotal - b.kpiRankTotal;
            // Priority 4: Tiebreaker (highest first — descending)
            if (Math.abs(a.tiebreaker - b.tiebreaker) > 1e-9) return b.tiebreaker - a.tiebreaker;
            // Priority 5: Name — deterministic order for otherwise-identical employees
            return a.name.localeCompare(b.name);
        });

        rankings.forEach(function (r, i) { r.rank = i + 1; });

        // Backward-compat: compositeScore (lower = better, used by matchup module)
        rankings.forEach(function (r) { r.compositeScore = r.rank; });

        return rankings;
    }

    /**
     * Build rankings for a specific period key (weekly or YTD).
     * Unlike buildCenterRankings which merges all periods,
     * this ranks only the employees present in the given period.
     */
    function buildRankingsForPeriod(periodKey) {
        if (!periodKey) return null;
        var wData = _getWeeklyData();
        var yData = _getYtdData();
        var period = wData[periodKey] || yData[periodKey];
        if (!period || !period.employees?.length) return null;

        var meta = period.metadata || {};
        var endStr = meta.endDate || (periodKey.includes('|') ? periodKey.split('|')[1] : '');
        var endYear = parseInt(String(endStr).split('-')[0], 10) || new Date().getFullYear();

        var rankings = _scoreAndRank(period.employees, endYear);
        if (!rankings.length) return null;

        // Identify team members for this period
        var teamMembers = _getTeamMembersForWeek(periodKey);
        var teamSet = new Set(teamMembers);

        return {
            rankings: rankings,
            totalEmployees: rankings.length,
            source: meta.label || periodKey,
            periodKey: periodKey,
            teamMembers: teamSet
        };
    }

    /**
     * Render the center ranking view
     */
    function renderCenterRanking() {
        var container = document.getElementById('centerRankingContent');
        if (!container) return;

        // Drop the remembered key if it no longer resolves (period was deleted,
        // replaced by cleanup, or hydrated from a different source mid-session).
        if (_selectedRankingPeriodKey) {
            var wData = _getWeeklyData();
            var yData = _getYtdData();
            if (!wData[_selectedRankingPeriodKey] && !yData[_selectedRankingPeriodKey]) {
                _selectedRankingPeriodKey = null;
                _rankingPeriodInitialized = false;
            }
        }

        // Default to most recent YTD period on first render. Only mark as
        // initialized once a YTD is actually found — otherwise a later render
        // (after data hydrates) will re-attempt the auto-pick.
        if (!_rankingPeriodInitialized) {
            var periods = _getAvailableRankingPeriods();
            var ytdPeriod = periods.find(function(p) { return p.type === 'ytd' && p.count >= 30; });
            if (ytdPeriod) {
                _selectedRankingPeriodKey = ytdPeriod.key;
                _rankingPeriodInitialized = true;
            }
        }

        var currentSelectValue = _selectedRankingPeriodKey || '';

        var data;
        if (_selectedRankingPeriodKey) {
            data = buildRankingsForPeriod(_selectedRankingPeriodKey);
        }
        // Fall back to the best-available source if the selected period
        // produced nothing. Covers stale keys, insufficient employees in the
        // selected period, and mid-session data swaps.
        if (!data || data.rankings.length === 0) {
            data = buildCenterRankings();
            if (data && data.rankings.length > 0) {
                _selectedRankingPeriodKey = data.periodKey || null;
                currentSelectValue = _selectedRankingPeriodKey || '';
            }
        }

        if (!data || data.rankings.length === 0) {
            container.innerHTML = _renderRankingPeriodSelector(currentSelectValue) +
                '<p style="color: #94a3b8; text-align: center; padding: 40px;">No ranking data available. Upload a full center data set (30+ employees) to see rankings.</p>';
            var sel = document.getElementById('rankingPeriodSelect');
            if (sel) sel.addEventListener('change', _onRankingPeriodChange);
            return;
        }

        var html = '';

        // Period selector
        html += _renderRankingPeriodSelector(currentSelectValue);

        // Header
        html += '<div style="margin-bottom: 20px; padding: 15px; background: #e3f2fd; border-radius: 8px; border-left: 4px solid #1565c0;">';
        html += '<strong>Center Rankings</strong> &mdash; ' + data.totalEmployees + ' employees scored';
        html += '<br><span style="color: #666; font-size: 0.85em;">Source: ' + _escapeHtml(data.source) + ' | Ranked by KPIs Met &rarr; Score Sum &rarr; KPI Rank Total &rarr; Tiebreaker</span>';
        html += '</div>';

        // Team summary
        var teamRanks = data.rankings.filter(function (r) { return data.teamMembers.has(r.name); });
        if (teamRanks.length > 0) {
            html += '<div style="margin-bottom: 20px; padding: 15px; background: #fff; border-radius: 8px; border: 1px solid #ddd; box-shadow: 0 1px 3px rgba(0,0,0,0.08);">';
            html += '<h4 style="margin-top: 0; color: #1a1a2e;">Your Team</h4>';
            html += '<div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 10px;">';

            teamRanks.forEach(function (r) {
                var statusColor = r.trackStatusValue === 'on-track-exceptional' ? '#2e7d32' :
                    r.trackStatusValue === 'on-track-successful' ? '#8bc34a' : '#c62828';
                var statusBg = r.trackStatusValue === 'on-track-exceptional' ? '#e8f5e9' :
                    r.trackStatusValue === 'on-track-successful' ? '#f1f8e9' : '#fbe9e7';
                var percentile = Math.round((1 - (r.rank - 1) / data.totalEmployees) * 100);

                html += '<div style="padding: 12px 16px; background: ' + statusBg + '; border-radius: 8px; border-left: 4px solid ' + statusColor + ';">';
                html += '<div class="ranking-card-name" data-employee="' + _escapeHtml(r.name) + '" style="font-weight: bold; font-size: 1.05em; cursor: pointer; text-decoration: underline;">' + _escapeHtml(r.name) + '</div>';
                html += '<div style="margin-top: 4px;">';
                html += '<span style="font-size: 1.3em; font-weight: bold; color: ' + statusColor + ';">#' + r.rank + '</span>';
                html += ' <span style="color: #666; font-size: 0.85em;">of ' + data.totalEmployees + ' (top ' + percentile + '%)</span>';
                html += '</div>';
                var kpiColor = r.kpisMet >= 4 ? '#2e7d32' : r.kpisMet >= 3 ? '#e65100' : '#c62828';
                html += '<div style="margin-top: 4px; font-size: 0.85em; color: #555;">' + _escapeHtml(r.trackLabel) + ' &mdash; Score: ' + r.scoreSum + '/' + (r.measuredCount * 3) + ' (KPI: ' + r.kpiScore.toFixed(1) + ')</div>';
                html += '<div style="margin-top: 2px; font-size: 0.85em;"><span style="font-weight: 700; color: ' + kpiColor + ';">' + r.kpisMet + '/5 KPIs met</span></div>';
                html += '<div style="font-size: 0.8em; color: #888;">Rank Total: ' + r.kpiRankTotal + ' | TB: ' + r.tiebreaker.toFixed(3) + '</div>';
                html += '</div>';
            });

            html += '</div></div>';
        }

        // Store data for re-sorting
        _lastRankingData = data;
        _currentSort = { key: 'rank', dir: 'asc' };

        // Full ranking table
        html += '<div id="centerRankingTableWrapper" style="padding: 20px; background: #fff; border-radius: 8px; border: 1px solid #ddd; box-shadow: 0 1px 3px rgba(0,0,0,0.08);">';
        html += '<h4 style="margin-top: 0; color: #1a1a2e;">Full Center Rankings</h4>';
        html += '<p style="margin: 0 0 12px 0; color: #666; font-size: 0.85em;">Click any column header to sort. Each metric shows value and rank (#).</p>';
        html += '</div>';

        container.innerHTML = html;
        renderRankingTable('rank', 'asc');

        // Bind period selector
        var sel = document.getElementById('rankingPeriodSelect');
        if (sel) sel.addEventListener('change', _onRankingPeriodChange);

        // Bind team card name clicks to scroll to that employee's row
        container.querySelectorAll('.ranking-card-name').forEach(function (el) {
            el.addEventListener('click', function () {
                var name = el.dataset.employee;
                var row = document.querySelector('#centerRankingTableWrapper tr[data-employee="' + CSS.escape(name) + '"]');
                if (row) {
                    row.scrollIntoView({ behavior: 'smooth', block: 'center' });
                    row.style.transition = 'background 0.3s';
                    row.style.background = '#bbdefb';
                    setTimeout(function () { row.style.background = ''; }, 2000);
                }
            });
        });
    }

    var _lastRankingData = null;
    var _currentSort = { key: 'composite', dir: 'asc' };

    var SORT_COLUMNS = [
        { key: 'rank', label: 'Rank', getValue: function(r) { return r.rank; }, reverse: false },
        { key: 'kpisMet', label: 'KPIs Met', getValue: function(r) { return r.kpisMet; }, reverse: true },
        { key: 'scoreSum', label: 'Score Sum', getValue: function(r) { return r.scoreSum; }, reverse: true },
        { key: 'kpiScore', label: 'KPI Score', getValue: function(r) { return r.kpiScore; }, reverse: true },
        { key: 'kpiRankTotal', label: 'Rank Total', getValue: function(r) { return r.kpiRankTotal; }, reverse: false },
        { key: 'tiebreaker', label: 'Tiebreaker', getValue: function(r) { return r.tiebreaker; }, reverse: true },
        { key: 'aht', label: 'AHT', getValue: function(r) { return r.values.aht; }, reverse: false },
        { key: 'adherence', label: 'Adherence', getValue: function(r) { return r.values.adherence; }, reverse: true },
        { key: 'sentiment', label: 'Sentiment', getValue: function(r) { return r.values.sentiment; }, reverse: true },
        { key: 'associateOverall', label: 'Assoc Overall', getValue: function(r) { return r.values.associateOverall; }, reverse: true },
        { key: 'reliability', label: 'Reliability', getValue: function(r) { return r.reliability; }, reverse: false }
    ];

    function renderRankingTable(sortKey, sortDir) {
        var wrapper = document.getElementById('centerRankingTableWrapper');
        if (!wrapper || !_lastRankingData) return;
        var data = _lastRankingData;

        // Sort rankings
        var col = SORT_COLUMNS.find(function(c) { return c.key === sortKey; });
        var sorted = data.rankings.slice().sort(function(a, b) {
            var aVal = col ? col.getValue(a) : a.rank;
            var bVal = col ? col.getValue(b) : b.rank;
            aVal = aVal !== null && aVal !== undefined ? aVal : (sortDir === 'asc' ? Infinity : -Infinity);
            bVal = bVal !== null && bVal !== undefined ? bVal : (sortDir === 'asc' ? Infinity : -Infinity);
            return sortDir === 'asc' ? (aVal - bVal) : (bVal - aVal);
        });

        var thStyle = 'padding: 6px 3px; text-align: center; border-bottom: 2px solid #ddd; cursor: pointer; user-select: none; font-size: 0.85em;';
        var arrow = function(key) {
            if (key !== sortKey) return ' <span style="opacity: 0.3;">&#8597;</span>';
            return sortDir === 'asc' ? ' <span style="color: #1565c0;">&#9650;</span>' : ' <span style="color: #1565c0;">&#9660;</span>';
        };

        var html = '<div style="overflow-x: auto;">';
        html += '<table style="width: 100%; border-collapse: collapse; font-size: 0.82em; table-layout: auto;">';
        html += '<thead><tr style="background: #f5f5f5;">';
        html += '<th class="rank-sort-header" data-sort="rank" style="' + thStyle + ' width: 30px;">Rank' + arrow('rank') + '</th>';
        html += '<th style="' + thStyle + ' text-align: left;">Name</th>';
        html += '<th class="rank-sort-header" data-sort="kpisMet" style="' + thStyle + '">KPIs Met' + arrow('kpisMet') + '</th>';
        html += '<th class="rank-sort-header" data-sort="scoreSum" style="' + thStyle + '">Score Sum' + arrow('scoreSum') + '</th>';
        html += '<th class="rank-sort-header" data-sort="kpiScore" style="' + thStyle + '">KPI Score' + arrow('kpiScore') + '</th>';
        html += '<th style="' + thStyle + '">Status</th>';
        html += '<th class="rank-sort-header" data-sort="aht" style="' + thStyle + '">AHT' + arrow('aht') + '</th>';
        html += '<th class="rank-sort-header" data-sort="adherence" style="' + thStyle + '">Adh' + arrow('adherence') + '</th>';
        html += '<th class="rank-sort-header" data-sort="sentiment" style="' + thStyle + '">Sent' + arrow('sentiment') + '</th>';
        html += '<th class="rank-sort-header" data-sort="associateOverall" style="' + thStyle + '">CX Adv' + arrow('associateOverall') + '</th>';
        html += '<th class="rank-sort-header" data-sort="reliability" style="' + thStyle + '">Rel' + arrow('reliability') + '</th>';
        html += '</tr></thead><tbody>';

        sorted.forEach(function (r, idx) {
            var isTeam = data.teamMembers.has(r.name);
            var supColor = _getSupervisorColor(r.name);
            var isDark = document.documentElement.getAttribute('data-theme') === 'dark';
            var defaultBg = isDark ? (idx % 2 === 0 ? '#1a1f2e' : 'transparent') : (idx % 2 === 0 ? '#fafafa' : '#fff');
            var rowBg = supColor || (isTeam ? (isDark ? '#0d2a1a' : '#e8f5e9') : defaultBg);
            var fontWeight = (isTeam || supColor) ? 'bold' : 'normal';

            // Status colors
            var statusColor, statusBg, statusText;
            if (r.trackStatusValue === 'on-track-exceptional') {
                statusColor = '#fff'; statusBg = '#2e7d32'; statusText = 'Exceptional';
            } else if (r.trackStatusValue === 'on-track-successful') {
                statusColor = '#fff'; statusBg = '#1565c0'; statusText = 'Successful';
            } else {
                statusColor = '#fff'; statusBg = '#c62828'; statusText = 'Off Track';
            }

            var scoreColor = function (s) {
                if (s === 3) return '#2e7d32';
                if (s === 2) return '#1565c0';
                return '#c62828';
            };

            // Rank cell formatting per spec
            var rankBg = '', rankColor = '';
            if (r.rank <= 26) { rankBg = '#1F4E79'; rankColor = '#FFFFFF'; }
            else if (r.rank >= 105) { rankBg = '#c62828'; rankColor = '#FFFFFF'; }

            var teamBorder = isTeam ? 'outline: 2px solid #2e7d32; outline-offset: -2px; ' : '';
            html += '<tr class="ranking-row" data-employee="' + _escapeHtml(r.name) + '" style="' + teamBorder + 'background: ' + rowBg + '; border-bottom: 1px solid #eee; font-weight: ' + fontWeight + ';">';

            // Rank
            var rankStyle = 'padding: 4px 3px; text-align: center; font-weight: bold;';
            if (rankBg) rankStyle += ' background: ' + rankBg + '; color: ' + rankColor + ';';
            html += '<td style="' + rankStyle + '">' + r.rank + '</td>';

            // Name
            html += '<td class="ranking-name-cell" style="padding: 4px 3px; white-space: nowrap;">';
            if (isTeam) {
                html += '<span style="color: #1565c0;">&#9733; </span>';
            } else if (supColor) {
                var _dotColor = _getSupervisorDotColor(r.name);
                html += '<span style="display:inline-block;width:9px;height:9px;border-radius:50%;background:' + _dotColor + ';box-shadow:0 0 0 1px rgba(0,0,0,0.25);margin-right:5px;vertical-align:middle;"></span>';
            }
            html += _escapeHtml(r.name) + '</td>';

            // KPIs Met
            var kpiMetColor = r.kpisMet >= 4 ? '#2e7d32' : r.kpisMet >= 3 ? '#e65100' : '#c62828';
            html += '<td style="padding: 4px 3px; text-align: center; font-weight: bold; color: ' + kpiMetColor + ';">' + r.kpisMet + '/5</td>';

            // Score Sum
            html += '<td style="padding: 4px 3px; text-align: center; font-weight: bold;">' + r.scoreSum + '</td>';

            // KPI Score
            html += '<td style="padding: 4px 3px; text-align: center; font-weight: bold; color: ' + scoreColor(Math.round(r.kpiScore)) + ';">' + r.kpiScore.toFixed(1) + '</td>';

            // Status badge
            html += '<td style="padding: 4px 3px; text-align: center;"><span style="display: inline-block; padding: 1px 5px; border-radius: 8px; font-size: 0.72em; font-weight: bold; color: ' + statusColor + '; background: ' + statusBg + ';">' + statusText + '</span></td>';

            // Individual metric cells
            var metricPairs = [
                { score: r.scores.aht, value: r.values.aht, key: 'aht', rankKey: 'aht' },
                { score: r.scores.adherence, value: r.values.adherence, key: 'scheduleAdherence', rankKey: 'adherence' },
                { score: r.scores.sentiment, value: r.values.sentiment, key: 'overallSentiment', rankKey: 'sentiment' },
                { score: r.scores.associateOverall, value: r.values.associateOverall, key: 'cxRepOverall', rankKey: 'associateOverall' },
                { score: r.scores.reliability, value: r.reliability, key: 'reliability', rankKey: 'reliability' }
            ];

            metricPairs.forEach(function (mp) {
                var display = mp.value !== null && mp.value !== undefined ? _formatMetricDisplay(mp.key, mp.value) : '--';
                var metricRank = r.metricRanks?.[mp.rankKey] || '?';
                var rankTextColor = metricRank <= 10 ? '#2e7d32' : metricRank <= Math.round(data.totalEmployees * 0.5) ? '#666' : '#c62828';
                var scoreBadge = mp.score !== null
                    ? '<span style="display: inline-block; width: 18px; height: 18px; line-height: 18px; border-radius: 50%; font-size: 0.7em; font-weight: bold; color: white; background: ' + scoreColor(mp.score) + '; text-align: center; margin-right: 3px;">' + mp.score + '</span>'
                    : '';
                var surveyBadge = '';
                if (mp.rankKey === 'associateOverall' && r.surveyTotal > 0) {
                    surveyBadge = ' <span style="font-size: 0.68em; color: #888;">(' + r.surveyTotal + ')</span>';
                }
                var cellColor = mp.score !== null ? scoreColor(mp.score) : '#333';
                html += '<td style="padding: 4px 3px; text-align: center; color: ' + cellColor + '; white-space: nowrap;">' +
                    scoreBadge + display + surveyBadge + ' <span style="font-size: 0.72em; color: ' + rankTextColor + ';">#' + metricRank + '</span></td>';
            });

            html += '</tr>';
        });

        html += '</tbody></table>';
        html += '</div>';

        // Keep the header content, replace just the table area
        var existingHeader = wrapper.querySelector('h4');
        var existingDesc = wrapper.querySelector('p');
        wrapper.innerHTML = '';
        if (existingHeader) wrapper.appendChild(existingHeader);
        if (existingDesc) wrapper.appendChild(existingDesc);
        var tableDiv = document.createElement('div');
        tableDiv.innerHTML = html;
        wrapper.appendChild(tableDiv.firstChild);

        // Bind sort headers
        wrapper.querySelectorAll('.rank-sort-header').forEach(function(th) {
            th.addEventListener('click', function() {
                var newKey = th.dataset.sort;
                var col = SORT_COLUMNS.find(function(c) { return c.key === newKey; });
                var defaultDir = col && col.reverse ? 'desc' : 'asc';
                var newDir;
                if (_currentSort.key === newKey) {
                    newDir = _currentSort.dir === 'asc' ? 'desc' : 'asc';
                } else {
                    newDir = defaultDir;
                }
                _currentSort = { key: newKey, dir: newDir };
                renderRankingTable(newKey, newDir);
            });
        });
    }

    /**
     * Reset the period selector so the next render re-picks the best YTD period.
     * Call after new data uploads so rankings reflect the latest data.
     */
    function resetPeriodSelection() {
        _rankingPeriodInitialized = false;
        _selectedRankingPeriodKey = null;
    }

    /* ── Module export ── */
    window.DevCoachModules = window.DevCoachModules || {};
    window.DevCoachModules.centerRanking = {
        renderCenterRanking: renderCenterRanking,
        buildCenterRankings: buildCenterRankings,
        buildRankingsForPeriod: buildRankingsForPeriod,
        resetPeriodSelection: resetPeriodSelection
    };

    window.renderCenterRanking = renderCenterRanking;
})();
