(function () {
    'use strict';

    /* ── Global helpers accessed via window ── */
    function _getWeeklyData() {
        return typeof weeklyData !== 'undefined' ? weeklyData : {};
    }
    function _getYtdData() {
        return typeof ytdData !== 'undefined' ? ytdData : {};
    }
    function _getWeeklyKeysSorted() {
        return typeof window.getWeeklyKeysSorted === 'function' ? window.getWeeklyKeysSorted() : Object.keys(_getWeeklyData());
    }
    function _getTeamMembersForWeek(weekKey) {
        return typeof window.getTeamMembersForWeek === 'function' ? window.getTeamMembersForWeek(weekKey) : [];
    }
    function _formatMetricDisplay(key, value) {
        return typeof window.formatMetricDisplay === 'function' ? window.formatMetricDisplay(key, value) : String(value);
    }
    function _escapeHtml(str) {
        var mod = window.DevCoachModules?.sharedUtils;
        if (mod?.escapeHtml) return mod.escapeHtml(str);
        return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }

    // Metrics to project (the meaningful ones with targets)
    var FUTURES_METRICS = [
        'scheduleAdherence', 'cxRepOverall', 'fcr', 'overallExperience',
        'transfers', 'overallSentiment', 'positiveWord', 'negativeWord',
        'managingEmotions', 'aht', 'acw', 'holdTime', 'reliability'
    ];

    // Cumulative metrics are summed across periods, not averaged.
    // The "need to average" projection doesn't apply — it's "budget remaining".
    var CUMULATIVE_METRICS = new Set(['reliability']);

    // The year is 52 weeks everywhere on this screen. It lives here rather than
    // inside estimateWeekCounts because the YTD week count below has to clamp
    // against the same number, and two 52s in one file is one 52 too many.
    var TOTAL_WEEKS_IN_YEAR = 52;

    /**
     * Find the most recent real (non-auto) YTD upload for a year.
     * Returns { employees, source, endDate, endDateText } or null.
     *
     * The end date is carried out because the caller needs to know how much of
     * the year that upload actually covers, not just what is in it.
     */
    function findRealYtdUpload(year) {
        var ytd = _getYtdData();
        var best = null;
        var bestDate = 0;
        var bestEndText = '';

        Object.keys(ytd).forEach(function (key) {
            var period = ytd[key];
            var meta = period?.metadata || {};
            if (meta.autoGeneratedYtd) return; // skip auto-generated
            if (meta.periodType !== 'ytd') return;
            var endStr = meta.endDate || (key.includes('|') ? key.split('|')[1] : '');
            var endDate = endStr ? new Date(endStr) : null;
            if (!endDate || isNaN(endDate) || endDate.getFullYear() !== year) return;
            if (endDate.getTime() > bestDate) {
                best = period;
                bestDate = endDate.getTime();
                bestEndText = String(endStr);
            }
        });

        if (best && best.employees) {
            return {
                employees: best.employees,
                source: best.metadata?.label || 'YTD upload',
                endDate: new Date(bestDate),
                endDateText: bestEndText
            };
        }
        return null;
    }

    // ISO date text pulled apart by hand rather than through a Date, because
    // "2026-01-01" parses as UTC midnight and reads back as December 31 through
    // the local getters in every timezone west of Greenwich. January 1 is the one
    // date where being a day out moves the answer into a different year.
    function _ymdParts(dateText) {
        var m = /^(\d{4})-(\d{2})-(\d{2})/.exec(String(dateText || ''));
        if (!m) return null;
        return { year: parseInt(m[1], 10), month: parseInt(m[2], 10) - 1, day: parseInt(m[3], 10) };
    }

    /*
     * How many weeks of the year are already spent as of a date.
     *
     * The projection needs a denominator, and until this existed the only one on
     * offer was "how many weekly files did somebody upload". Those are not the
     * same question. A YTD upload closing on July 25 covers thirty weeks of the
     * year whether the weekly folder holds thirty files, twelve, or none, and
     * twelve is the ordinary case, because people upload the YTD file and stop
     * bothering with the weeks. The screen then read twelve weeks done and forty
     * to go, and every required average on it was computed against a year that
     * was still two thirds ahead when in truth it was two thirds gone. It told
     * people they had time they did not have.
     *
     * The rule chosen is whole weeks elapsed since January 1, ceil(dayOfYear / 7),
     * clamped into 0..52. Two alternatives were rejected. Counting weekly files is
     * the bug above. ISO week numbers do not fit a fixed 52-week year: an ISO year
     * can hold 53 weeks, which drives weeksRemaining negative, and an early
     * January date belongs to week 52 or 53 of the PRIOR ISO year, which would
     * report a January 2 upload as a year already over. Day-of-year over seven has
     * neither problem and agrees with the other denominator in this file, where 52
     * weekly uploads is a full year. It rounds up because a part week already
     * lived through is a week nobody gets back.
     */
    function weeksCompletedThroughDate(endDateText, endDate) {
        var parts = _ymdParts(endDateText);
        var year, month, day;
        if (parts) {
            year = parts.year; month = parts.month; day = parts.day;
        } else if (endDate instanceof Date && !isNaN(endDate)) {
            year = endDate.getFullYear(); month = endDate.getMonth(); day = endDate.getDate();
        } else {
            return null;
        }
        var dayOfYear = Math.round((Date.UTC(year, month, day) - Date.UTC(year, 0, 1)) / 86400000) + 1;
        if (!Number.isFinite(dayOfYear)) return null;
        var weeks = Math.ceil(dayOfYear / 7);
        if (weeks < 0) weeks = 0;
        if (weeks > TOTAL_WEEKS_IN_YEAR) weeks = TOTAL_WEEKS_IN_YEAR;
        return weeks;
    }

    /*
     * Write a weeks-completed figure into a week split.
     *
     * Both branches of buildFuturesData have to do this, and for a while only one
     * of them did it properly, so the arithmetic lives here where a fix cannot
     * land on one branch and miss the other. A count of zero or less is refused
     * rather than written, which is how a caller learns its date was unreadable
     * and it needs to try something else; the return value says which happened.
     */
    function applyWeeksCompleted(weekInfo, weeks) {
        if (weeks === null || !Number.isFinite(weeks) || weeks <= 0) return false;
        var capped = Math.min(weeks, weekInfo.totalWeeks);
        weekInfo.weeksCompleted = capped;
        weekInfo.weeksRemaining = Math.max(0, weekInfo.totalWeeks - capped);
        return true;
    }

    /**
     * Estimate total weeks in the year and weeks completed based on uploaded data
     */
    function estimateWeekCounts() {
        var currentYear = new Date().getFullYear();
        var keys = _getWeeklyKeysSorted();
        var yearKeys = keys.filter(function (k) {
            var endStr = k.split('|')[1] || '';
            return parseInt(endStr.split('-')[0], 10) === currentYear;
        });

        var weeksCompleted = yearKeys.length;
        var totalWeeks = TOTAL_WEEKS_IN_YEAR;
        var weeksRemaining = Math.max(0, totalWeeks - weeksCompleted);

        return {
            currentYear: currentYear,
            weeksCompleted: weeksCompleted,
            totalWeeks: totalWeeks,
            weeksRemaining: weeksRemaining,
            yearKeys: yearKeys
        };
    }

    // Metrics that should be weighted by surveyTotal instead of totalCalls
    var SURVEY_WEIGHTED = new Set(['cxRepOverall', 'fcr', 'overallExperience']);

    // Rate metrics that get weighted-averaged (matches buildYtdAggregateForYear)
    var RATE_METRICS = new Set([
        'scheduleAdherence', 'transfers', 'cxRepOverall', 'fcr', 'overallExperience',
        'aht', 'talkTime', 'acw', 'holdTime', 'overallSentiment', 'managingEmotions',
        'negativeWord', 'positiveWord'
    ]);

    /**
     * Narrow a set of period keys down to a single granularity.
     *
     * Weekly, monthly and quarterly uploads routinely cover the same calendar
     * days, and calls and surveys accumulate, so counting a month beside the four
     * weeks inside it counts that volume twice. Matches buildYtdAggregateForYear's
     * sourceTypePriority logic. Returns { keys, type }.
     */
    function chooseSingleSourceKeys(yearKeys) {
        var wData = _getWeeklyData();
        var sourceTypePriority = ['week', 'week-in-progress', 'month', 'quarter', 'custom', 'daily'];
        var periodsByType = {};
        (yearKeys || []).forEach(function (weekKey) {
            var period = wData[weekKey];
            if (!period) return;
            var pType = period.metadata?.periodType || 'week';
            if (!periodsByType[pType]) periodsByType[pType] = [];
            periodsByType[pType].push(weekKey);
        });

        var chosenType = null;
        for (var i = 0; i < sourceTypePriority.length; i++) {
            if (periodsByType[sourceTypePriority[i]] && periodsByType[sourceTypePriority[i]].length > 0) {
                chosenType = sourceTypePriority[i];
                break;
            }
        }
        return {
            keys: chosenType ? periodsByType[chosenType] : (yearKeys || []),
            type: chosenType
        };
    }

    /**
     * Aggregate YTD values directly from weekly data uploads.
     * Uses the same rules as buildYtdAggregateForYear but WITHOUT the
     * anchor pattern, so it always reflects the actual weekly uploads.
     *
     * - Rate metrics: weighted average (by totalCalls or surveyTotal)
     * - Cumulative metrics (reliability): summed
     */
    function aggregateFromWeeklyData(yearKeys) {
        var wData = _getWeeklyData();
        var chosen = chooseSingleSourceKeys(yearKeys);
        var filteredKeys = chosen.keys;
        var chosenType = chosen.type;

        var empAgg = {}; // { name: { totalCalls, surveyTotal, reliability, weightedSums, weightedCounts } }

        // How much of the calendar these periods actually cover. It is tracked
        // here, while the periods are being read, rather than inferred later from
        // the number of them, because the number of them answers a different
        // question. Six monthly uploads are six periods and half a year. The
        // caller needs the half year; see the fallback branch in buildFuturesData
        // for what happened when it was handed the six.
        var coverageEndText = '';
        var coverageEndStamp = -1;
        var weeksCovered = 0;

        filteredKeys.forEach(function (weekKey) {
            var period = wData[weekKey];
            if (!period || !period.employees) return;

            weeksCovered += _periodWeekSpan(period, weekKey);
            var endText = period.metadata?.endDate || (weekKey.indexOf('|') > -1 ? weekKey.split('|')[1] : '');
            var endParts = _ymdParts(endText);
            if (endParts) {
                var endStamp = (endParts.year * 10000) + (endParts.month * 100) + endParts.day;
                if (endStamp > coverageEndStamp) {
                    coverageEndStamp = endStamp;
                    coverageEndText = String(endText);
                }
            }

            period.employees.forEach(function (emp) {
                if (!emp || !emp.name) return;

                if (!empAgg[emp.name]) {
                    empAgg[emp.name] = {
                        name: emp.name,
                        totalCalls: 0,
                        surveyTotal: 0,
                        reliability: 0,
                        weightedSums: {},
                        weightedCounts: {}
                    };
                }

                var agg = empAgg[emp.name];
                var tc = parseInt(emp.totalCalls, 10);
                var st = parseInt(emp.surveyTotal, 10);

                agg.totalCalls += Number.isInteger(tc) ? tc : 0;
                agg.surveyTotal += Number.isInteger(st) ? st : 0;

                // Reliability: hours missed in each period, so they add up. The
                // comments above always said summed; the code took the highest
                // value instead, which kept a person's single worst week and threw
                // away every other absence. This path has no YTD anchor, so every
                // period here is a per-period figure and all of them count.
                var rel = parseFloat(emp.reliability);
                if (Number.isFinite(rel)) agg.reliability += rel;

                // Rate metrics: accumulate weighted sums
                RATE_METRICS.forEach(function (mk) {
                    var val = parseFloat(emp[mk]);
                    if (!Number.isFinite(val)) return;

                    var weight = 1;
                    if (SURVEY_WEIGHTED.has(mk)) {
                        weight = Number.isInteger(st) && st > 0 ? st : 0;
                    } else {
                        weight = Number.isInteger(tc) && tc > 0 ? tc : 1;
                    }
                    if (weight <= 0) return;

                    agg.weightedSums[mk] = (agg.weightedSums[mk] || 0) + (val * weight);
                    agg.weightedCounts[mk] = (agg.weightedCounts[mk] || 0) + weight;
                });
            });
        });

        // Finalize: compute weighted averages
        var employees = [];
        Object.keys(empAgg).forEach(function (name) {
            var agg = empAgg[name];

            // surveyTotal travels with totalCalls because projectedVolume asks a
            // row for whichever column its metric is weighted by, and the three
            // survey metrics ask for this one. It was accumulated above and then
            // dropped here, so parseFloat(undefined) came back NaN, projectedVolume
            // returned null, and cxRepOverall, fcr and overallExperience quietly
            // fell back to week counting while every call-weighted metric beside
            // them on the same row was blended by volume. Two denominators in one
            // table, and nothing on screen to say which row got which.
            var result = {
                name: name,
                reliability: agg.reliability,
                totalCalls: agg.totalCalls,
                surveyTotal: agg.surveyTotal
            };

            RATE_METRICS.forEach(function (mk) {
                var totalWeight = agg.weightedCounts[mk] || 0;
                if (totalWeight > 0) {
                    result[mk] = agg.weightedSums[mk] / totalWeight;
                }
            });

            employees.push(result);
        });

        var sourceLabel = filteredKeys.length + ' ' + (chosenType || 'period') + (filteredKeys.length !== 1 ? 's' : '') + ' aggregated';
        return employees.length > 0
            ? {
                employees: employees,
                source: sourceLabel,
                periodCount: filteredKeys.length,
                periodType: chosenType,
                coverageEndText: coverageEndText,
                weeksCovered: weeksCovered
            }
            : null;
    }

    // What a period type is nominally worth in weeks. Only consulted when a key
    // carries no readable dates, which ordinary uploads always do carry. The old
    // fallback was a flat one week for every type: right for the undated weekly
    // key this is almost always reached by, and wrong by a factor of four for a
    // month, an error that would then ride into a per-week run rate and out onto
    // the screen.
    var NOMINAL_WEEK_SPAN = {
        week: 1,
        'week-in-progress': 1,
        month: TOTAL_WEEKS_IN_YEAR / 12,
        quarter: TOTAL_WEEKS_IN_YEAR / 4,
        daily: 1 / 7
    };

    /**
     * Calendar weeks a period covers, from its start and end dates, falling back
     * to what its declared period type is nominally worth.
     */
    function _periodWeekSpan(period, periodKey) {
        var meta = (period && period.metadata) || {};
        var hasBar = String(periodKey || '').indexOf('|') > -1;
        var start = _ymdParts(meta.startDate || (hasBar ? periodKey.split('|')[0] : ''));
        var end = _ymdParts(meta.endDate || (hasBar ? periodKey.split('|')[1] : ''));
        if (!start || !end) {
            var nominal = NOMINAL_WEEK_SPAN[meta.periodType];
            return nominal > 0 ? nominal : 1;
        }
        var days = Math.round(
            (Date.UTC(end.year, end.month, end.day) - Date.UTC(start.year, start.month, start.day)) / 86400000
        ) + 1;
        if (!(days > 0)) return 1;
        return days / 7;
    }

    /**
     * Per-week call and survey volume for each employee, read off the weekly
     * uploads on file for the year.
     *
     * This is the forward run rate: the weeks still to come are worth roughly
     * what the weeks on hand are worth, and the weekly uploads are the only place
     * that says what somebody is currently handling. A YTD file cannot answer it,
     * because its per-week average is smeared across the whole year and hides
     * exactly the change that matters, somebody moving onto a light schedule or
     * off one. Volume is divided by calendar weeks covered rather than by period
     * count, so a month upload is not mistaken for a week's worth of calls.
     *
     * Returns { name: { callsPerWeek, surveysPerWeek, weeks } }.
     */
    function weeklyVolumeRates(yearKeys) {
        var wData = _getWeeklyData();
        var chosen = chooseSingleSourceKeys(yearKeys);
        var rates = {};

        chosen.keys.forEach(function (periodKey) {
            var period = wData[periodKey];
            if (!period || !period.employees) return;
            var span = _periodWeekSpan(period, periodKey);

            period.employees.forEach(function (emp) {
                if (!emp || !emp.name) return;
                if (!rates[emp.name]) {
                    rates[emp.name] = { calls: 0, surveys: 0, weeks: 0, callsPerWeek: null, surveysPerWeek: null };
                }
                var row = rates[emp.name];
                var tc = parseFloat(emp.totalCalls);
                var st = parseFloat(emp.surveyTotal);
                if (Number.isFinite(tc)) row.calls += tc;
                if (Number.isFinite(st)) row.surveys += st;
                row.weeks += span;
            });
        });

        Object.keys(rates).forEach(function (name) {
            var row = rates[name];
            if (row.weeks > 0) {
                row.callsPerWeek = row.calls > 0 ? row.calls / row.weeks : null;
                row.surveysPerWeek = row.surveys > 0 ? row.surveys / row.weeks : null;
            }
        });

        return rates;
    }

    /**
     * The weights for one employee and one metric: volume already banked, and
     * volume the rest of the year is expected to carry.
     *
     * Which column counts is the same question buildYtdAggregateForYear answers
     * with SURVEY_WEIGHTED, so the answer is taken from the same set. Returns null
     * when the banked volume is missing or zero, which is the signal to fall back
     * to week counts rather than to invent a weight.
     */
    function projectedVolume(ytdEmp, rate, metricKey, weekInfo) {
        if (!ytdEmp || !weekInfo) return null;
        var isSurvey = SURVEY_WEIGHTED.has(metricKey);
        var done = parseFloat(isSurvey ? ytdEmp.surveyTotal : ytdEmp.totalCalls);
        if (!Number.isFinite(done) || done <= 0) return null;

        var perWeek = rate ? (isSurvey ? rate.surveysPerWeek : rate.callsPerWeek) : null;
        if (!Number.isFinite(perWeek) || perWeek <= 0) {
            // No weekly uploads to read a current run rate from. Spreading the
            // banked volume evenly over the weeks it covers is the only remaining
            // guess, and it lands on the same answer week counting would give,
            // which is the right result when nothing better is known.
            if (!(weekInfo.weeksCompleted > 0)) return null;
            perWeek = done / weekInfo.weeksCompleted;
        }

        var remaining = perWeek * weekInfo.weeksRemaining;
        if (!Number.isFinite(remaining) || remaining <= 0) return null;
        return { done: done, remaining: remaining, perWeek: perWeek };
    }

    /*
     * What the rest of the year has to average for the year to land on target.
     *
     * The weights matter more than the arithmetic here. A YTD figure in this app
     * is volume-weighted and not a flat average of weeks: buildYtdAggregateForYear
     * weights every rate metric by totalCalls, and the three survey metrics by
     * surveyTotal, which is why SURVEY_WEIGHTED and RATE_METRICS exist above.
     * This function used to blend by week count, and blending by week count only
     * gives the same answer when every week carries identical volume, which no
     * week does.
     *
     * The gap is not a rounding difference and it does not point one way. AHT is
     * where it hurts most. Somebody who has handled 6,000 calls at 470 seconds and
     * has since moved to a light schedule of 90 calls a week cannot drag the year
     * back to 426, because the weeks left are worth a fraction of what is already
     * banked. Week counting reported a required average that looked reachable,
     * isAchievable waved it through, and the coaching conversation was built on a
     * number that could not happen. Weighted the other way, a heavy final quarter
     * after a quiet start, it overstates the climb and talks somebody out of a
     * target still well within reach.
     *
     * So the weights are handed in. `volume` is { done, remaining } in whatever
     * unit the metric is weighted by; when it is missing or unusable the function
     * falls back to week counts, which is the old behaviour and the honest guess
     * when nothing better is known. An upload with no call-count column still has
     * to produce a number rather than blanking the screen.
     *
     * There is one implementation because there used to be two: calculateDailyTarget
     * held a line-for-line copy of this formula, so the check-in summary and the
     * table could quietly disagree the moment either was touched.
     */
    function calculateRequiredAverage(currentAvg, weeksCompleted, weeksRemaining, target, volume) {
        if (weeksRemaining <= 0) return null;

        var done = volume ? parseFloat(volume.done) : NaN;
        var remaining = volume ? parseFloat(volume.remaining) : NaN;
        var weighted = Number.isFinite(done) && done > 0 && Number.isFinite(remaining) && remaining > 0;

        var weightDone = weighted ? done : weeksCompleted;
        var weightLeft = weighted ? remaining : weeksRemaining;
        if (!(weightLeft > 0) || !(weightDone >= 0)) return null;

        var totalNeeded = target * (weightDone + weightLeft);
        var currentTotal = currentAvg * weightDone;
        return (totalNeeded - currentTotal) / weightLeft;
    }

    /**
     * Determine if a required average is achievable
     */
    function isAchievable(metricKey, requiredAvg) {
        var metric = window.METRICS_REGISTRY[metricKey];
        if (!metric) return true;
        if (requiredAvg < 0) return false;
        if (metric.unit === '%' && requiredAvg > 100) return false;
        return true;
    }

    /**
     * Build futures projection data for all team members
     */
    function buildFuturesData() {
        var weekInfo = estimateWeekCounts();
        var currentYear = weekInfo.currentYear;
        var wData = _getWeeklyData();
        var latestKey = weekInfo.yearKeys.length > 0 ? weekInfo.yearKeys[weekInfo.yearKeys.length - 1] : null;

        // Get team members from latest period (weekly or YTD)
        var teamMembers = [];
        var teamSourcePeriod = latestKey && wData[latestKey] ? wData[latestKey] : null;

        // Fall back to YTD data if no weekly data
        if (!teamSourcePeriod) {
            var yData = _getYtdData();
            var bestYtdKey = null;
            var bestYtdDate = 0;
            Object.keys(yData).forEach(function (k) {
                var meta = yData[k]?.metadata || {};
                var endStr = meta.endDate || (k.includes('|') ? k.split('|')[1] : '');
                var endYear = parseInt(String(endStr).split('-')[0], 10);
                if (endYear !== currentYear) return;
                var d = new Date(endStr);
                if (!isNaN(d) && d.getTime() > bestYtdDate) {
                    bestYtdDate = d.getTime();
                    bestYtdKey = k;
                }
            });
            if (bestYtdKey) {
                teamSourcePeriod = yData[bestYtdKey];
                latestKey = bestYtdKey;
            }
        }

        if (teamSourcePeriod) {
            var teamFilter = window.DevCoachModules?.teamFilter;
            var filterKey = latestKey;
            if (teamFilter?.getTeamSelectionContext) {
                var ctx = teamFilter.getTeamSelectionContext();
                if (ctx.weekKey) filterKey = ctx.weekKey;
            }
            var members = _getTeamMembersForWeek(filterKey);
            var allEmps = (teamSourcePeriod.employees || []).map(function (e) { return e.name; });
            teamMembers = members.length > 0 ? allEmps.filter(function (n) { return members.includes(n); }) : allEmps;
        }
        // Sort alphabetically by first name
        teamMembers.sort(function (a, b) {
            var aFirst = (a || '').split(/[\s,]+/)[0].toLowerCase();
            var bFirst = (b || '').split(/[\s,]+/)[0].toLowerCase();
            return aFirst.localeCompare(bFirst);
        });

        // Primary: use real YTD upload if available (source of truth)
        var ytdEmployees = [];
        var ytdSource = '';
        var realYtd = findRealYtdUpload(currentYear);
        if (realYtd) {
            ytdEmployees = realYtd.employees;
            ytdSource = realYtd.source;
            // The values now come from the YTD file, so the weeks have to come
            // from it as well. estimateWeekCounts counted weekly uploads, and a
            // YTD file closing at week 30 beside twelve weekly files was reported
            // as twelve weeks done and forty to go, so the branch that is supposed
            // to be the source of truth was the one telling people the year had
            // barely started. The fallback branch below now asks the same question
            // of its own periods; whichever data the screen is built on, weeks
            // completed means calendar weeks elapsed and never a count of files.
            applyWeeksCompleted(weekInfo, weeksCompletedThroughDate(realYtd.endDateText, realYtd.endDate));
        } else {
            // Fallback: aggregate from weekly data when no YTD upload exists
            var weeklyAgg = aggregateFromWeeklyData(weekInfo.yearKeys);
            if (weeklyAgg) {
                ytdEmployees = weeklyAgg.employees;
                ytdSource = weeklyAgg.source;
                // Same rule as the YTD branch above, for the same reason: the
                // values came from these periods, so the weeks come from the date
                // those periods close on. This used to count the uploads instead,
                // which is only right when every upload is a week. Six monthly
                // files covering January through June reported six weeks done and
                // forty-six to go, on the last day of June, and then every
                // required average was blended against a year that had barely
                // started while projectedVolume multiplied a perfectly good
                // per-week rate by forty-six weeks that do not exist. The upload
                // wizard offers month and quarter uploads and recommends them as a
                // replacement for four or five weekly ones, so this is a path the
                // app actively steers people onto, not a corner.
                if (!applyWeeksCompleted(weekInfo, weeksCompletedThroughDate(weeklyAgg.coverageEndText))) {
                    // Nothing in the uploads carried a readable end date. The
                    // calendar span of the periods themselves is the last thing
                    // left that knows a month is not a week, and on the undated
                    // weekly keys this branch is actually reached by, it lands on
                    // the same answer counting them used to give.
                    applyWeeksCompleted(weekInfo, Math.ceil(weeklyAgg.weeksCovered));
                }
            }
        }

        var targets = window.DevCoachModules?.metricProfiles?.TARGETS_BY_YEAR?.[currentYear] || {};
        var ratingBands = window.DevCoachModules?.metricProfiles?.RATING_BANDS_BY_YEAR?.[currentYear] || {};

        // Read once for the whole team rather than per employee per metric.
        var volumeRates = weeklyVolumeRates(weekInfo.yearKeys);

        var results = [];
        teamMembers.forEach(function (empName) {
            // Find this employee in the aggregated YTD data
            var ytdEmp = null;
            for (var i = 0; i < ytdEmployees.length; i++) {
                if (ytdEmployees[i].name === empName) {
                    ytdEmp = ytdEmployees[i];
                    break;
                }
            }
            if (!ytdEmp) return;

            var empResult = {
                name: empName,
                dataSource: ytdSource,
                metrics: {}
            };

            FUTURES_METRICS.forEach(function (metricKey) {
                var targetConfig = targets[metricKey];
                if (!targetConfig) return;

                var val = parseFloat(ytdEmp[metricKey]);
                if (isNaN(val)) return;

                var currentValue = val;
                var meetTarget = targetConfig.value;
                var isReverse = targetConfig.type === 'max';
                var isCumulative = CUMULATIVE_METRICS.has(metricKey);

                // Determine "exceed" target from rating bands (score 3)
                var exceedTarget = meetTarget;
                var bandConfig = ratingBands[metricKey];
                if (bandConfig) {
                    exceedTarget = isReverse ? bandConfig.score3.max : bandConfig.score3.min;
                }

                var requiredToMeet = null;
                var requiredToExceed = null;
                var meetAchievable = null;
                var exceedAchievable = null;
                var currentlyMeeting, currentlyExceeding;
                var budgetRemaining = null;
                var exceedBudgetRemaining = null;
                var volume = isCumulative ? null : projectedVolume(ytdEmp, volumeRates[empName], metricKey, weekInfo);

                if (isCumulative) {
                    // Cumulative metrics (reliability): compare total used vs annual max
                    currentlyMeeting = currentValue <= meetTarget;
                    currentlyExceeding = bandConfig
                        ? (currentValue <= exceedTarget)
                        : currentlyMeeting;
                    budgetRemaining = meetTarget - currentValue;
                    exceedBudgetRemaining = bandConfig ? exceedTarget - currentValue : null;
                } else {
                    // Rate metrics: use weighted average projection
                    currentlyMeeting = isReverse ? (currentValue <= meetTarget) : (currentValue >= meetTarget);
                    currentlyExceeding = bandConfig
                        ? (isReverse ? (currentValue <= exceedTarget) : (currentValue >= exceedTarget))
                        : currentlyMeeting;

                    requiredToMeet = calculateRequiredAverage(currentValue, weekInfo.weeksCompleted, weekInfo.weeksRemaining, meetTarget, volume);
                    requiredToExceed = calculateRequiredAverage(currentValue, weekInfo.weeksCompleted, weekInfo.weeksRemaining, exceedTarget, volume);
                    meetAchievable = requiredToMeet !== null ? isAchievable(metricKey, requiredToMeet) : null;
                    exceedAchievable = requiredToExceed !== null ? isAchievable(metricKey, requiredToExceed) : null;
                }

                empResult.metrics[metricKey] = {
                    currentAvg: currentValue,
                    meetTarget: meetTarget,
                    exceedTarget: exceedTarget,
                    requiredToMeet: requiredToMeet,
                    requiredToExceed: requiredToExceed,
                    meetAchievable: meetAchievable,
                    exceedAchievable: exceedAchievable,
                    currentlyMeeting: currentlyMeeting,
                    currentlyExceeding: currentlyExceeding,
                    isReverse: isReverse,
                    hasExceedBand: !!bandConfig,
                    isCumulative: isCumulative,
                    budgetRemaining: budgetRemaining,
                    exceedBudgetRemaining: exceedBudgetRemaining,
                    // Carried so the check-in summary blends on the same weights
                    // the table did. Passing week counts there and volume here is
                    // how the two surfaces used to disagree about the same person.
                    volume: volume
                };
            });

            results.push(empResult);
        });

        return {
            weekInfo: weekInfo,
            employees: results
        };
    }

    /**
     * Render the futures projection table
     */
    function renderFutures() {
        var container = document.getElementById('futuresContent');
        if (!container) return;

        var data = buildFuturesData();
        var weekInfo = data.weekInfo;

        if (data.employees.length === 0) {
            container.innerHTML = '<p style="color: var(--text-tertiary); text-align: center; padding: 40px;">No data available. Upload data to see projections.</p>';
            return;
        }

        var html = '';

        // Summary header
        html += '<div style="margin-bottom: 20px; padding: 15px; background: var(--green-soft); border-radius: 8px; border-left: 4px solid #4caf50;">';
        html += '<strong>Year Progress:</strong> ' + weekInfo.weeksCompleted + ' weeks completed, ' + weekInfo.weeksRemaining + ' weeks remaining in ' + weekInfo.currentYear;
        html += '</div>';

        // Employee selector
        html += '<div style="margin-bottom: 20px; padding: 15px; background: var(--bg-surface); border-radius: 8px; border: 1px solid var(--border);">';
        html += '<label for="futuresEmployeeSelect" style="font-weight: bold; display: block; margin-bottom: 8px;">Select Associate:</label>';
        html += '<select id="futuresEmployeeSelect" style="width: 100%; padding: 8px; border: 1px solid var(--border); border-radius: 4px; font-size: 1em; cursor: pointer;">';
        html += '<option value="__all__">All Team Members</option>';
        data.employees.forEach(function (emp) {
            html += '<option value="' + _escapeHtml(emp.name) + '">' + _escapeHtml(emp.name) + '</option>';
        });
        html += '</select>';
        html += '</div>';

        // Timeframe toggle
        html += '<div style="margin-bottom: 20px; padding: 15px; background: var(--bg-surface); border-radius: 8px; border: 1px solid var(--border);">';
        html += '<label style="font-weight: bold; display: block; margin-bottom: 8px;">Show targets as:</label>';
        html += '<div style="display: flex; gap: 8px;">';
        ['Daily', 'Weekly', 'Monthly'].forEach(function (label) {
            var val = label.toLowerCase();
            var isDefault = val === 'weekly';
            html += '<button type="button" class="futures-timeframe-btn" data-timeframe="' + val + '" style="padding: 8px 18px; border: 2px solid ' + (isDefault ? '#4caf50' : 'var(--border)') + '; background: ' + (isDefault ? '#4caf50' : 'white') + '; color: ' + (isDefault ? 'white' : 'var(--text-secondary)') + '; border-radius: 4px; cursor: pointer; font-weight: bold;">' + label + '</button>';
        });
        html += '</div></div>';

        // Content area
        html += '<div id="futuresTableContainer"></div>';

        container.innerHTML = html;

        // Bind employee select
        var select = document.getElementById('futuresEmployeeSelect');
        if (select) {
            select.addEventListener('change', function () {
                var tf = document.querySelector('.futures-timeframe-btn[style*="background: rgb(76, 175, 80)"]')?.dataset?.timeframe || 'weekly';
                renderFuturesTable(data, select.value, tf);
            });
        }

        // Bind timeframe buttons
        document.querySelectorAll('.futures-timeframe-btn').forEach(function (btn) {
            btn.addEventListener('click', function () {
                document.querySelectorAll('.futures-timeframe-btn').forEach(function (b) {
                    b.style.background = 'white'; b.style.color = '#666'; b.style.borderColor = '#ddd';
                });
                btn.style.background = '#4caf50'; btn.style.color = 'white'; btn.style.borderColor = '#4caf50';
                var empVal = document.getElementById('futuresEmployeeSelect')?.value || '__all__';
                renderFuturesTable(data, empVal, btn.dataset.timeframe);
            });
        });

        // Initial render
        renderFuturesTable(data, '__all__', 'weekly');
    }

    function renderFuturesTable(data, selectedEmployee, timeframe) {
        timeframe = timeframe || 'weekly';
        var tableContainer = document.getElementById('futuresTableContainer');
        if (!tableContainer) return;

        var employees = selectedEmployee === '__all__'
            ? data.employees
            : data.employees.filter(function (e) { return e.name === selectedEmployee; });

        if (employees.length === 0) {
            tableContainer.innerHTML = '<p style="color: var(--text-tertiary); text-align: center;">No data for selected employee.</p>';
            return;
        }

        var html = '';

        employees.forEach(function (emp) {
            html += '<div style="margin-bottom: 24px; padding: 20px; background: var(--bg-surface); border-radius: 8px; border: 1px solid var(--border); box-shadow: 0 1px 3px rgba(0,0,0,0.08);">';
            html += '<div style="display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #4caf50; padding-bottom: 8px; margin-bottom: 0;">';
            html += '<h3 style="margin: 0; color: var(--text-primary);">' + _escapeHtml(emp.name) + '</h3>';
            html += '<button type="button" class="futures-checkin-btn" data-employee="' + _escapeHtml(emp.name) + '" style="padding: 6px 16px; background: #1565c0; color: white; border: none; border-radius: 6px; cursor: pointer; font-weight: bold; font-size: 0.85em; white-space: nowrap;">Check-In Summary</button>';
            html += '</div>';

            if (emp.dataSource) {
                html += '<p style="margin: 0 0 12px 0; color: var(--text-secondary); font-size: 0.85em;">Source: ' + _escapeHtml(emp.dataSource) + '</p>';
            }

            // Table
            html += '<div style="overflow-x: auto;">';
            html += '<table style="width: 100%; border-collapse: collapse; font-size: 0.9em;">';
            html += '<thead><tr style="background: var(--bg-surface-raised);">';
            html += '<th style="padding: 10px 8px; text-align: left; border-bottom: 2px solid var(--border);">Metric</th>';
            html += '<th style="padding: 10px 8px; text-align: center; border-bottom: 2px solid var(--border);">YTD</th>';
            html += '<th style="padding: 10px 8px; text-align: center; border-bottom: 2px solid var(--border);">Target</th>';
            html += '<th style="padding: 10px 8px; text-align: center; border-bottom: 2px solid var(--border);">Status</th>';
            var tfLabel = timeframe === 'daily' ? 'Avg/Day' : timeframe === 'monthly' ? 'Avg/Month' : 'Avg/Week';
            html += '<th style="padding: 10px 8px; text-align: center; border-bottom: 2px solid var(--border); background: var(--green-soft);">Meet (' + tfLabel + ')</th>';
            html += '<th style="padding: 10px 8px; text-align: center; border-bottom: 2px solid var(--border); background: #e3f2fd;">Exceed (' + tfLabel + ')</th>';
            html += '</tr></thead><tbody>';

            var metricKeys = Object.keys(emp.metrics);
            if (metricKeys.length === 0) {
                html += '<tr><td colspan="6" style="padding: 15px; text-align: center; color: var(--text-tertiary);">No metric data available</td></tr>';
            }

            metricKeys.forEach(function (metricKey) {
                var m = emp.metrics[metricKey];
                var metric = window.METRICS_REGISTRY[metricKey];
                if (!metric) return;

                var icon = metric.icon || '';
                var label = metric.label || metricKey;

                // Row background based on status
                var rowBg = m.currentlyMeeting ? '#f1f8e9' : '#fff3e0';
                if (m.currentlyExceeding) rowBg = '#e8f5e9';

                html += '<tr style="background: ' + rowBg + '; border-bottom: 1px solid var(--border);">';

                // Metric name
                html += '<td style="padding: 8px; font-weight: 500;">' + icon + ' ' + _escapeHtml(label) + '</td>';

                // Current YTD value
                html += '<td style="padding: 8px; text-align: center; font-weight: bold;">' + _formatMetricDisplay(metricKey, m.currentAvg) + '</td>';

                // Target
                html += '<td style="padding: 8px; text-align: center; color: var(--text-secondary);">' + _formatMetricDisplay(metricKey, m.meetTarget) + '</td>';

                // Status badge
                var statusText, statusColor;
                if (m.currentlyExceeding) {
                    statusText = 'Exceeding';
                    statusColor = '#2e7d32';
                } else if (m.currentlyMeeting) {
                    statusText = 'Meeting';
                    statusColor = '#f57f17';
                } else {
                    statusText = 'Below';
                    statusColor = '#c62828';
                }
                html += '<td style="padding: 8px; text-align: center;"><span style="display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 0.85em; font-weight: bold; color: white; background: ' + statusColor + ';">' + statusText + '</span></td>';

                // Timeframe divisor for cumulative budgets
                var weeksLeft = data.weekInfo.weeksRemaining;
                var tfDivisor = timeframe === 'daily' ? (weeksLeft * 5) : timeframe === 'monthly' ? (weeksLeft / 4.33) : weeksLeft;
                var tfSuffix = timeframe === 'daily' ? '/day' : timeframe === 'monthly' ? '/mo' : '/wk';

                // Required to meet
                html += '<td style="padding: 8px; text-align: center; background: rgba(232,245,233,0.3);">';
                if (m.isCumulative) {
                    if (m.currentlyMeeting) {
                        var meetBudgetPer = tfDivisor > 0 ? m.budgetRemaining / tfDivisor : 0;
                        html += '<span style="color: var(--green-text); font-weight: bold;">' + _formatMetricDisplay(metricKey, meetBudgetPer) + tfSuffix + ' left</span>';
                    } else {
                        html += '<span style="color: var(--red-text); font-weight: bold;">Over by ' + _formatMetricDisplay(metricKey, Math.abs(m.budgetRemaining)) + '</span>';
                    }
                } else if (m.currentlyMeeting) {
                    html += '<span style="color: var(--green-text); font-weight: bold;">On track</span>';
                } else if (m.requiredToMeet !== null && m.meetAchievable) {
                    html += '<span style="color: #e65100; font-weight: bold;">' + _formatMetricDisplay(metricKey, m.requiredToMeet) + tfSuffix + '</span>';
                } else if (m.requiredToMeet !== null && !m.meetAchievable) {
                    html += '<span style="color: var(--red-text); font-size: 0.85em;">Not achievable</span>';
                } else {
                    html += '<span style="color: var(--text-tertiary);">N/A</span>';
                }
                html += '</td>';

                // Required to exceed
                html += '<td style="padding: 8px; text-align: center; background: rgba(227,242,253,0.3);">';
                if (!m.hasExceedBand) {
                    html += '<span style="color: var(--text-tertiary); font-size: 0.85em;">No band</span>';
                } else if (m.isCumulative) {
                    if (m.currentlyExceeding) {
                        var excBudgetPer = tfDivisor > 0 ? m.exceedBudgetRemaining / tfDivisor : 0;
                        html += '<span style="color: #1565c0; font-weight: bold;">' + _formatMetricDisplay(metricKey, excBudgetPer) + tfSuffix + ' left</span>';
                    } else {
                        html += '<span style="color: var(--red-text); font-weight: bold;">Over by ' + _formatMetricDisplay(metricKey, Math.abs(m.exceedBudgetRemaining)) + '</span>';
                    }
                } else if (m.currentlyExceeding) {
                    html += '<span style="color: #1565c0; font-weight: bold;">On track</span>';
                } else if (m.requiredToExceed !== null && m.exceedAchievable) {
                    html += '<span style="color: #1565c0; font-weight: bold;">' + _formatMetricDisplay(metricKey, m.requiredToExceed) + tfSuffix + '</span>';
                } else if (m.requiredToExceed !== null && !m.exceedAchievable) {
                    html += '<span style="color: var(--red-text); font-size: 0.85em;">Not achievable</span>';
                } else {
                    html += '<span style="color: var(--text-tertiary);">N/A</span>';
                }
                html += '</td>';

                html += '</tr>';
            });

            html += '</tbody></table>';
            html += '</div>';

            // Summary callout
            var meetingCount = 0;
            var exceedingCount = 0;
            var belowCount = 0;
            var notAchievableCount = 0;
            metricKeys.forEach(function (mk) {
                var mm = emp.metrics[mk];
                if (mm.currentlyExceeding) exceedingCount++;
                else if (mm.currentlyMeeting) meetingCount++;
                else {
                    belowCount++;
                    if (!mm.isCumulative && mm.requiredToMeet !== null && !mm.meetAchievable) notAchievableCount++;
                }
            });

            html += '<div style="margin-top: 12px; display: flex; gap: 12px; flex-wrap: wrap;">';
            if (exceedingCount > 0) {
                html += '<span style="padding: 6px 14px; border-radius: 16px; background: var(--green-soft); color: var(--green-text); font-weight: bold; font-size: 0.9em;">' + exceedingCount + ' Exceeding</span>';
            }
            if (meetingCount > 0) {
                html += '<span style="padding: 6px 14px; border-radius: 16px; background: #fff8e1; color: #f57f17; font-weight: bold; font-size: 0.9em;">' + meetingCount + ' Meeting</span>';
            }
            if (belowCount > 0) {
                html += '<span style="padding: 6px 14px; border-radius: 16px; background: #fbe9e7; color: var(--red-text); font-weight: bold; font-size: 0.9em;">' + belowCount + ' Below</span>';
            }
            if (notAchievableCount > 0) {
                html += '<span style="padding: 6px 14px; border-radius: 16px; background: #f8d7da; color: #721c24; font-weight: bold; font-size: 0.9em;">' + notAchievableCount + ' Not Achievable</span>';
            }
            html += '</div>';

            html += '</div>';
        });

        tableContainer.innerHTML = html;

        // Bind check-in buttons
        tableContainer.querySelectorAll('.futures-checkin-btn').forEach(function (btn) {
            btn.addEventListener('click', function () {
                var empName = btn.dataset.employee;
                showCheckInModal(empName, data);
            });
        });
    }

    /* ── Check-In Summary ── */

    /**
     * Count working days (Mon-Fri) between two dates (exclusive of start, inclusive of end).
     */
    function countWorkingDays(startDate, endDate) {
        var count = 0;
        var current = new Date(startDate.getFullYear(), startDate.getMonth(), startDate.getDate());
        current.setDate(current.getDate() + 1); // start from next day
        var end = new Date(endDate.getFullYear(), endDate.getMonth(), endDate.getDate());
        while (current <= end) {
            var dow = current.getDay();
            if (dow !== 0 && dow !== 6) count++;
            current.setDate(current.getDate() + 1);
        }
        return count;
    }

    /**
     * Get number of working days remaining in the performance period.
     * Performance period ends October 31 of the current year.
     */
    function getWorkingDaysRemaining() {
        var now = new Date();
        var endDate = new Date(now.getFullYear(), 9, 31); // Oct 31
        if (now > endDate) return 0;
        return countWorkingDays(now, endDate);
    }

    /**
     * The figure the check-in summary quotes as a daily aim.
     *
     * This used to hold its own copy of the required-average formula, identical
     * line for line to calculateRequiredAverage, which meant the table and the
     * check-in could be given different weights and print different numbers for
     * the same person on the same day. The name is kept because that is what the
     * check-in asks for, but the arithmetic now lives in exactly one place.
     *
     * Note it returns the required AVERAGE for the rest of the year, not a value
     * divided across working days. That was always true, despite the old comment
     * claiming a conversion; an average is in fact the right thing for the
     * check-in to quote, because "hold at or above this each day" is how a person
     * hits an average.
     */
    function calculateDailyTarget(currentAvg, weeksCompleted, weeksRemaining, target, volume) {
        return calculateRequiredAverage(currentAvg, weeksCompleted, weeksRemaining, target, volume);
    }

    /**
     * Build an employee-friendly check-in summary.
     * Uses "next level" language — no score numbers, no goal values, no end dates.
     */
    function buildCheckInSummary(empName, data) {
        var emp = null;
        for (var i = 0; i < data.employees.length; i++) {
            if (data.employees[i].name === empName) { emp = data.employees[i]; break; }
        }
        if (!emp) return 'No data available for ' + empName + '.';

        var weekInfo = data.weekInfo;
        var workingDaysLeft = getWorkingDaysRemaining();
        var ratingBands = window.DevCoachModules?.metricProfiles?.RATING_BANDS_BY_YEAR?.[weekInfo.currentYear] || {};

        var lines = [];
        lines.push('Performance Check-In: ' + empName);
        lines.push('');

        var greatMetrics = [];
        var improvementMetrics = [];

        var metricKeys = Object.keys(emp.metrics);
        metricKeys.forEach(function (metricKey) {
            // Skip reliability — not shared with employees in check-ins
            if (metricKey === 'reliability') return;

            var m = emp.metrics[metricKey];
            var metric = window.METRICS_REGISTRY[metricKey];
            if (!metric) return;

            var label = metric.label || metricKey;
            var bandConfig = ratingBands[metricKey];

            // Determine current score level
            var score = null;
            if (bandConfig) {
                if (bandConfig.type === 'min') {
                    if (m.currentAvg >= bandConfig.score3.min) score = 3;
                    else if (m.currentAvg >= bandConfig.score2.min) score = 2;
                    else score = 1;
                } else {
                    if (m.currentAvg <= bandConfig.score3.max) score = 3;
                    else if (m.currentAvg <= bandConfig.score2.max) score = 2;
                    else score = 1;
                }
            } else {
                // No rating band — use meet/exceed status
                if (m.currentlyExceeding) score = 3;
                else if (m.currentlyMeeting) score = 2;
                else score = 1;
            }

            if (score === 3) {
                greatMetrics.push({ label: label, currentAvg: m.currentAvg, metricKey: metricKey });
                return;
            }

            // Figure out the next level target
            var nextTarget = null;
            var levelLabel = 'next level';
            if (bandConfig) {
                if (score === 1) {
                    nextTarget = bandConfig.type === 'min' ? bandConfig.score2.min : bandConfig.score2.max;
                } else if (score === 2) {
                    nextTarget = bandConfig.type === 'min' ? bandConfig.score3.min : bandConfig.score3.max;
                    levelLabel = 'top level';
                }
            } else {
                nextTarget = score === 1 ? m.meetTarget : m.exceedTarget;
                if (score === 2) levelLabel = 'top level';
            }

            if (nextTarget === null) return;

            // Calculate required daily average
            var dailyTarget = null;
            if (!m.isCumulative) {
                var requiredAvg = calculateDailyTarget(m.currentAvg, weekInfo.weeksCompleted, weekInfo.weeksRemaining, nextTarget, m.volume);
                if (requiredAvg !== null && isAchievable(metricKey, requiredAvg)) {
                    dailyTarget = requiredAvg;
                }
            }

            improvementMetrics.push({
                label: label,
                metricKey: metricKey,
                currentAvg: m.currentAvg,
                nextTarget: nextTarget,
                dailyTarget: dailyTarget,
                levelLabel: levelLabel,
                isCumulative: m.isCumulative,
                isReverse: m.isReverse,
                budgetRemaining: m.budgetRemaining,
                achievable: dailyTarget !== null || m.isCumulative
            });
        });

        // Great metrics section
        if (greatMetrics.length > 0) {
            lines.push('DOING GREAT:');
            greatMetrics.forEach(function (gm) {
                lines.push('  ' + gm.label + ': ' + _formatMetricDisplay(gm.metricKey, gm.currentAvg) + ' — Top level! Keep it up.');
            });
            lines.push('');
        }

        // Improvement metrics section
        if (improvementMetrics.length > 0) {
            lines.push('AREAS TO FOCUS ON:');
            improvementMetrics.forEach(function (im) {
                var current = _formatMetricDisplay(im.metricKey, im.currentAvg);
                if (im.isCumulative) {
                    if (im.budgetRemaining > 0) {
                        var perDay = workingDaysLeft > 0 ? im.budgetRemaining / workingDaysLeft : 0;
                        lines.push('  ' + im.label + ': Currently at ' + current + '. You have ' + _formatMetricDisplay(im.metricKey, im.budgetRemaining) + ' remaining to stay within budget.');
                    } else {
                        lines.push('  ' + im.label + ': Currently at ' + current + '. Over budget — minimize further usage.');
                    }
                } else if (im.dailyTarget !== null) {
                    var targetDisplay = _formatMetricDisplay(im.metricKey, im.dailyTarget);
                    var direction = im.isReverse ? 'at or below' : 'at or above';
                    lines.push('  ' + im.label + ': Currently at ' + current + '. To reach the ' + im.levelLabel + ', aim for ' + direction + ' ' + targetDisplay + ' each day.');
                } else {
                    lines.push('  ' + im.label + ': Currently at ' + current + '. This one will be tough to move — stay consistent and do your best.');
                }
            });
            lines.push('');
        }

        if (improvementMetrics.length === 0 && greatMetrics.length > 0) {
            lines.push('All metrics are at the top level — outstanding work!');
            lines.push('');
        }

        lines.push('Keep pushing — every day counts!');

        return lines.join('\n');
    }

    /**
     * Show the check-in summary in a modal.
     */
    function showCheckInModal(empName, data) {
        var summary = buildCheckInSummary(empName, data);

        // Remove existing modal if any
        var existing = document.getElementById('futuresCheckInModal');
        if (existing) existing.remove();

        var overlay = document.createElement('div');
        overlay.id = 'futuresCheckInModal';
        overlay.className = 'modal-overlay';
        overlay.style.display = 'flex';

        var content = document.createElement('div');
        content.className = 'modal-content';
        content.innerHTML =
            '<div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px;">' +
                '<h3 style="margin: 0; color: var(--text-primary);">Check-In Summary</h3>' +
                '<button id="futuresCheckInClose" style="background: none; border: none; font-size: 1.5em; cursor: pointer; color: var(--text-secondary); padding: 0 4px;">&times;</button>' +
            '</div>' +
            '<pre id="futuresCheckInText" style="white-space: pre-wrap; font-family: Segoe UI, sans-serif; font-size: 0.92em; line-height: 1.6; background: var(--bg-surface-raised); padding: 16px; border-radius: 6px; border: 1px solid var(--border); max-height: 60vh; overflow-y: auto;">' + _escapeHtml(summary) + '</pre>' +
            '<div style="margin-top: 16px; display: flex; gap: 10px;">' +
                '<button id="futuresCheckInCopy" style="padding: 10px 20px; background: #4caf50; color: white; border: none; border-radius: 6px; cursor: pointer; font-weight: bold; font-size: 0.95em;">Copy to Clipboard</button>' +
            '</div>';

        overlay.appendChild(content);
        document.body.appendChild(overlay);

        // Close handlers
        document.getElementById('futuresCheckInClose').addEventListener('click', function () { overlay.remove(); });
        overlay.addEventListener('click', function (e) { if (e.target === overlay) overlay.remove(); });

        // Copy handler
        document.getElementById('futuresCheckInCopy').addEventListener('click', function () {
            copyToClipboard(summary, { button: document.getElementById('futuresCheckInCopy') });
        });
    }

    /* ── Module export ── */
    window.DevCoachModules = window.DevCoachModules || {};
    window.DevCoachModules.futures = {
        renderFutures: renderFutures,
        buildFuturesData: buildFuturesData,
        buildCheckInSummary: buildCheckInSummary,
        showCheckInModal: showCheckInModal,
        // Exported for the projection tests. These are the pieces that decide
        // what a person is told they have to do for the rest of the year, and
        // they are worth pinning down without a DOM in the way.
        calculateRequiredAverage: calculateRequiredAverage,
        calculateDailyTarget: calculateDailyTarget,
        weeksCompletedThroughDate: weeksCompletedThroughDate,
        estimateWeekCounts: estimateWeekCounts,
        findRealYtdUpload: findRealYtdUpload,
        weeklyVolumeRates: weeklyVolumeRates,
        projectedVolume: projectedVolume,
        // Exported for the same reason as the rest: the shape of the row it hands
        // back is what decides whether a metric gets weighted at all, and a
        // dropped column there is invisible from every screen.
        aggregateFromWeeklyData: aggregateFromWeeklyData
    };

    window.renderFutures = renderFutures;
})();
