(function () {
    'use strict';

    /* ── Global helpers accessed via window ── */
    function _getWeeklyData() {
        return typeof weeklyData !== 'undefined' ? weeklyData : {};
    }
    function _getYtdData() {
        return typeof ytdData !== 'undefined' ? ytdData : {};
    }
    function _getWeeklyKeysSorted() {
        return typeof window.getWeeklyKeysSorted === 'function' ? window.getWeeklyKeysSorted() : Object.keys(_getWeeklyData());
    }
    function _getTeamMembersForWeek(weekKey) {
        return typeof window.getTeamMembersForWeek === 'function' ? window.getTeamMembersForWeek(weekKey) : [];
    }
    function _formatMetricDisplay(key, value) {
        return typeof window.formatMetricDisplay === 'function' ? window.formatMetricDisplay(key, value) : String(value);
    }
    function _escapeHtml(str) {
        var mod = window.DevCoachModules?.sharedUtils;
        if (mod?.escapeHtml) return mod.escapeHtml(str);
        return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    }

    // Metrics to project (the meaningful ones with targets)
    var FUTURES_METRICS = [
        'scheduleAdherence', 'cxRepOverall', 'fcr', 'overallExperience',
        'transfers', 'overallSentiment', 'positiveWord', 'negativeWord',
        'managingEmotions', 'aht', 'acw', 'holdTime', 'reliability'
    ];

    // Cumulative metrics are summed across periods, not averaged.
    // The "need to average" projection doesn't apply — it's "budget remaining".
    var CUMULATIVE_METRICS = new Set(['reliability']);

    /**
     * Find the most recent real (non-auto) YTD upload for a year.
     * Returns { employees, source } or null.
     */
    function findRealYtdUpload(year) {
        var ytd = _getYtdData();
        var best = null;
        var bestDate = 0;

        Object.keys(ytd).forEach(function (key) {
            var period = ytd[key];
            var meta = period?.metadata || {};
            if (meta.autoGeneratedYtd) return; // skip auto-generated
            if (meta.periodType !== 'ytd') return;
            var endStr = meta.endDate || (key.includes('|') ? key.split('|')[1] : '');
            var endDate = endStr ? new Date(endStr) : null;
            if (!endDate || isNaN(endDate) || endDate.getFullYear() !== year) return;
            if (endDate.getTime() > bestDate) {
                best = period;
                bestDate = endDate.getTime();
            }
        });

        if (best && best.employees) {
            return {
                employees: best.employees,
                source: best.metadata?.label || 'YTD upload'
            };
        }
        return null;
    }

    /**
     * Estimate total weeks in the year and weeks completed based on uploaded data
     */
    function estimateWeekCounts() {
        var currentYear = new Date().getFullYear();
        var keys = _getWeeklyKeysSorted();
        var yearKeys = keys.filter(function (k) {
            var endStr = k.split('|')[1] || '';
            return parseInt(endStr.split('-')[0], 10) === currentYear;
        });

        var weeksCompleted = yearKeys.length;
        var totalWeeks = 52;
        var weeksRemaining = Math.max(0, totalWeeks - weeksCompleted);

        return {
            currentYear: currentYear,
            weeksCompleted: weeksCompleted,
            totalWeeks: totalWeeks,
            weeksRemaining: weeksRemaining,
            yearKeys: yearKeys
        };
    }

    // Metrics that should be weighted by surveyTotal instead of totalCalls
    var SURVEY_WEIGHTED = new Set(['cxRepOverall', 'fcr', 'overallExperience']);

    // Rate metrics that get weighted-averaged (matches buildYtdAggregateForYear)
    var RATE_METRICS = new Set([
        'scheduleAdherence', 'transfers', 'cxRepOverall', 'fcr', 'overallExperience',
        'aht', 'talkTime', 'acw', 'holdTime', 'overallSentiment', 'managingEmotions',
        'negativeWord', 'positiveWord'
    ]);

    /**
     * Aggregate YTD values directly from weekly data uploads.
     * Uses the same rules as buildYtdAggregateForYear but WITHOUT the
     * anchor pattern, so it always reflects the actual weekly uploads.
     *
     * - Rate metrics: weighted average (by totalCalls or surveyTotal)
     * - Cumulative metrics (reliability): summed
     */
    function aggregateFromWeeklyData(yearKeys) {
        var wData = _getWeeklyData();

        // Filter to one source type to avoid double-counting overlapping periods
        // (e.g., weekly + monthly/quarterly covering the same timeframe).
        // Matches buildYtdAggregateForYear's sourceTypePriority logic.
        var sourceTypePriority = ['week', 'month', 'quarter', 'custom', 'daily'];
        var periodsByType = {};
        yearKeys.forEach(function (weekKey) {
            var period = wData[weekKey];
            if (!period) return;
            var pType = period.metadata?.periodType || 'week';
            if (!periodsByType[pType]) periodsByType[pType] = [];
            periodsByType[pType].push(weekKey);
        });

        var chosenType = null;
        for (var i = 0; i < sourceTypePriority.length; i++) {
            if (periodsByType[sourceTypePriority[i]] && periodsByType[sourceTypePriority[i]].length > 0) {
                chosenType = sourceTypePriority[i];
                break;
            }
        }
        var filteredKeys = chosenType ? periodsByType[chosenType] : yearKeys;

        var empAgg = {}; // { name: { totalCalls, surveyTotal, reliability, weightedSums, weightedCounts } }

        filteredKeys.forEach(function (weekKey) {
            var period = wData[weekKey];
            if (!period || !period.employees) return;

            period.employees.forEach(function (emp) {
                if (!emp || !emp.name) return;

                if (!empAgg[emp.name]) {
                    empAgg[emp.name] = {
                        name: emp.name,
                        totalCalls: 0,
                        surveyTotal: 0,
                        reliability: 0,
                        weightedSums: {},
                        weightedCounts: {}
                    };
                }

                var agg = empAgg[emp.name];
                var tc = parseInt(emp.totalCalls, 10);
                var st = parseInt(emp.surveyTotal, 10);

                agg.totalCalls += Number.isInteger(tc) ? tc : 0;
                agg.surveyTotal += Number.isInteger(st) ? st : 0;

                // Reliability: cumulative hours — take the highest (most complete) value
                var rel = parseFloat(emp.reliability);
                if (Number.isFinite(rel) && rel > agg.reliability) agg.reliability = rel;

                // Rate metrics: accumulate weighted sums
                RATE_METRICS.forEach(function (mk) {
                    var val = parseFloat(emp[mk]);
                    if (!Number.isFinite(val)) return;

                    var weight = 1;
                    if (SURVEY_WEIGHTED.has(mk)) {
                        weight = Number.isInteger(st) && st > 0 ? st : 0;
                    } else {
                        weight = Number.isInteger(tc) && tc > 0 ? tc : 1;
                    }
                    if (weight <= 0) return;

                    agg.weightedSums[mk] = (agg.weightedSums[mk] || 0) + (val * weight);
                    agg.weightedCounts[mk] = (agg.weightedCounts[mk] || 0) + weight;
                });
            });
        });

        // Finalize: compute weighted averages
        var employees = [];
        Object.keys(empAgg).forEach(function (name) {
            var agg = empAgg[name];
            var result = { name: name, reliability: agg.reliability, totalCalls: agg.totalCalls };

            RATE_METRICS.forEach(function (mk) {
                var totalWeight = agg.weightedCounts[mk] || 0;
                if (totalWeight > 0) {
                    result[mk] = agg.weightedSums[mk] / totalWeight;
                }
            });

            employees.push(result);
        });

        var sourceLabel = filteredKeys.length + ' ' + (chosenType || 'period') + (filteredKeys.length !== 1 ? 's' : '') + ' aggregated';
        return employees.length > 0
            ? { employees: employees, source: sourceLabel, periodCount: filteredKeys.length, periodType: chosenType }
            : null;
    }

    /**
     * Calculate what an employee needs to average for the rest of the year
     * to hit a specific target (for rate/averaged metrics only).
     */
    function calculateRequiredAverage(currentAvg, weeksCompleted, weeksRemaining, target) {
        if (weeksRemaining <= 0) return null;
        var totalNeeded = target * (weeksCompleted + weeksRemaining);
        var currentTotal = currentAvg * weeksCompleted;
        var required = (totalNeeded - currentTotal) / weeksRemaining;
        return required;
    }

    /**
     * Determine if a required average is achievable
     */
    function isAchievable(metricKey, requiredAvg) {
        var metric = window.METRICS_REGISTRY[metricKey];
        if (!metric) return true;
        if (requiredAvg < 0) return false;
        if (metric.unit === '%' && requiredAvg > 100) return false;
        return true;
    }

    /**
     * Build futures projection data for all team members
     */
    function buildFuturesData() {
        var weekInfo = estimateWeekCounts();
        var currentYear = weekInfo.currentYear;
        var wData = _getWeeklyData();
        var latestKey = weekInfo.yearKeys.length > 0 ? weekInfo.yearKeys[weekInfo.yearKeys.length - 1] : null;

        // Get team members from latest period (weekly or YTD)
        var teamMembers = [];
        var teamSourcePeriod = latestKey && wData[latestKey] ? wData[latestKey] : null;

        // Fall back to YTD data if no weekly data
        if (!teamSourcePeriod) {
            var yData = _getYtdData();
            var bestYtdKey = null;
            var bestYtdDate = 0;
            Object.keys(yData).forEach(function (k) {
                var meta = yData[k]?.metadata || {};
                var endStr = meta.endDate || (k.includes('|') ? k.split('|')[1] : '');
                var endYear = parseInt(String(endStr).split('-')[0], 10);
                if (endYear !== currentYear) return;
                var d = new Date(endStr);
                if (!isNaN(d) && d.getTime() > bestYtdDate) {
                    bestYtdDate = d.getTime();
                    bestYtdKey = k;
                }
            });
            if (bestYtdKey) {
                teamSourcePeriod = yData[bestYtdKey];
                latestKey = bestYtdKey;
            }
        }

        if (teamSourcePeriod) {
            var teamFilter = window.DevCoachModules?.teamFilter;
            var filterKey = latestKey;
            if (teamFilter?.getTeamSelectionContext) {
                var ctx = teamFilter.getTeamSelectionContext();
                if (ctx.weekKey) filterKey = ctx.weekKey;
            }
            var members = _getTeamMembersForWeek(filterKey);
            var allEmps = (teamSourcePeriod.employees || []).map(function (e) { return e.name; });
            teamMembers = members.length > 0 ? allEmps.filter(function (n) { return members.includes(n); }) : allEmps;
        }
        // Sort alphabetically by first name
        teamMembers.sort(function (a, b) {
            var aFirst = (a || '').split(/[\s,]+/)[0].toLowerCase();
            var bFirst = (b || '').split(/[\s,]+/)[0].toLowerCase();
            return aFirst.localeCompare(bFirst);
        });

        // Primary: use real YTD upload if available (source of truth)
        var ytdEmployees = [];
        var ytdSource = '';
        var realYtd = findRealYtdUpload(currentYear);
        if (realYtd) {
            ytdEmployees = realYtd.employees;
            ytdSource = realYtd.source;
        } else {
            // Fallback: aggregate from weekly data when no YTD upload exists
            var weeklyAgg = aggregateFromWeeklyData(weekInfo.yearKeys);
            if (weeklyAgg) {
                ytdEmployees = weeklyAgg.employees;
                ytdSource = weeklyAgg.source;
                if (weeklyAgg.periodCount) {
                    weekInfo.weeksCompleted = weeklyAgg.periodCount;
                    weekInfo.weeksRemaining = Math.max(0, weekInfo.totalWeeks - weekInfo.weeksCompleted);
                }
            }
        }

        var targets = window.DevCoachModules?.metricProfiles?.TARGETS_BY_YEAR?.[currentYear] || {};
        var ratingBands = window.DevCoachModules?.metricProfiles?.RATING_BANDS_BY_YEAR?.[currentYear] || {};

        var results = [];
        teamMembers.forEach(function (empName) {
            // Find this employee in the aggregated YTD data
            var ytdEmp = null;
            for (var i = 0; i < ytdEmployees.length; i++) {
                if (ytdEmployees[i].name === empName) {
                    ytdEmp = ytdEmployees[i];
                    break;
                }
            }
            if (!ytdEmp) return;

            var empResult = {
                name: empName,
                dataSource: ytdSource,
                metrics: {}
            };

            FUTURES_METRICS.forEach(function (metricKey) {
                var targetConfig = targets[metricKey];
                if (!targetConfig) return;

                var val = parseFloat(ytdEmp[metricKey]);
                if (isNaN(val)) return;

                var currentValue = val;
                var meetTarget = targetConfig.value;
                var isReverse = targetConfig.type === 'max';
                var isCumulative = CUMULATIVE_METRICS.has(metricKey);

                // Determine "exceed" target from rating bands (score 3)
                var exceedTarget = meetTarget;
                var bandConfig = ratingBands[metricKey];
                if (bandConfig) {
                    exceedTarget = isReverse ? bandConfig.score3.max : bandConfig.score3.min;
                }

                var requiredToMeet = null;
                var requiredToExceed = null;
                var meetAchievable = null;
                var exceedAchievable = null;
                var currentlyMeeting, currentlyExceeding;
                var budgetRemaining = null;
                var exceedBudgetRemaining = null;

                if (isCumulative) {
                    // Cumulative metrics (reliability): compare total used vs annual max
                    currentlyMeeting = currentValue <= meetTarget;
                    currentlyExceeding = bandConfig
                        ? (currentValue <= exceedTarget)
                        : currentlyMeeting;
                    budgetRemaining = meetTarget - currentValue;
                    exceedBudgetRemaining = bandConfig ? exceedTarget - currentValue : null;
                } else {
                    // Rate metrics: use weighted average projection
                    currentlyMeeting = isReverse ? (currentValue <= meetTarget) : (currentValue >= meetTarget);
                    currentlyExceeding = bandConfig
                        ? (isReverse ? (currentValue <= exceedTarget) : (currentValue >= exceedTarget))
                        : currentlyMeeting;

                    requiredToMeet = calculateRequiredAverage(currentValue, weekInfo.weeksCompleted, weekInfo.weeksRemaining, meetTarget);
                    requiredToExceed = calculateRequiredAverage(currentValue, weekInfo.weeksCompleted, weekInfo.weeksRemaining, exceedTarget);
                    meetAchievable = requiredToMeet !== null ? isAchievable(metricKey, requiredToMeet) : null;
                    exceedAchievable = requiredToExceed !== null ? isAchievable(metricKey, requiredToExceed) : null;
                }

                empResult.metrics[metricKey] = {
                    currentAvg: currentValue,
                    meetTarget: meetTarget,
                    exceedTarget: exceedTarget,
                    requiredToMeet: requiredToMeet,
                    requiredToExceed: requiredToExceed,
                    meetAchievable: meetAchievable,
                    exceedAchievable: exceedAchievable,
                    currentlyMeeting: currentlyMeeting,
                    currentlyExceeding: currentlyExceeding,
                    isReverse: isReverse,
                    hasExceedBand: !!bandConfig,
                    isCumulative: isCumulative,
                    budgetRemaining: budgetRemaining,
                    exceedBudgetRemaining: exceedBudgetRemaining
                };
            });

            results.push(empResult);
        });

        return {
            weekInfo: weekInfo,
            employees: results
        };
    }

    /**
     * Render the futures projection table
     */
    function renderFutures() {
        var container = document.getElementById('futuresContent');
        if (!container) return;

        var data = buildFuturesData();
        var weekInfo = data.weekInfo;

        if (data.employees.length === 0) {
            container.innerHTML = '<p style="color: #94a3b8; text-align: center; padding: 40px;">No data available. Upload data to see projections.</p>';
            return;
        }

        var html = '';

        // Summary header
        html += '<div style="margin-bottom: 20px; padding: 15px; background: #e8f5e9; border-radius: 8px; border-left: 4px solid #4caf50;">';
        html += '<strong>Year Progress:</strong> ' + weekInfo.weeksCompleted + ' weeks completed, ' + weekInfo.weeksRemaining + ' weeks remaining in ' + weekInfo.currentYear;
        html += '</div>';

        // Employee selector
        html += '<div style="margin-bottom: 20px; padding: 15px; background: #fff; border-radius: 8px; border: 1px solid #ddd;">';
        html += '<label for="futuresEmployeeSelect" style="font-weight: bold; display: block; margin-bottom: 8px;">Select Associate:</label>';
        html += '<select id="futuresEmployeeSelect" style="width: 100%; padding: 8px; border: 1px solid #ddd; border-radius: 4px; font-size: 1em; cursor: pointer;">';
        html += '<option value="__all__">All Team Members</option>';
        data.employees.forEach(function (emp) {
            html += '<option value="' + _escapeHtml(emp.name) + '">' + _escapeHtml(emp.name) + '</option>';
        });
        html += '</select>';
        html += '</div>';

        // Timeframe toggle
        html += '<div style="margin-bottom: 20px; padding: 15px; background: #fff; border-radius: 8px; border: 1px solid #ddd;">';
        html += '<label style="font-weight: bold; display: block; margin-bottom: 8px;">Show targets as:</label>';
        html += '<div style="display: flex; gap: 8px;">';
        ['Daily', 'Weekly', 'Monthly'].forEach(function (label) {
            var val = label.toLowerCase();
            var isDefault = val === 'weekly';
            html += '<button type="button" class="futures-timeframe-btn" data-timeframe="' + val + '" style="padding: 8px 18px; border: 2px solid ' + (isDefault ? '#4caf50' : '#ddd') + '; background: ' + (isDefault ? '#4caf50' : 'white') + '; color: ' + (isDefault ? 'white' : '#666') + '; border-radius: 4px; cursor: pointer; font-weight: bold;">' + label + '</button>';
        });
        html += '</div></div>';

        // Content area
        html += '<div id="futuresTableContainer"></div>';

        container.innerHTML = html;

        // Bind employee select
        var select = document.getElementById('futuresEmployeeSelect');
        if (select) {
            select.addEventListener('change', function () {
                var tf = document.querySelector('.futures-timeframe-btn[style*="background: rgb(76, 175, 80)"]')?.dataset?.timeframe || 'weekly';
                renderFuturesTable(data, select.value, tf);
            });
        }

        // Bind timeframe buttons
        document.querySelectorAll('.futures-timeframe-btn').forEach(function (btn) {
            btn.addEventListener('click', function () {
                document.querySelectorAll('.futures-timeframe-btn').forEach(function (b) {
                    b.style.background = 'white'; b.style.color = '#666'; b.style.borderColor = '#ddd';
                });
                btn.style.background = '#4caf50'; btn.style.color = 'white'; btn.style.borderColor = '#4caf50';
                var empVal = document.getElementById('futuresEmployeeSelect')?.value || '__all__';
                renderFuturesTable(data, empVal, btn.dataset.timeframe);
            });
        });

        // Initial render
        renderFuturesTable(data, '__all__', 'weekly');
    }

    function renderFuturesTable(data, selectedEmployee, timeframe) {
        timeframe = timeframe || 'weekly';
        var tableContainer = document.getElementById('futuresTableContainer');
        if (!tableContainer) return;

        var employees = selectedEmployee === '__all__'
            ? data.employees
            : data.employees.filter(function (e) { return e.name === selectedEmployee; });

        if (employees.length === 0) {
            tableContainer.innerHTML = '<p style="color: #94a3b8; text-align: center;">No data for selected employee.</p>';
            return;
        }

        var html = '';

        employees.forEach(function (emp) {
            html += '<div style="margin-bottom: 24px; padding: 20px; background: #fff; border-radius: 8px; border: 1px solid #ddd; box-shadow: 0 1px 3px rgba(0,0,0,0.08);">';
            html += '<div style="display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #4caf50; padding-bottom: 8px; margin-bottom: 0;">';
            html += '<h3 style="margin: 0; color: #1a1a2e;">' + _escapeHtml(emp.name) + '</h3>';
            html += '<button type="button" class="futures-checkin-btn" data-employee="' + _escapeHtml(emp.name) + '" style="padding: 6px 16px; background: #1565c0; color: white; border: none; border-radius: 6px; cursor: pointer; font-weight: bold; font-size: 0.85em; white-space: nowrap;">Check-In Summary</button>';
            html += '</div>';

            if (emp.dataSource) {
                html += '<p style="margin: 0 0 12px 0; color: #666; font-size: 0.85em;">Source: ' + _escapeHtml(emp.dataSource) + '</p>';
            }

            // Table
            html += '<div style="overflow-x: auto;">';
            html += '<table style="width: 100%; border-collapse: collapse; font-size: 0.9em;">';
            html += '<thead><tr style="background: #f5f5f5;">';
            html += '<th style="padding: 10px 8px; text-align: left; border-bottom: 2px solid #ddd;">Metric</th>';
            html += '<th style="padding: 10px 8px; text-align: center; border-bottom: 2px solid #ddd;">YTD</th>';
            html += '<th style="padding: 10px 8px; text-align: center; border-bottom: 2px solid #ddd;">Target</th>';
            html += '<th style="padding: 10px 8px; text-align: center; border-bottom: 2px solid #ddd;">Status</th>';
            var tfLabel = timeframe === 'daily' ? 'Avg/Day' : timeframe === 'monthly' ? 'Avg/Month' : 'Avg/Week';
            html += '<th style="padding: 10px 8px; text-align: center; border-bottom: 2px solid #ddd; background: #e8f5e9;">Meet (' + tfLabel + ')</th>';
            html += '<th style="padding: 10px 8px; text-align: center; border-bottom: 2px solid #ddd; background: #e3f2fd;">Exceed (' + tfLabel + ')</th>';
            html += '</tr></thead><tbody>';

            var metricKeys = Object.keys(emp.metrics);
            if (metricKeys.length === 0) {
                html += '<tr><td colspan="6" style="padding: 15px; text-align: center; color: #999;">No metric data available</td></tr>';
            }

            metricKeys.forEach(function (metricKey) {
                var m = emp.metrics[metricKey];
                var metric = window.METRICS_REGISTRY[metricKey];
                if (!metric) return;

                var icon = metric.icon || '';
                var label = metric.label || metricKey;

                // Row background based on status
                var rowBg = m.currentlyMeeting ? '#f1f8e9' : '#fff3e0';
                if (m.currentlyExceeding) rowBg = '#e8f5e9';

                html += '<tr style="background: ' + rowBg + '; border-bottom: 1px solid #eee;">';

                // Metric name
                html += '<td style="padding: 8px; font-weight: 500;">' + icon + ' ' + _escapeHtml(label) + '</td>';

                // Current YTD value
                html += '<td style="padding: 8px; text-align: center; font-weight: bold;">' + _formatMetricDisplay(metricKey, m.currentAvg) + '</td>';

                // Target
                html += '<td style="padding: 8px; text-align: center; color: #666;">' + _formatMetricDisplay(metricKey, m.meetTarget) + '</td>';

                // Status badge
                var statusText, statusColor;
                if (m.currentlyExceeding) {
                    statusText = 'Exceeding';
                    statusColor = '#2e7d32';
                } else if (m.currentlyMeeting) {
                    statusText = 'Meeting';
                    statusColor = '#f57f17';
                } else {
                    statusText = 'Below';
                    statusColor = '#c62828';
                }
                html += '<td style="padding: 8px; text-align: center;"><span style="display: inline-block; padding: 3px 10px; border-radius: 12px; font-size: 0.85em; font-weight: bold; color: white; background: ' + statusColor + ';">' + statusText + '</span></td>';

                // Timeframe divisor for cumulative budgets
                var weeksLeft = data.weekInfo.weeksRemaining;
                var tfDivisor = timeframe === 'daily' ? (weeksLeft * 5) : timeframe === 'monthly' ? (weeksLeft / 4.33) : weeksLeft;
                var tfSuffix = timeframe === 'daily' ? '/day' : timeframe === 'monthly' ? '/mo' : '/wk';

                // Required to meet
                html += '<td style="padding: 8px; text-align: center; background: rgba(232,245,233,0.3);">';
                if (m.isCumulative) {
                    if (m.currentlyMeeting) {
                        var meetBudgetPer = tfDivisor > 0 ? m.budgetRemaining / tfDivisor : 0;
                        html += '<span style="color: #2e7d32; font-weight: bold;">' + _formatMetricDisplay(metricKey, meetBudgetPer) + tfSuffix + ' left</span>';
                    } else {
                        html += '<span style="color: #c62828; font-weight: bold;">Over by ' + _formatMetricDisplay(metricKey, Math.abs(m.budgetRemaining)) + '</span>';
                    }
                } else if (m.currentlyMeeting) {
                    html += '<span style="color: #2e7d32; font-weight: bold;">On track</span>';
                } else if (m.requiredToMeet !== null && m.meetAchievable) {
                    html += '<span style="color: #e65100; font-weight: bold;">' + _formatMetricDisplay(metricKey, m.requiredToMeet) + tfSuffix + '</span>';
                } else if (m.requiredToMeet !== null && !m.meetAchievable) {
                    html += '<span style="color: #c62828; font-size: 0.85em;">Not achievable</span>';
                } else {
                    html += '<span style="color: #999;">N/A</span>';
                }
                html += '</td>';

                // Required to exceed
                html += '<td style="padding: 8px; text-align: center; background: rgba(227,242,253,0.3);">';
                if (!m.hasExceedBand) {
                    html += '<span style="color: #999; font-size: 0.85em;">No band</span>';
                } else if (m.isCumulative) {
                    if (m.currentlyExceeding) {
                        var excBudgetPer = tfDivisor > 0 ? m.exceedBudgetRemaining / tfDivisor : 0;
                        html += '<span style="color: #1565c0; font-weight: bold;">' + _formatMetricDisplay(metricKey, excBudgetPer) + tfSuffix + ' left</span>';
                    } else {
                        html += '<span style="color: #c62828; font-weight: bold;">Over by ' + _formatMetricDisplay(metricKey, Math.abs(m.exceedBudgetRemaining)) + '</span>';
                    }
                } else if (m.currentlyExceeding) {
                    html += '<span style="color: #1565c0; font-weight: bold;">On track</span>';
                } else if (m.requiredToExceed !== null && m.exceedAchievable) {
                    html += '<span style="color: #1565c0; font-weight: bold;">' + _formatMetricDisplay(metricKey, m.requiredToExceed) + tfSuffix + '</span>';
                } else if (m.requiredToExceed !== null && !m.exceedAchievable) {
                    html += '<span style="color: #c62828; font-size: 0.85em;">Not achievable</span>';
                } else {
                    html += '<span style="color: #999;">N/A</span>';
                }
                html += '</td>';

                html += '</tr>';
            });

            html += '</tbody></table>';
            html += '</div>';

            // Summary callout
            var meetingCount = 0;
            var exceedingCount = 0;
            var belowCount = 0;
            var notAchievableCount = 0;
            metricKeys.forEach(function (mk) {
                var mm = emp.metrics[mk];
                if (mm.currentlyExceeding) exceedingCount++;
                else if (mm.currentlyMeeting) meetingCount++;
                else {
                    belowCount++;
                    if (!mm.isCumulative && mm.requiredToMeet !== null && !mm.meetAchievable) notAchievableCount++;
                }
            });

            html += '<div style="margin-top: 12px; display: flex; gap: 12px; flex-wrap: wrap;">';
            if (exceedingCount > 0) {
                html += '<span style="padding: 6px 14px; border-radius: 16px; background: #e8f5e9; color: #2e7d32; font-weight: bold; font-size: 0.9em;">' + exceedingCount + ' Exceeding</span>';
            }
            if (meetingCount > 0) {
                html += '<span style="padding: 6px 14px; border-radius: 16px; background: #fff8e1; color: #f57f17; font-weight: bold; font-size: 0.9em;">' + meetingCount + ' Meeting</span>';
            }
            if (belowCount > 0) {
                html += '<span style="padding: 6px 14px; border-radius: 16px; background: #fbe9e7; color: #c62828; font-weight: bold; font-size: 0.9em;">' + belowCount + ' Below</span>';
            }
            if (notAchievableCount > 0) {
                html += '<span style="padding: 6px 14px; border-radius: 16px; background: #f8d7da; color: #721c24; font-weight: bold; font-size: 0.9em;">' + notAchievableCount + ' Not Achievable</span>';
            }
            html += '</div>';

            html += '</div>';
        });

        tableContainer.innerHTML = html;

        // Bind check-in buttons
        tableContainer.querySelectorAll('.futures-checkin-btn').forEach(function (btn) {
            btn.addEventListener('click', function () {
                var empName = btn.dataset.employee;
                showCheckInModal(empName, data);
            });
        });
    }

    /* ── Check-In Summary ── */

    /**
     * Count working days (Mon-Fri) between two dates (exclusive of start, inclusive of end).
     */
    function countWorkingDays(startDate, endDate) {
        var count = 0;
        var current = new Date(startDate.getFullYear(), startDate.getMonth(), startDate.getDate());
        current.setDate(current.getDate() + 1); // start from next day
        var end = new Date(endDate.getFullYear(), endDate.getMonth(), endDate.getDate());
        while (current <= end) {
            var dow = current.getDay();
            if (dow !== 0 && dow !== 6) count++;
            current.setDate(current.getDate() + 1);
        }
        return count;
    }

    /**
     * Get number of working days remaining in the performance period.
     * Performance period ends October 31 of the current year.
     */
    function getWorkingDaysRemaining() {
        var now = new Date();
        var endDate = new Date(now.getFullYear(), 9, 31); // Oct 31
        if (now > endDate) return 0;
        return countWorkingDays(now, endDate);
    }

    /**
     * Calculate required daily average for a rate metric to reach a target.
     * Uses weeks completed/remaining to compute overall required average,
     * then converts to a daily figure based on working days left.
     */
    function calculateDailyTarget(currentAvg, weeksCompleted, weeksRemaining, target) {
        if (weeksRemaining <= 0) return null;
        var totalNeeded = target * (weeksCompleted + weeksRemaining);
        var currentTotal = currentAvg * weeksCompleted;
        var required = (totalNeeded - currentTotal) / weeksRemaining;
        return required;
    }

    /**
     * Build an employee-friendly check-in summary.
     * Uses "next level" language — no score numbers, no goal values, no end dates.
     */
    function buildCheckInSummary(empName, data) {
        var emp = null;
        for (var i = 0; i < data.employees.length; i++) {
            if (data.employees[i].name === empName) { emp = data.employees[i]; break; }
        }
        if (!emp) return 'No data available for ' + empName + '.';

        var weekInfo = data.weekInfo;
        var workingDaysLeft = getWorkingDaysRemaining();
        var ratingBands = window.DevCoachModules?.metricProfiles?.RATING_BANDS_BY_YEAR?.[weekInfo.currentYear] || {};

        var lines = [];
        lines.push('Performance Check-In: ' + empName);
        lines.push('');

        var greatMetrics = [];
        var improvementMetrics = [];

        var metricKeys = Object.keys(emp.metrics);
        metricKeys.forEach(function (metricKey) {
            // Skip reliability — not shared with employees in check-ins
            if (metricKey === 'reliability') return;

            var m = emp.metrics[metricKey];
            var metric = window.METRICS_REGISTRY[metricKey];
            if (!metric) return;

            var label = metric.label || metricKey;
            var bandConfig = ratingBands[metricKey];

            // Determine current score level
            var score = null;
            if (bandConfig) {
                if (bandConfig.type === 'min') {
                    if (m.currentAvg >= bandConfig.score3.min) score = 3;
                    else if (m.currentAvg >= bandConfig.score2.min) score = 2;
                    else score = 1;
                } else {
                    if (m.currentAvg <= bandConfig.score3.max) score = 3;
                    else if (m.currentAvg <= bandConfig.score2.max) score = 2;
                    else score = 1;
                }
            } else {
                // No rating band — use meet/exceed status
                if (m.currentlyExceeding) score = 3;
                else if (m.currentlyMeeting) score = 2;
                else score = 1;
            }

            if (score === 3) {
                greatMetrics.push({ label: label, currentAvg: m.currentAvg, metricKey: metricKey });
                return;
            }

            // Figure out the next level target
            var nextTarget = null;
            var levelLabel = 'next level';
            if (bandConfig) {
                if (score === 1) {
                    nextTarget = bandConfig.type === 'min' ? bandConfig.score2.min : bandConfig.score2.max;
                } else if (score === 2) {
                    nextTarget = bandConfig.type === 'min' ? bandConfig.score3.min : bandConfig.score3.max;
                    levelLabel = 'top level';
                }
            } else {
                nextTarget = score === 1 ? m.meetTarget : m.exceedTarget;
                if (score === 2) levelLabel = 'top level';
            }

            if (nextTarget === null) return;

            // Calculate required daily average
            var dailyTarget = null;
            if (!m.isCumulative) {
                var requiredAvg = calculateDailyTarget(m.currentAvg, weekInfo.weeksCompleted, weekInfo.weeksRemaining, nextTarget);
                if (requiredAvg !== null && isAchievable(metricKey, requiredAvg)) {
                    dailyTarget = requiredAvg;
                }
            }

            improvementMetrics.push({
                label: label,
                metricKey: metricKey,
                currentAvg: m.currentAvg,
                nextTarget: nextTarget,
                dailyTarget: dailyTarget,
                levelLabel: levelLabel,
                isCumulative: m.isCumulative,
                isReverse: m.isReverse,
                budgetRemaining: m.budgetRemaining,
                achievable: dailyTarget !== null || m.isCumulative
            });
        });

        // Great metrics section
        if (greatMetrics.length > 0) {
            lines.push('DOING GREAT:');
            greatMetrics.forEach(function (gm) {
                lines.push('  ' + gm.label + ': ' + _formatMetricDisplay(gm.metricKey, gm.currentAvg) + ' — Top level! Keep it up.');
            });
            lines.push('');
        }

        // Improvement metrics section
        if (improvementMetrics.length > 0) {
            lines.push('AREAS TO FOCUS ON:');
            improvementMetrics.forEach(function (im) {
                var current = _formatMetricDisplay(im.metricKey, im.currentAvg);
                if (im.isCumulative) {
                    if (im.budgetRemaining > 0) {
                        var perDay = workingDaysLeft > 0 ? im.budgetRemaining / workingDaysLeft : 0;
                        lines.push('  ' + im.label + ': Currently at ' + current + '. You have ' + _formatMetricDisplay(im.metricKey, im.budgetRemaining) + ' remaining to stay within budget.');
                    } else {
                        lines.push('  ' + im.label + ': Currently at ' + current + '. Over budget — minimize further usage.');
                    }
                } else if (im.dailyTarget !== null) {
                    var targetDisplay = _formatMetricDisplay(im.metricKey, im.dailyTarget);
                    var direction = im.isReverse ? 'at or below' : 'at or above';
                    lines.push('  ' + im.label + ': Currently at ' + current + '. To reach the ' + im.levelLabel + ', aim for ' + direction + ' ' + targetDisplay + ' each day.');
                } else {
                    lines.push('  ' + im.label + ': Currently at ' + current + '. This one will be tough to move — stay consistent and do your best.');
                }
            });
            lines.push('');
        }

        if (improvementMetrics.length === 0 && greatMetrics.length > 0) {
            lines.push('All metrics are at the top level — outstanding work!');
            lines.push('');
        }

        lines.push('Keep pushing — every day counts!');

        return lines.join('\n');
    }

    /**
     * Show the check-in summary in a modal.
     */
    function showCheckInModal(empName, data) {
        var summary = buildCheckInSummary(empName, data);

        // Remove existing modal if any
        var existing = document.getElementById('futuresCheckInModal');
        if (existing) existing.remove();

        var overlay = document.createElement('div');
        overlay.id = 'futuresCheckInModal';
        overlay.className = 'modal-overlay';
        overlay.style.display = 'flex';

        var content = document.createElement('div');
        content.className = 'modal-content';
        content.innerHTML =
            '<div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px;">' +
                '<h3 style="margin: 0; color: #1a1a2e;">Check-In Summary</h3>' +
                '<button id="futuresCheckInClose" style="background: none; border: none; font-size: 1.5em; cursor: pointer; color: #666; padding: 0 4px;">&times;</button>' +
            '</div>' +
            '<pre id="futuresCheckInText" style="white-space: pre-wrap; font-family: Segoe UI, sans-serif; font-size: 0.92em; line-height: 1.6; background: #f8f9fa; padding: 16px; border-radius: 6px; border: 1px solid #e0e0e0; max-height: 60vh; overflow-y: auto;">' + _escapeHtml(summary) + '</pre>' +
            '<div style="margin-top: 16px; display: flex; gap: 10px;">' +
                '<button id="futuresCheckInCopy" style="padding: 10px 20px; background: #4caf50; color: white; border: none; border-radius: 6px; cursor: pointer; font-weight: bold; font-size: 0.95em;">Copy to Clipboard</button>' +
            '</div>';

        overlay.appendChild(content);
        document.body.appendChild(overlay);

        // Close handlers
        document.getElementById('futuresCheckInClose').addEventListener('click', function () { overlay.remove(); });
        overlay.addEventListener('click', function (e) { if (e.target === overlay) overlay.remove(); });

        // Copy handler
        document.getElementById('futuresCheckInCopy').addEventListener('click', function () {
            navigator.clipboard.writeText(summary).then(function () {
                var btn = document.getElementById('futuresCheckInCopy');
                btn.textContent = 'Copied!';
                btn.style.background = '#2e7d32';
                setTimeout(function () { btn.textContent = 'Copy to Clipboard'; btn.style.background = '#4caf50'; }, 2000);
            });
        });
    }

    /* ── Module export ── */
    window.DevCoachModules = window.DevCoachModules || {};
    window.DevCoachModules.futures = {
        renderFutures: renderFutures,
        buildFuturesData: buildFuturesData,
        buildCheckInSummary: buildCheckInSummary,
        showCheckInModal: showCheckInModal
    };

    window.renderFutures = renderFutures;
})();
