(function () {
    'use strict';

    var STORAGE_PREFIX = (window.DevCoachConstants && window.DevCoachConstants.STORAGE_PREFIX) || 'devCoachingTool_';

    function _escapeHtml(str) {
        var mod = window.DevCoachModules?.sharedUtils;
        if (mod?.escapeHtml) return mod.escapeHtml(str);
        return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
    }

    function _formatMetricDisplay(key, value) {
        return typeof window.formatMetricDisplay === 'function' ? window.formatMetricDisplay(key, value) : String(value);
    }

    /**
     * Which supervisor label is me.
     *
     * Picks the supervisor whose assigned reps overlap my own team list most.
     * Returns null when nothing overlaps, which leaves every supervisor row
     * alone rather than guessing one of them is mine.
     */
    function resolveMyTeamLabel(rankings, supervisors, myTeamSet) {
        // team-scope owns "which supervisor label is me". Asking it keeps the
        // head-to-head and the My Team picker on the same answer — they used to
        // disagree, which is how my own team appeared twice in one table.
        var scope = window.DevCoachModules?.teamScope;
        if (scope?.resolveMyLabel) {
            var shared = scope.resolveMyLabel(supervisors, Array.from(myTeamSet || []));
            if (shared) return shared;
        }

        var counts = {};
        (rankings || []).forEach(function (r) {
            var sup = supervisors && supervisors[r.name];
            if (!sup || !myTeamSet || !myTeamSet.has(r.name)) return;
            counts[sup] = (counts[sup] || 0) + 1;
        });

        var best = null;
        var bestCount = 0;
        Object.keys(counts).forEach(function (sup) {
            // Ties go to the alphabetically first label so the answer is stable
            // across reloads rather than depending on key order.
            if (counts[sup] > bestCount || (counts[sup] === bestCount && best && sup < best)) {
                bestCount = counts[sup];
                best = sup;
            }
        });
        return bestCount > 0 ? best : null;
    }

    function _getSupervisors() {
        try {
            return JSON.parse(localStorage.getItem(STORAGE_PREFIX + 'employeeSupervisors') || '{}');
        } catch (_e) { return {}; }
    }

    function _getTeamMembersForWeek(weekKey) {
        return typeof window.getTeamMembersForWeek === 'function' ? window.getTeamMembersForWeek(weekKey) : [];
    }

    function _getLatestWeeklyKey() {
        return typeof window.getLatestWeeklyKey === 'function' ? window.getLatestWeeklyKey() : null;
    }

    function _getWeeklyData() {
        return typeof weeklyData !== 'undefined' ? weeklyData : {};
    }
    function _getYtdData() {
        return typeof ytdData !== 'undefined' ? ytdData : {};
    }

    function _getAvailablePeriods() {
        var periods = [];
        var wData = _getWeeklyData();
        var yData = _getYtdData();
        var currentYear = new Date().getFullYear();

        Object.keys(wData).forEach(function(key) {
            var data = wData[key];
            var meta = data?.metadata || {};
            var count = (data?.employees || []).length;
            if (count < 2) return;
            var pType = meta.periodType || 'week';
            var endStr = meta.endDate || (key.includes('|') ? key.split('|')[1] : '');
            var label = meta.label || _formatPeriodLabel(key, pType);
            periods.push({ key: key, label: label, type: pType, source: 'weekly', count: count, endDate: endStr });
        });

        Object.keys(yData).forEach(function(key) {
            var data = yData[key];
            var meta = data?.metadata || {};
            if (meta.autoGeneratedYtd) return;
            var count = (data?.employees || []).length;
            if (count < 2) return;
            var pType = meta.periodType || 'ytd';
            var endStr = meta.endDate || (key.includes('|') ? key.split('|')[1] : '');
            var label = meta.label || _formatPeriodLabel(key, pType);
            periods.push({ key: key, label: label, type: pType, source: 'ytd', count: count, endDate: endStr });
        });

        // Months rebuilt from weekly uploads, so a supervisor matchup can be run
        // over a whole month instead of a single week. Same source as the
        // rankings picker, so both offer the same months.
        var _pc = window.DevCoachModules && window.DevCoachModules.periodCompare;
        if (_pc && _pc.getMonthPeriodOptions) {
            periods = periods.concat(_pc.getMonthPeriodOptions());
        }

        periods.sort(function(a, b) {
            var aDate = a.endDate || a.key.split('|')[1] || '';
            var bDate = b.endDate || b.key.split('|')[1] || '';
            return bDate.localeCompare(aDate);
        });

        return periods;
    }

    function _formatPeriodLabel(key, type) {
        var parts = key.split('|');
        var endDate = parts[1] || parts[0] || '';
        var prefix;
        if (type === 'ytd') prefix = 'YTD';
        else if (type === 'month' || type === 'month-agg') prefix = 'Monthly';
        else if (type === 'quarter') prefix = 'Quarterly';
        else if (type === 'daily') prefix = 'Daily';
        else if (type === 'week-in-progress') prefix = 'Week in progress';
        else prefix = 'Weekly';
        return prefix + ' ending ' + endDate;
    }

    var _selectedPeriodKey = null;
    var _selectedPeriodSource = null;
    var _matchupPeriodInitialized = false;

    /* ── Scope ──
       The period list runs to twenty-odd entries and mixes weeks, months and YTD,
       so picking "this month" or "the year" meant hunting. Scope jumps to the
       newest period of a kind that can actually carry a matchup.

       The floor of 30 matters: a single supervisor's report filed as a month is a
       valid period but every person in it is on one team, which produces a matchup
       with no opponents. */
    var MIN_MATCHUP_EMPLOYEES = 30;

    var MATCHUP_SCOPES = [
        { key: 'ytd', label: 'YTD', types: ['ytd'] },
        { key: 'month', label: 'Monthly', types: ['month', 'month-agg'] },
        { key: 'week', label: 'Weekly', types: ['week', 'week-in-progress'] }
    ];

    function _periodsForScope(scopeKey) {
        var scope = MATCHUP_SCOPES.filter(function (s) { return s.key === scopeKey; })[0];
        if (!scope) return [];
        return _getAvailablePeriods().filter(function (p) {
            return scope.types.indexOf(p.type) > -1 && p.count >= MIN_MATCHUP_EMPLOYEES;
        });
    }

    function _scopeOfPeriod(periodKey) {
        if (!periodKey) return null;
        var all = _getAvailablePeriods();
        var match = all.filter(function (p) { return p.key === periodKey; })[0];
        if (!match) return null;
        var hit = MATCHUP_SCOPES.filter(function (s) { return s.types.indexOf(match.type) > -1; })[0];
        return hit ? hit.key : null;
    }

    function _renderScopeSelector() {
        var active = _scopeOfPeriod(_selectedPeriodKey);
        var html = '<div style="margin-bottom: 10px; display: flex; align-items: center; gap: 8px; flex-wrap: wrap;">';
        html += '<label style="font-weight: 600; color: var(--text-secondary); font-size: 0.9em;">Compare:</label>';

        MATCHUP_SCOPES.forEach(function (s) {
            var available = _periodsForScope(s.key);
            var isActive = active === s.key;
            var disabled = available.length === 0;
            html += '<button type="button" class="matchup-scope-btn" data-scope="' + s.key + '"' +
                (disabled ? ' disabled' : '') +
                ' title="' + (disabled ? 'No ' + s.label.toLowerCase() + ' period covers enough of the centre' : 'Newest: ' + _escapeHtml(available[0].label)) + '"' +
                ' style="padding: 6px 14px; border-radius: 6px; font-size: 0.9em; cursor: ' + (disabled ? 'not-allowed' : 'pointer') + ';' +
                ' font-weight: ' + (isActive ? '700' : '500') + ';' +
                ' border: 2px solid ' + (isActive ? '#e65100' : 'var(--border)') + ';' +
                ' background: ' + (isActive ? '#e65100' : 'var(--bg-surface)') + ';' +
                ' color: ' + (isActive ? '#ffffff' : (disabled ? 'var(--text-tertiary)' : 'var(--text-primary)')) + ';' +
                ' box-shadow: ' + (isActive ? '0 0 0 3px rgba(230,81,0,0.25)' : 'none') + ';' +
                ' opacity: ' + (disabled ? '0.55' : '1') + ';">' + s.label + '</button>';
        });

        html += '</div>';
        return html;
    }

    function _onScopeClick(scopeKey) {
        var available = _periodsForScope(scopeKey);
        if (!available.length) return;
        _selectedPeriodKey = available[0].key;
        _selectedPeriodSource = available[0].source;
        renderMatchup();
    }

    // Metric definitions for matchup comparison
    // Each has: key (values obj key), label, lowerIsBetter flag, formatKey (for formatMetricDisplay).
    // weightBy controls team aggregation — 'calls' weights by call volume, 'survey' by survey
    // count, 'sum' totals the values. Never simple-average rate metrics across agents.
    var MATCHUP_METRICS = [
        { key: 'aht',              label: 'AHT',             lowerIsBetter: true,  formatKey: 'aht',               weightBy: 'calls' },
        { key: 'adherence',        label: 'Adherence',       lowerIsBetter: false, formatKey: 'scheduleAdherence', weightBy: 'calls' },
        { key: 'sentiment',        label: 'Sentiment',       lowerIsBetter: false, formatKey: 'overallSentiment',  weightBy: 'calls' },
        { key: 'associateOverall', label: 'Assoc Overall',   lowerIsBetter: false, formatKey: 'cxRepOverall',      weightBy: 'survey' },
        { key: 'reliability',      label: 'Reliability',     lowerIsBetter: true,  formatKey: 'reliability', isTopLevel: true, weightBy: 'sum' }
    ];

    /**
     * Build matchup data: groups all ranked employees by supervisor,
     * computes team averages, and determines wins per metric.
     */
    function buildMatchupData(periodKey) {
        var ranking = window.DevCoachModules?.centerRanking;
        if (!ranking?.buildCenterRankings) return null;

        var data;
        if (periodKey && ranking.buildRankingsForPeriod) {
            data = ranking.buildRankingsForPeriod(periodKey);
        } else {
            data = ranking.buildCenterRankings();
        }
        if (!data || !data.rankings.length) return null;

        var supervisors = _getSupervisors();

        // Which supervisor am I? Whichever one's roster overlaps my own team
        // list the most. Data-driven rather than configured, so it keeps working
        // when the roster is re-read.
        var latestKey = _getLatestWeeklyKey();
        var teamFilter = window.DevCoachModules?.teamFilter;
        if (!latestKey && teamFilter?.getTeamSelectionContext) {
            latestKey = teamFilter.getTeamSelectionContext().weekKey || '';
        }
        var myTeamSet = new Set(latestKey ? _getTeamMembersForWeek(latestKey) : []);

        // Group employees by supervisor
        var teams = {};  // supervisor name -> [ranked employee objects]
        var MY_TEAM = 'My Team';
        var myLabel = resolveMyTeamLabel(data.rankings, supervisors, myTeamSet);

        data.rankings.forEach(function (r) {
            var sup = supervisors[r.name] || '';
            // My own supervisor row and "My Team" are the same team. Left apart,
            // half my reps sat under my name and half under "My Team", the two
            // halves competed against each other in the rankings, and neither
            // row was actually my team.
            if (sup && myLabel && sup === myLabel) {
                sup = MY_TEAM;
            } else if (!sup) {
                sup = myTeamSet.has(r.name) ? MY_TEAM : 'Unassigned';
            }
            if (!teams[sup]) teams[sup] = [];
            teams[sup].push(r);
        });

        // Only include teams that have at least 1 member
        // (Unassigned is kept but displayed last)
        var teamNames = Object.keys(teams).sort(function (a, b) {
            if (a === MY_TEAM) return -1;
            if (b === MY_TEAM) return 1;
            if (a === 'Unassigned') return 1;
            if (b === 'Unassigned') return -1;
            return a.localeCompare(b);
        });

        // Compute team averages per metric
        var teamStats = {};
        teamNames.forEach(function (name) {
            var members = teams[name];
            var stats = { name: name, count: members.length, averages: {}, totalComposite: 0, wins: 0, losses: 0, ties: 0 };

            MATCHUP_METRICS.forEach(function (m) {
                var _val = function (r) {
                    return m.isTopLevel ? r[m.key] : (r.values ? r.values[m.key] : null);
                };

                // Cumulative metrics (reliability) total their values.
                if (m.weightBy === 'sum') {
                    var sumVals = members.map(_val).filter(function (v) {
                        return v !== null && v !== undefined && !isNaN(v);
                    });
                    stats.averages[m.key] = sumVals.length > 0
                        ? sumVals.reduce(function (a, b) { return a + b; }, 0)
                        : null;
                    return;
                }

                // Rate metrics use a volume-weighted average so high-volume agents
                // pull the team number — matching Team Snapshot's computeTeamMetricValue.
                var wSum = 0, wTotal = 0;
                members.forEach(function (r) {
                    var v = _val(r);
                    if (v === null || v === undefined || isNaN(v)) return;
                    var w;
                    if (m.weightBy === 'survey') {
                        w = r.surveyTotal > 0 ? r.surveyTotal : 0;
                    } else {
                        w = r.totalCalls > 0 ? r.totalCalls : 1;
                    }
                    if (w <= 0) return;
                    wSum += v * w;
                    wTotal += w;
                });
                stats.averages[m.key] = wTotal > 0 ? wSum / wTotal : null;
            });

            // Average composite rank
            var composites = members.map(function (r) { return r.compositeScore; }).filter(function (v) { return v !== Infinity; });
            stats.totalComposite = composites.length > 0
                ? composites.reduce(function (a, b) { return a + b; }, 0) / composites.length
                : Infinity;

            // Average rating
            var ratings = members.map(function (r) { return r.ratingAverage; }).filter(function (v) { return v != null; });
            stats.avgRating = ratings.length > 0
                ? ratings.reduce(function (a, b) { return a + b; }, 0) / ratings.length
                : 0;

            teamStats[name] = stats;
        });

        // Head-to-head: compare My Team vs each rival on each metric
        var myStats = teamStats[MY_TEAM];
        if (myStats) {
            teamNames.forEach(function (name) {
                if (name === MY_TEAM || name === 'Unassigned') return;
                var rival = teamStats[name];
                MATCHUP_METRICS.forEach(function (m) {
                    var myVal = myStats.averages[m.key];
                    var rivalVal = rival.averages[m.key];
                    if (myVal === null || rivalVal === null) return;

                    var myWins;
                    if (m.lowerIsBetter) {
                        myWins = myVal < rivalVal;
                    } else {
                        myWins = myVal > rivalVal;
                    }
                    var tie = Math.abs(myVal - rivalVal) < 0.01;

                    if (tie) {
                        myStats.ties++;
                        rival.ties++;
                    } else if (myWins) {
                        myStats.wins++;
                        rival.losses++;
                    } else {
                        myStats.losses++;
                        rival.wins++;
                    }
                });
            });
        }

        return {
            teams: teams,
            teamNames: teamNames,
            teamStats: teamStats,
            rankings: data.rankings,
            totalEmployees: data.totalEmployees,
            source: data.source,
            // Which supervisor label is mine. The movement panel groups on raw
            // supervisor labels, so it needs this to know which row is yours.
            myLabel: myLabel
        };
    }

    /**
     * How each supervisor's team moved between the last two comparable months.
     *
     * Placed on average KPI score rather than average rank. Average rank depends on
     * who else is in the pool — a team can lose a weak performer and every remaining
     * member's rank improves with nobody doing anything differently. KPI score is a
     * fixed 1-3 scale, so a move in it is a real move.
     *
     * Independent of the period selector above, which chooses what the matchup
     * itself is computed over. Both months are named so the two are not confused.
     */
    function _renderTeamMovement(data) {
        var pc = window.DevCoachModules && window.DevCoachModules.periodCompare;
        if (!pc || !pc.buildMonthOverMonthTeams) return '';

        // Follows the selected scope. Showing month-over-month while someone has
        // Weekly selected reads as a broken panel — the header and period change,
        // the movement does not, so it looks stuck rather than deliberate.
        var scope = _scopeOfPeriod(_selectedPeriodKey) || 'month';
        var mv, fellBack = false;
        try {
            mv = pc.buildTeamMovementForScope(scope, _getSupervisors());
            // A single YTD upload has nothing to compare against. Months are the
            // useful answer there, said out loud rather than shown silently.
            if (!mv && scope !== 'month') {
                mv = pc.buildTeamMovementForScope('month', _getSupervisors());
                fellBack = !!mv;
            }
        } catch (err) {
            console.warn('[matchup] Team movement unavailable:', err && err.message);
            return '';
        }
        if (!mv || !mv.teams.length) return '';

        var SCOPE_NOUN = { ytd: 'year-to-date file', month: 'month', week: 'week' };

        var html = '<div style="margin-bottom: 20px; padding: 15px; background: var(--bg-surface); border-radius: 8px; border: 1px solid var(--border); box-shadow: 0 1px 3px rgba(0,0,0,0.08);">';
        html += '<h4 style="margin-top: 0; color: var(--text-primary);">Team Movement &mdash; ' +
            _escapeHtml(mv.previous.label) + ' &rarr; ' + _escapeHtml(mv.current.label) + '</h4>';
        html += '<p style="margin: 0 0 12px 0; color: var(--text-secondary); font-size: 0.85em;">' +
            'Placed on average KPI score across the ' + mv.total + ' associates scored in both. ' +
            'Teams on the same average share a place.' +
            (fellBack
                ? ' <span style="color: #e65100;">Only one ' + (SCOPE_NOUN[scope] || scope) +
                  ' is available, so there is nothing to compare it against — showing months instead.</span>'
                : '') +
            '</p>';

        html += '<table style="width: 100%; border-collapse: collapse; font-size: 0.88em;">';
        html += '<thead><tr style="background: var(--bg-surface-raised);">';
        ['Place', 'Team', 'Move', 'Avg KPI', 'Change', 'Scored'].forEach(function (h, i) {
            html += '<th style="padding: 6px 8px; border-bottom: 2px solid #ddd; text-align: ' + (i === 1 ? 'left' : 'center') + '; font-size: 0.9em;">' + h + '</th>';
        });
        html += '</tr></thead><tbody>';

        mv.teams.forEach(function (t, idx) {
            var isMine = data && data.myLabel && t.name === data.myLabel;
            var bg = isMine ? 'rgba(21,101,192,0.10)' : (idx % 2 === 0 ? 'var(--bg-surface-raised)' : 'transparent');

            var moveHtml;
            if (t.placeDelta === 0) {
                moveHtml = '<span style="color: var(--text-tertiary);">&#8213;</span>';
            } else {
                var up = t.placeDelta > 0;
                moveHtml = '<span style="color: ' + (up ? '#2e7d32' : '#c62828') + '; font-weight: bold;">' +
                    (up ? '&#9650;' : '&#9660;') + Math.abs(t.placeDelta) + '</span>';
            }

            // Rating change is the substance; place can move because another team
            // moved, so it is shown but never on its own.
            var rd = t.ratingDelta;
            var rdColor = Math.abs(rd) < 0.005 ? 'var(--text-tertiary)' : (rd > 0 ? '#2e7d32' : '#c62828');
            var rdText = Math.abs(rd) < 0.005 ? 'no change' : (rd > 0 ? '+' : '') + rd.toFixed(2);

            html += '<tr style="background: ' + bg + '; border-bottom: 1px solid var(--border);">';
            html += '<td style="padding: 6px 8px; text-align: center; font-weight: bold;">' + t.curPlace + '</td>';
            html += '<td style="padding: 6px 8px; font-weight: ' + (isMine ? 'bold' : 'normal') + ';">' +
                _escapeHtml(t.name) + (isMine ? ' <span style="color:#1565c0;">(you)</span>' : '') + '</td>';
            html += '<td style="padding: 6px 8px; text-align: center;">' + moveHtml + '</td>';
            html += '<td style="padding: 6px 8px; text-align: center;">' + t.curAvgRating.toFixed(2) + '</td>';
            html += '<td style="padding: 6px 8px; text-align: center; color: ' + rdColor + ';">' + rdText + '</td>';
            html += '<td style="padding: 6px 8px; text-align: center; color: var(--text-secondary);">' + t.count + '</td>';
            html += '</tr>';
        });

        html += '</tbody></table></div>';
        return html;
    }

    /**
     * Render the full Matchup view
     */
    function _renderPeriodSelector(selectedValue) {
        var periods = _getAvailablePeriods();
        var typeOrder = ['ytd', 'quarter', 'month', 'month-agg', 'week', 'week-in-progress', 'daily'];
        var typeLabels = { ytd: 'YTD', quarter: 'Quarterly', month: 'Monthly', 'month-agg': 'Monthly (rebuilt from weeks)', week: 'Weekly', 'week-in-progress': 'Week to Date', daily: 'Daily' };
        var grouped = {};
        periods.forEach(function(p) {
            var t = p.type || 'week';
            if (!grouped[t]) grouped[t] = [];
            grouped[t].push(p);
        });

        var html = '<div style="margin-bottom: 16px; display: flex; align-items: center; gap: 12px; flex-wrap: wrap;">';
        html += '<label style="font-weight: 600; color: var(--text-secondary); font-size: 0.9em;">Period:</label>';
        html += '<select id="matchupPeriodSelect" style="padding: 6px 10px; border: 1px solid var(--border); border-radius: 6px; font-size: 0.9em; min-width: 260px;">';
        html += '<option value="">Auto (Best Available)</option>';

        typeOrder.forEach(function(t) {
            if (!grouped[t] || grouped[t].length === 0) return;
            html += '<optgroup label="' + (typeLabels[t] || t) + '">';
            grouped[t].forEach(function(p) {
                var val = p.key + '||' + p.source;
                var sel = (val === selectedValue) ? ' selected' : '';
                html += '<option value="' + _escapeHtml(val) + '"' + sel + '>' + _escapeHtml(p.label) + ' (' + p.count + ' employees)</option>';
            });
            html += '</optgroup>';
        });

        html += '</select></div>';
        return html;
    }

    function _onPeriodChange() {
        var select = document.getElementById('matchupPeriodSelect');
        if (!select) return;
        var val = select.value;
        if (val) {
            var parts = val.split('||');
            _selectedPeriodKey = parts[0];
            _selectedPeriodSource = parts[1] || '';
        } else {
            _selectedPeriodKey = null;
            _selectedPeriodSource = null;
        }
        renderMatchup();
    }

    function renderMatchup() {
        var container = document.getElementById('subSectionTaMatchup');
        if (!container) return;

        // Default to most recent YTD period on first render
        if (!_matchupPeriodInitialized) {
            _matchupPeriodInitialized = true;
            var periods = _getAvailablePeriods();
            var ytdPeriod = periods.find(function(p) { return p.type === 'ytd' && p.count >= 30; });
            if (ytdPeriod) {
                _selectedPeriodKey = ytdPeriod.key;
                _selectedPeriodSource = ytdPeriod.source || '';
            }
        }

        var currentSelectValue = _selectedPeriodKey ? (_selectedPeriodKey + '||' + _selectedPeriodSource) : '';

        var data = buildMatchupData(_selectedPeriodKey);
        if (!data) {
            container.innerHTML = _renderPeriodSelector(currentSelectValue) +
                '<p style="color: var(--text-tertiary); text-align: center; padding: 40px;">No matchup data available. Upload a full center data set and assign supervisors in Settings > Team Members.</p>';
            var sel = document.getElementById('matchupPeriodSelect');
            if (sel) sel.addEventListener('change', _onPeriodChange);
            return;
        }

        // Check if any supervisors are actually assigned (besides My Team and Unassigned)
        var rivalTeams = data.teamNames.filter(function (n) { return n !== 'My Team' && n !== 'Unassigned'; });
        if (rivalTeams.length === 0) {
            // Two very different causes, and the old copy only described one. A
            // period holding a single supervisor's upload (one team's report filed
            // as a month) has nobody to match against no matter how the roster is
            // set up, and sending someone to Settings to fix that wastes their time.
            var _onlyMine = data.totalEmployees > 0 && data.totalEmployees < 40;
            var _why = _onlyMine
                ? 'This period only has <strong>' + data.totalEmployees + ' associates</strong> in it, and they are all on one team, so there is nothing to match against. Pick a period covering the whole centre using the scope buttons above.'
                : 'No supervisors are assigned. Go to <strong>Settings &gt; Team Members</strong> and type a supervisor name (e.g. "Nicole P") next to their agents to set up matchups.';
            container.innerHTML = _renderScopeSelector() + _renderPeriodSelector(currentSelectValue) +
                '<div style="padding: 30px; text-align: center;">' +
                '<h3 style="color: #e65100;">🥊 Team Matchup</h3>' +
                '<p style="color: var(--text-secondary); max-width: 560px; margin: 0 auto;">' + _why + '</p>' +
                '<p style="color: var(--text-tertiary); font-size: 0.85em; margin-top: 10px;">Source: ' + _escapeHtml(data.source) + '</p>' +
                '</div>';
            var sel = document.getElementById('matchupPeriodSelect');
            if (sel) sel.addEventListener('change', _onPeriodChange);
            // Bound here too, or the buttons the message points at do nothing.
            _bindScopeButtons(container);
            return;
        }

        var html = '';

        // Scope buttons, then the full period list
        html += _renderScopeSelector();
        html += _renderPeriodSelector(currentSelectValue);

        // Header
        html += '<div style="margin-bottom: 20px; padding: 15px; background: #fff3e0; border-radius: 8px; border-left: 4px solid #e65100;">';
        html += '<strong>🥊 Team Matchup</strong> &mdash; ' + data.totalEmployees + ' employees across ' + data.teamNames.length + ' teams';
        html += '<br><span style="color: var(--text-secondary); font-size: 0.85em;">Source: ' + _escapeHtml(data.source) + '</span>';
        html += '</div>';

        // Month-over-month team movement
        html += _renderTeamMovement(data);

        // Scoreboard: My Team vs each rival
        var myStats = data.teamStats['My Team'];
        if (myStats) {
            rivalTeams.forEach(function (rivalName) {
                var rival = data.teamStats[rivalName];
                html += _renderHeadToHead(myStats, rival, data);
            });
        }

        // Team Rankings table
        html += _renderTeamRankings(data);

        // Per-team member breakdown
        data.teamNames.forEach(function (teamName) {
            if (teamName === 'Unassigned') return;
            html += _renderTeamRoster(teamName, data);
        });

        container.innerHTML = html;

        // Bind period selector
        var sel = document.getElementById('matchupPeriodSelect');
        if (sel) sel.addEventListener('change', _onPeriodChange);
        _bindScopeButtons(container);
    }

    function _bindScopeButtons(container) {
        if (!container || !container.querySelectorAll) return;
        Array.prototype.forEach.call(container.querySelectorAll('.matchup-scope-btn'), function (btn) {
            if (btn.disabled) return;
            btn.addEventListener('click', function () {
                _onScopeClick(btn.getAttribute('data-scope'));
            });
        });
    }

    function _renderHeadToHead(myStats, rivalStats, data) {
        var html = '<div style="margin-bottom: 20px; padding: 20px; background: var(--bg-surface); border-radius: 12px; border: 2px solid #e65100; box-shadow: 0 2px 8px rgba(0,0,0,0.08);">';

        // Team names header
        html += '<div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px;">';
        html += '<div style="text-align: center; flex: 1;">';
        html += '<div style="font-size: 1.3em; font-weight: bold; color: #1565c0;">My Team</div>';
        html += '<div style="font-size: 0.85em; color: var(--text-secondary);">' + myStats.count + ' agents</div>';
        html += '</div>';
        html += '<div style="font-size: 1.5em; font-weight: bold; color: #e65100; padding: 0 20px;">VS</div>';
        html += '<div style="text-align: center; flex: 1;">';
        html += '<div style="font-size: 1.3em; font-weight: bold; color: var(--red-text);">' + _escapeHtml(rivalStats.name) + '</div>';
        html += '<div style="font-size: 0.85em; color: var(--text-secondary);">' + rivalStats.count + ' agents</div>';
        html += '</div>';
        html += '</div>';

        // Metric-by-metric bars
        MATCHUP_METRICS.forEach(function (m) {
            var myVal = myStats.averages[m.key];
            var rivalVal = rivalStats.averages[m.key];
            if (myVal === null || rivalVal === null) return;

            var myWins, tie;
            if (m.lowerIsBetter) {
                myWins = myVal < rivalVal;
                tie = Math.abs(myVal - rivalVal) < 0.01;
            } else {
                myWins = myVal > rivalVal;
                tie = Math.abs(myVal - rivalVal) < 0.01;
            }

            var myColor = tie ? '#666' : (myWins ? '#2e7d32' : '#c62828');
            var rivalColor = tie ? '#666' : (myWins ? '#c62828' : '#2e7d32');
            var myBg = tie ? '#f5f5f5' : (myWins ? '#e8f5e9' : '#fbe9e7');
            var rivalBg = tie ? '#f5f5f5' : (myWins ? '#fbe9e7' : '#e8f5e9');
            var icon = tie ? '🤝' : (myWins ? '✅' : '❌');

            html += '<div style="display: flex; align-items: center; margin-bottom: 8px; gap: 8px;">';
            // My team value
            html += '<div style="flex: 1; text-align: right; padding: 8px 12px; background: ' + myBg + '; border-radius: 6px;">';
            html += '<span style="font-weight: bold; color: ' + myColor + ';">' + _formatMetricDisplay(m.formatKey, myVal) + '</span>';
            html += '</div>';
            // Metric label
            html += '<div style="width: 110px; text-align: center; font-size: 0.85em; font-weight: 600; color: var(--text-secondary);">' + icon + ' ' + m.label + '</div>';
            // Rival value
            html += '<div style="flex: 1; text-align: left; padding: 8px 12px; background: ' + rivalBg + '; border-radius: 6px;">';
            html += '<span style="font-weight: bold; color: ' + rivalColor + ';">' + _formatMetricDisplay(m.formatKey, rivalVal) + '</span>';
            html += '</div>';
            html += '</div>';
        });

        // Overall record for this matchup
        var myWinsTotal = 0, rivalWinsTotal = 0, tiesTotal = 0;
        MATCHUP_METRICS.forEach(function (m) {
            var myVal = myStats.averages[m.key];
            var rivalVal = rivalStats.averages[m.key];
            if (myVal === null || rivalVal === null) return;
            var tie = Math.abs(myVal - rivalVal) < 0.01;
            if (tie) { tiesTotal++; return; }
            var myWins = m.lowerIsBetter ? (myVal < rivalVal) : (myVal > rivalVal);
            if (myWins) myWinsTotal++; else rivalWinsTotal++;
        });

        var recordColor = myWinsTotal > rivalWinsTotal ? '#2e7d32' : (myWinsTotal < rivalWinsTotal ? '#c62828' : '#666');
        html += '<div style="text-align: center; margin-top: 12px; padding: 10px; background: var(--bg-surface-raised); border-radius: 8px;">';
        html += '<span style="font-size: 1.2em; font-weight: bold; color: ' + recordColor + ';">';
        html += myWinsTotal + 'W - ' + rivalWinsTotal + 'L';
        if (tiesTotal > 0) html += ' - ' + tiesTotal + 'T';
        html += '</span>';
        html += '</div>';

        html += '</div>';
        return html;
    }

    function _renderTeamRankings(data) {
        // Sort teams by avg composite score (lower = better), skip Unassigned
        var sortedTeams = data.teamNames
            .filter(function (n) { return n !== 'Unassigned'; })
            .map(function (n) { return data.teamStats[n]; })
            .sort(function (a, b) { return (b.avgRating || 0) - (a.avgRating || 0); });

        var html = '<div style="margin-bottom: 20px; padding: 20px; background: var(--bg-surface); border-radius: 8px; border: 1px solid var(--border); box-shadow: 0 1px 3px rgba(0,0,0,0.08);">';
        html += '<h4 style="margin-top: 0; color: var(--text-primary);">Team Power Rankings</h4>';

        html += '<table style="width: 100%; border-collapse: collapse; font-size: 0.88em;">';
        html += '<thead><tr style="background: var(--bg-surface-raised); border-bottom: 2px solid var(--border);">';
        html += '<th style="padding: 8px; text-align: center; width: 40px;">#</th>';
        html += '<th style="padding: 8px; text-align: left;">Team</th>';
        html += '<th style="padding: 8px; text-align: center;">Agents</th>';
        html += '<th style="padding: 8px; text-align: center;">Avg Score</th>';
        html += '<th style="padding: 8px; text-align: center;">Avg Rank</th>';

        MATCHUP_METRICS.forEach(function (m) {
            html += '<th style="padding: 8px; text-align: center;">' + m.label + '</th>';
        });

        html += '<th style="padding: 8px; text-align: center;">Record</th>';
        html += '</tr></thead><tbody>';

        sortedTeams.forEach(function (team, idx) {
            var isMyTeam = team.name === 'My Team';
            var rowBg = isMyTeam ? '#e8eaf6' : (idx % 2 === 0 ? '#fff' : '#fafafa');
            var fontWeight = isMyTeam ? 'bold' : 'normal';

            html += '<tr style="background: ' + rowBg + '; border-bottom: 1px solid var(--border); font-weight: ' + fontWeight + ';">';
            html += '<td style="padding: 8px; text-align: center; font-weight: bold;">' + (idx + 1) + '</td>';
            html += '<td style="padding: 8px;">' + (isMyTeam ? '<span style="color: #1565c0;">★ </span>' : '') + _escapeHtml(team.name) + '</td>';
            html += '<td style="padding: 8px; text-align: center;">' + team.count + '</td>';
            html += '<td style="padding: 8px; text-align: center;">' + (team.avgRating ? team.avgRating.toFixed(2) : '--') + '</td>';
            html += '<td style="padding: 8px; text-align: center;">' + (team.totalComposite !== Infinity ? team.totalComposite.toFixed(1) : '--') + '</td>';

            MATCHUP_METRICS.forEach(function (m) {
                var val = team.averages[m.key];
                html += '<td style="padding: 8px; text-align: center;">' + (val !== null ? _formatMetricDisplay(m.formatKey, val) : '--') + '</td>';
            });

            html += '<td style="padding: 8px; text-align: center;">';
            var wColor = team.wins > team.losses ? '#2e7d32' : (team.wins < team.losses ? '#c62828' : '#666');
            html += '<span style="color: ' + wColor + '; font-weight: bold;">' + team.wins + 'W-' + team.losses + 'L</span>';
            html += '</td>';
            html += '</tr>';
        });

        html += '</tbody></table></div>';
        return html;
    }

    function _renderTeamRoster(teamName, data) {
        var members = data.teams[teamName] || [];
        if (members.length === 0) return '';

        var isMyTeam = teamName === 'My Team';
        var borderColor = isMyTeam ? '#1565c0' : '#e65100';
        var headerBg = isMyTeam ? '#e3f2fd' : '#fff3e0';

        var html = '<div style="margin-bottom: 16px; border-radius: 8px; border: 1px solid var(--border); overflow: hidden;">';
        html += '<div style="padding: 12px 16px; background: ' + headerBg + '; border-left: 4px solid ' + borderColor + ';">';
        html += '<strong>' + _escapeHtml(teamName) + '</strong> <span style="color: var(--text-secondary); font-size: 0.85em;">(' + members.length + ' agents)</span>';
        html += '</div>';

        html += '<table style="width: 100%; border-collapse: collapse; font-size: 0.82em;">';
        html += '<thead><tr style="background: var(--bg-surface-raised);">';
        html += '<th style="padding: 6px 8px; text-align: center; width: 35px;">#</th>';
        html += '<th style="padding: 6px 8px; text-align: left;">Name</th>';
        html += '<th style="padding: 6px 8px; text-align: center;">Score</th>';
        html += '<th style="padding: 6px 8px; text-align: center;">Center Rank</th>';

        MATCHUP_METRICS.forEach(function (m) {
            html += '<th style="padding: 6px 8px; text-align: center;">' + m.label + '</th>';
        });

        html += '</tr></thead><tbody>';

        // Sort members within team by composite score
        var sorted = members.slice().sort(function (a, b) { return a.compositeScore - b.compositeScore; });

        sorted.forEach(function (r, idx) {
            var statusColor = r.trackStatusValue === 'on-track-exceptional' ? '#2e7d32' :
                r.trackStatusValue === 'on-track-successful' ? '#f57f17' : '#c62828';

            html += '<tr style="border-bottom: 1px solid var(--border); background: ' + (idx % 2 === 0 ? 'var(--bg-surface)' : 'var(--bg-surface-raised)') + ';">';
            html += '<td style="padding: 5px 8px; text-align: center; font-weight: bold;">' + (idx + 1) + '</td>';
            html += '<td style="padding: 5px 8px;">' + _escapeHtml(r.name) + '</td>';
            html += '<td style="padding: 5px 8px; text-align: center; color: ' + statusColor + '; font-weight: bold;">' + r.ratingAverage.toFixed(2) + '</td>';
            html += '<td style="padding: 5px 8px; text-align: center;">#' + r.rank + ' <span style="font-size: 0.75em; color: #888;">of ' + data.totalEmployees + '</span></td>';

            MATCHUP_METRICS.forEach(function (m) {
                var val = m.isTopLevel ? r[m.key] : (r.values ? r.values[m.key] : null);
                var metricRank = r.metricRanks?.[m.key] || '?';
                var display = val !== null && val !== undefined ? _formatMetricDisplay(m.formatKey, val) : '--';
                html += '<td style="padding: 5px 8px; text-align: center;">' + display + ' <span style="font-size: 0.72em; color: #888;">#' + metricRank + '</span></td>';
            });

            html += '</tr>';
        });

        html += '</tbody></table></div>';
        return html;
    }

    /* ── Module export ── */
    window.DevCoachModules = window.DevCoachModules || {};
    window.DevCoachModules.matchup = {
        MATCHUP_METRICS: MATCHUP_METRICS,
        resolveMyTeamLabel: resolveMyTeamLabel,
        renderMatchup: renderMatchup,
        buildMatchupData: buildMatchupData
    };
})();
