'use strict';

const { suite } = require('./harness');

/**
 * Two rules that were asked for out loud and that nothing was holding.
 *
 * 1. The standings block talks about FOUR metrics, not six.
 *
 *    rank-projection can project six: it also ranks First Call Resolution and
 *    Overall Experience, and the block was walking that whole list. The five
 *    KPIs an associate is scored on at year end are adherence, sentiment, rep
 *    satisfaction, handle time and reliability; reliability is attendance and
 *    this block does not report it, which leaves four. Ranking somebody on a
 *    metric nobody grades them on invites "so what happens if I am 40th at
 *    this", and the honest answer is nothing.
 *
 *    The existing suite did not catch the wider list because its fixture never
 *    made First Call Resolution good enough to be picked. This one does, on
 *    purpose, so the pool is tested rather than the sample.
 *
 * 2. The upload banner counts only REAL year-to-date uploads.
 *
 *    The app writes an auto-generated year-to-date row of its own and stamps it
 *    autoGeneratedYtd. Counting it meant the banner saw a current-year file on
 *    nearly every install, so "no YTD on file" could never fire and the one
 *    warning that explains why the year-pace features stay quiet was dead code
 *    that always passed. futures.findRealYtdUpload draws the same line, and the
 *    two have to agree.
 */

const WEEK_KEY = '2026-08-17|2026-08-21';

/* ── The standings pool ── */

// Peers deliberately mediocre on the four scorecard metrics and strong on the
// two that must not be reported, so anything that leaks the wider list shows up
// as an extra bullet rather than as a subtle reordering.
function peerRow(i) {
    return {
        name: 'Peer ' + String(i).padStart(2, '0'),
        totalCalls: 240,
        surveyTotal: 40,
        reliability: 4 + i * 0.5,
        metricRanks: {},
        values: {
            aht: 401 + i * 2,
            adherence: 96 - i * 0.25,
            sentiment: 95 - i * 0.2,
            associateOverall: 92 - i * 0.3
        },
        extraValues: {
            fcr: 95 - i * 0.4,
            overallExperience: 96 - i * 0.35
        }
    };
}

// Bottom of the field on all four scorecard metrics, top of it on the two that
// are out of scope. If the block ever reports what it is not asked to report,
// these are the numbers it will reach for first.
function danaRow() {
    return {
        name: 'Dana Reed',
        totalCalls: 250,
        surveyTotal: 40,
        reliability: 9,
        metricRanks: {},
        values: { aht: 470, adherence: 88.0, sentiment: 88.5, associateOverall: 82 },
        extraValues: { fcr: 99.5, overallExperience: 99.5 }
    };
}

const TEAM_PEERS = [2, 6, 10, 15, 19, 23, 27];

function loadPulse(t) {
    t.installFakeBrowser();
    const rows = [];
    for (let i = 0; i < 29; i++) rows.push(peerRow(i));
    rows.push(danaRow());

    global.weeklyData = {
        [WEEK_KEY]: {
            metadata: { periodType: 'week', startDate: '2026-08-17', endDate: '2026-08-21' },
            employees: [{ name: 'Dana Reed', totalCalls: 250, surveyTotal: 40, aht: 470, scheduleAdherence: 88, fcr: 99.5 }]
        }
    };
    global.ytdData = {};
    global.dailyData = {};

    const registry = t.loadModule('modules/metrics-registry.module.js');
    global.isReverseMetric = registry.metricsRegistryHelpers.isReverseMetric;
    global.METRICS_REGISTRY = global.window.METRICS_REGISTRY;
    global.formatDateMMDDYYYY = (s) => {
        const [year, month, day] = String(s || '').split('-');
        return year && month && day ? `${month}/${day}/${year}` : '';
    };
    global.window.analyzeTrendMetrics = () => ({ allMetrics: [] });

    t.loadModule('modules/rank-projection.module.js');
    global.window.DevCoachModules.centerRanking = {
        buildRankingsForPeriod: () => ({
            rankings: rows,
            totalEmployees: rows.length,
            source: WEEK_KEY,
            periodKey: WEEK_KEY,
            teamMembers: new Set(['Dana Reed'].concat(TEAM_PEERS.map(i => 'Peer ' + String(i).padStart(2, '0'))))
        })
    };
    return t.loadModule('modules/morning-pulse.module.js').morningPulse;
}

suite('standings scope: four metrics, not everything that has a rank', (t) => {
    const pulse = loadPulse(t);
    const block = pulse.buildStandingsBlock('Dana Reed', WEEK_KEY);

    t.check('the block still says something', block.length > 0);

    // Dana is first in the centre on both of these. If the pool were still
    // rank-projection's six, they would lead the block rather than be absent.
    t.check('First Call Resolution is not reported', block.indexOf('First Call Resolution') === -1);
    t.check('Overall Experience is not reported', block.indexOf('Overall Experience') === -1);

    // And the scorecard four are exactly what is left to report.
    const named = ['Schedule Adherence', 'Overall Sentiment', 'Rep Satisfaction', 'Average Handle Time']
        .filter(label => block.indexOf(label) > -1);
    t.check('what it does report comes from the scorecard four', named.length > 0);

    // Reliability is attendance. It is excluded twice over and neither guard is
    // allowed to be the only one.
    t.check('reliability is still absent', !/reliab/i.test(block));
});

suite('standings scope: the four are named in one place', (t) => {
    const pulse = loadPulse(t);

    // The list is its own constant rather than a filter over
    // PROJECTABLE_RANK_KEYS, so that adding a projectable metric for the
    // manager ladder cannot quietly widen what lands in somebody's inbox.
    const rp = global.window.DevCoachModules.rankProjection;
    t.check('rank-projection still offers the wider list',
        (rp.PROJECTABLE_RANK_KEYS || []).length > 4);
    t.check('and the block does not simply inherit it',
        pulse.buildStandingsBlock('Dana Reed', WEEK_KEY).indexOf('First Call Resolution') === -1);
});

/* ── Real year-to-date uploads only ── */

function loadWizard(t) {
    t.installFakeBrowser();
    global.document = {
        getElementById: () => null,
        createElement: () => ({ style: {}, dataset: {}, appendChild() {}, set textContent(v) { this._t = v; } }),
        querySelector: () => null,
        querySelectorAll: () => []
    };
    return t.loadModule('modules/upload-wizard.module.js').uploadWizard;
}

const TODAY = new Date(2026, 7, 18);   // 18 August 2026, a Tuesday

function ytdFile(endDate, extraMeta) {
    return {
        [`2026-01-01|${endDate}`]: {
            employees: [{ name: 'A' }],
            metadata: Object.assign({ startDate: '2026-01-01', endDate, periodType: 'ytd' }, extraMeta || {})
        }
    };
}

suite('upload gaps: an auto-built year-to-date file is not a year-to-date upload', (t) => {
    const wiz = loadWizard(t);

    // The row the app writes for itself, stitched from the weeks on file.
    const auto = wiz.ytdCoverage(ytdFile('2026-08-14', { autoGeneratedYtd: true }), TODAY);
    t.check('an auto-built file leaves the year uncovered', auto.isMissing === true);
    t.check('and it is not mistaken for a current-year upload', auto.hasCurrentYear === false);
    t.check('so nothing claims a closing date it does not have', auto.latestEnd === null);

    // The same file, uploaded by a person.
    const real = wiz.ytdCoverage(ytdFile('2026-08-14'), TODAY);
    t.check('a real upload does cover the year', real.isMissing === false);
    t.equal('and it keeps its closing date', real.latestEnd, '2026-08-14');
});

suite('upload gaps: a real file is still found behind an auto-built one', (t) => {
    const wiz = loadWizard(t);

    // The ordinary state of the store: a real upload from April that nobody has
    // refreshed, and a newer auto-built row sitting on top of it. Reading the
    // newest key would report the year as current and hide the staleness that
    // is the actual problem.
    const store = Object.assign({},
        ytdFile('2026-04-30'),
        ytdFile('2026-08-14', { autoGeneratedYtd: true })
    );
    const cov = wiz.ytdCoverage(store, TODAY);

    t.check('the year counts as covered', cov.hasCurrentYear === true);
    t.equal('by the real upload, not the auto one', cov.latestEnd, '2026-04-30');
    t.check('and its age is measured from that', cov.isStale === true);
    t.equal('which is the month a person would name', cov.closedMonth, 'April');
});

suite('upload gaps: nothing but auto-built rows reads as nothing at all', (t) => {
    const wiz = loadWizard(t);
    const store = Object.assign({},
        ytdFile('2026-06-30', { autoGeneratedYtd: true }),
        ytdFile('2026-08-14', { autoGeneratedYtd: true })
    );
    const cov = wiz.ytdCoverage(store, TODAY);

    t.check('two auto rows are still no upload', cov.isMissing === true);
    t.check('and staleness is not claimed about a file nobody made', cov.isStale === false);
    t.check('no month is named', cov.closedMonth === null);
});

/* ── One metric, one placing ── */

/**
 * The standings block and the near-miss line are both welcome in a one-to-one,
 * and both name a placing, but they count different fields: the block ranks
 * over the people scored on that metric ("10th of 30"), while the near-miss
 * line comes from celebrations and ranks over its display ranks for the period
 * ("#12 in the Call Center"). Two paragraphs apart in one message about one
 * metric, they read as the app contradicting itself.
 *
 * The block wins where they overlap, because it is the one that also says what
 * to do about it. The line survives for metrics the block did not reach, since
 * the block stops at three.
 */
function celebrationsStub(metricKey) {
    return {
        nearMissFor: () => ({ metricKey, label: 'Schedule Adherence', rank: 12, away: 2, bar: 10, value: 94.1 }),
        describeNearMiss: () => 'One more thing: you are 2 spots away from top 10 in Schedule Adherence.'
    };
}

suite('standings scope: the same metric is not placed twice in one message', (t) => {
    const pulse = loadPulse(t);

    global.window.DevCoachModules.celebrations = celebrationsStub('adherence');

    // The block spoke for adherence, so the tail about adherence is dropped.
    const spoken = new Set(['adherence']);
    const kept = pulse.withNearMiss('body', 'Dana Reed', WEEK_KEY, spoken);
    t.equal('the second placing is not written', kept, 'body');

    // A metric the block never reached still earns its line.
    const other = pulse.withNearMiss('body', 'Dana Reed', WEEK_KEY, new Set(['aht']));
    t.check('a metric the block missed keeps its near-miss line', other.indexOf('2 spots away') > -1);

    // No block at all means nothing to collide with.
    const none = pulse.withNearMiss('body', 'Dana Reed', WEEK_KEY, new Set());
    t.check('an empty block suppresses nothing', none.indexOf('2 spots away') > -1);

    // Callers that predate the set are unaffected.
    const legacy = pulse.withNearMiss('body', 'Dana Reed', WEEK_KEY);
    t.check('a caller passing no set behaves as it always did', legacy.indexOf('2 spots away') > -1);
});

suite('standings scope: the block reports which metrics it spoke for', (t) => {
    const pulse = loadPulse(t);

    const spoken = new Set();
    const block = pulse.buildStandingsBlock('Dana Reed', WEEK_KEY, spoken);

    t.check('the block was written', block.length > 0);
    t.check('and it recorded what it named', spoken.size > 0);

    // Whatever it recorded has to be a rank key celebrations would also use,
    // or the comparison in withNearMiss silently never matches.
    const rp = global.window.DevCoachModules.rankProjection;
    const known = Object.keys(rp.RANK_TO_REGISTRY || {});
    t.check('in the vocabulary both sides share',
        Array.from(spoken).every(k => known.indexOf(k) > -1));
    t.check('and never attendance', !spoken.has('reliability'));
});
